const fs = require('fs');

const wordTemplates = [
  { word: 'abandon', phonetic: '/əˈbændən/', pos: 'v.', meaning: '放弃；遗弃', eg: 'He abandoned his plan to travel abroad.', trans: '他放弃了出国旅行的计划。', coll: 'abandon plan; with abandon', root: 'aban- + -don' },
  { word: 'ability', phonetic: '/əˈbɪləti/', pos: 'n.', meaning: '能力', eg: 'She has the ability to speak three languages.', trans: '她有能力说三种语言。', coll: 'ability to; have ability', root: 'able + -ity' },
  { word: 'able', phonetic: '/ˈeɪbl/', pos: 'adj.', meaning: '能够的；有能力的', eg: 'I am able to finish this task on time.', trans: '我能够按时完成这项任务。', coll: 'be able to; able-bodied', root: '拉丁语 habilis' },
  { word: 'about', phonetic: '/əˈbaʊt/', pos: 'prep./adv.', meaning: '关于；大约', eg: 'Tell me something about your trip.', trans: '告诉我一些关于你旅行的事情。', coll: 'talk about; think about', root: '古英语 butan' },
  { word: 'above', phonetic: '/əˈbʌv/', pos: 'prep./adv.', meaning: '在...之上；以上', eg: 'The temperature is above 30 degrees.', trans: '气温在30度以上。', coll: 'above all; above mentioned', root: '古英语 abufan' },
  { word: 'abroad', phonetic: '/əˈbrɔːd/', pos: 'adv.', meaning: '在国外；到国外', eg: 'She studied abroad for two years.', trans: '她在国外学习了两年。', coll: 'go abroad; study abroad', root: 'a- + broad' },
  { word: 'absence', phonetic: '/ˈæbsəns/', pos: 'n.', meaning: '缺席；缺乏', eg: 'His absence from the meeting was noticed.', trans: '他缺席会议引起了注意。', coll: 'in absence; absence from', root: 'abs- + -ence' },
  { word: 'absent', phonetic: '/ˈæbsənt/', pos: 'adj.', meaning: '缺席的；不在的', eg: 'He was absent from school yesterday.', trans: '他昨天没来上学。', coll: 'be absent; absent-minded', root: 'abs- + -ent' },
  { word: 'absolute', phonetic: '/ˈæbsəluːt/', pos: 'adj.', meaning: '绝对的；完全的', eg: 'You have my absolute support.', trans: '我绝对支持你。', coll: 'absolute value; absolute majority', root: 'abs- + solut-' },
  { word: 'absorb', phonetic: '/əbˈsɔːb/', pos: 'v.', meaning: '吸收；吸引', eg: 'Plants absorb carbon dioxide.', trans: '植物吸收二氧化碳。', coll: 'absorb water; absorb knowledge', root: 'abs- + sorb' },
  { word: 'abstract', phonetic: '/ˈæbstrækt/', pos: 'adj./n.', meaning: '抽象的；摘要', eg: 'This is an abstract concept.', trans: '这是一个抽象概念。', coll: 'abstract concept; abstract thinking', root: 'abs- + tract' },
  { word: 'academic', phonetic: '/ˌækəˈdemɪk/', pos: 'adj./n.', meaning: '学术的；学者', eg: 'He has an academic background in physics.', trans: '他有物理学学术背景。', coll: 'academic degree; academic paper', root: 'academy + -ic' },
  { word: 'accept', phonetic: '/əkˈsept/', pos: 'v.', meaning: '接受；认可', eg: 'She accepted the job offer.', trans: '她接受了这份工作邀请。', coll: 'accept invitation; accept responsibility', root: 'ac- + cept' },
  { word: 'access', phonetic: '/ˈækses/', pos: 'n./v.', meaning: '通道；访问', eg: 'You can access the internet from here.', trans: '你可以从这里访问互联网。', coll: 'have access; access to', root: 'ac- + cess' },
  { word: 'accident', phonetic: '/ˈæksɪdənt/', pos: 'n.', meaning: '事故；意外', eg: 'He was injured in a car accident.', trans: '他在一场车祸中受伤。', coll: 'by accident; traffic accident', root: 'accid- + -ent' },
  { word: 'accompany', phonetic: '/əˈkʌmpəni/', pos: 'v.', meaning: '陪伴；伴随', eg: 'She accompanied him to the doctor.', trans: '她陪他去看医生。', coll: 'accompany someone; be accompanied', root: 'ac- + company' },
  { word: 'accomplish', phonetic: '/əˈkʌmplɪʃ/', pos: 'v.', meaning: '完成；实现', eg: 'We accomplished our goal ahead of schedule.', trans: '我们提前完成了目标。', coll: 'accomplish task; accomplish mission', root: 'ac- + complish' },
  { word: 'according', phonetic: '/əˈkɔːrdɪŋ/', pos: 'prep.', meaning: '根据；按照', eg: 'According to the report, sales increased.', trans: '根据报告，销售额有所增长。', coll: 'according to; accordingly', root: 'accord + -ing' },
  { word: 'account', phonetic: '/əˈkaʊnt/', pos: 'n./v.', meaning: '账户；解释', eg: 'I opened a new bank account.', trans: '我开了一个新的银行账户。', coll: 'bank account; on account of', root: 'ac- + count' },
  { word: 'accurate', phonetic: '/ˈækjərət/', pos: 'adj.', meaning: '准确的；精确的', eg: 'Please provide accurate information.', trans: '请提供准确的信息。', coll: 'accurate measurement; accurate info', root: 'accur- + -ate' },
  { word: 'achieve', phonetic: '/əˈtʃiːv/', pos: 'v.', meaning: '实现；达到', eg: 'She achieved her dream of becoming a doctor.', trans: '她实现了当医生的梦想。', coll: 'achieve goal; achieve dream', root: 'a- + chieve' },
  { word: 'acquire', phonetic: '/əˈkwaɪər/', pos: 'v.', meaning: '获得；获取', eg: 'He acquired a new skill through practice.', trans: '他通过练习获得了一项新技能。', coll: 'acquire knowledge; acquire habit', root: 'ac- + quire' },
  { word: 'across', phonetic: '/əˈkrɔːs/', pos: 'prep./adv.', meaning: '穿过；横过', eg: 'The river flows across the valley.', trans: '河流穿过山谷。', coll: 'come across; run across', root: 'a- + cross' },
  { word: 'action', phonetic: '/ˈækʃən/', pos: 'n.', meaning: '行动；动作', eg: 'We need to take immediate action.', trans: '我们需要立即采取行动。', coll: 'take action; in action', root: 'act + -ion' },
  { word: 'active', phonetic: '/ˈæktɪv/', pos: 'adj.', meaning: '积极的；活跃的', eg: 'She is an active member of the club.', trans: '她是俱乐部的积极成员。', coll: 'active participation; stay active', root: 'act + -ive' },
  { word: 'activity', phonetic: '/ækˈtɪvəti/', pos: 'n.', meaning: '活动；行动', eg: 'There are many activities for children.', trans: '有很多适合儿童的活动。', coll: 'physical activity; outdoor activity', root: 'active + -ity' },
  { word: 'actual', phonetic: '/ˈæktʃuəl/', pos: 'adj.', meaning: '实际的；真实的', eg: 'The actual cost was higher than expected.', trans: '实际成本比预期更高。', coll: 'in actual fact; actual situation', root: 'act + -ual' },
  { word: 'adapt', phonetic: '/əˈdæpt/', pos: 'v.', meaning: '适应；改编', eg: 'It takes time to adapt to a new environment.', trans: '适应新环境需要时间。', coll: 'adapt to; adapt oneself', root: 'ad- + apt' },
  { word: 'add', phonetic: '/æd/', pos: 'v.', meaning: '添加；增加', eg: 'Please add some sugar to the tea.', trans: '请在茶里加些糖。', coll: 'add up; add to', root: '拉丁语 addere' },
  { word: 'addition', phonetic: '/əˈdɪʃən/', pos: 'n.', meaning: '添加；加法', eg: 'In addition, we need more supplies.', trans: '此外，我们还需要更多物资。', coll: 'in addition; in addition to', root: 'add + -ition' },
  { word: 'additional', phonetic: '/əˈdɪʃənl/', pos: 'adj.', meaning: '额外的；附加的', eg: 'We need additional funding for the project.', trans: '我们需要为这个项目追加资金。', coll: 'additional cost; additional help', root: 'addition + -al' },
  { word: 'address', phonetic: '/əˈdres/', pos: 'n./v.', meaning: '地址；演讲', eg: 'Please write your address here.', trans: '请在这里写下你的地址。', coll: 'home address; email address', root: 'ad- + dress' },
  { word: 'adequate', phonetic: '/ˈædɪkwət/', pos: 'adj.', meaning: '足够的；适当的', eg: 'We have adequate supplies for the trip.', trans: '我们有足够的物资供旅行使用。', coll: 'adequate supply; adequate support', root: 'ad- + equate' },
  { word: 'adjust', phonetic: '/əˈdʒʌst/', pos: 'v.', meaning: '调整；适应', eg: 'Please adjust the temperature.', trans: '请调整温度。', coll: 'adjust to; adjust oneself', root: 'ad- + just' },
  { word: 'administration', phonetic: '/ədˌmɪnɪˈstreɪʃən/', pos: 'n.', meaning: '管理；行政', eg: 'The administration has announced new policies.', trans: '管理层宣布了新政策。', coll: 'business admin; public admin', root: 'administr- + -ation' },
  { word: 'admire', phonetic: '/ədˈmaɪər/', pos: 'v.', meaning: '钦佩；赞美', eg: 'I admire her courage and determination.', trans: '我钦佩她的勇气和决心。', coll: 'admire someone; admire greatly', root: 'ad- + mir' },
  { word: 'admit', phonetic: '/ədˈmɪt/', pos: 'v.', meaning: '承认；允许进入', eg: 'He finally admitted his mistake.', trans: '他最终承认了自己的错误。', coll: 'admit to; admit of', root: 'ad- + mit' },
  { word: 'adopt', phonetic: '/əˈdɒpt/', pos: 'v.', meaning: '采纳；收养', eg: 'The committee adopted the new proposal.', trans: '委员会采纳了新提案。', coll: 'adopt policy; adopt child', root: 'ad- + opt' },
  { word: 'advance', phonetic: '/ədˈvɑːns/', pos: 'v./n.', meaning: '前进；进展', eg: 'We need to advance our plans.', trans: '我们需要推进我们的计划。', coll: 'in advance; advance towards', root: 'ad- + vance' },
  { word: 'advantage', phonetic: '/ədˈvɑːntɪdʒ/', pos: 'n.', meaning: '优势；有利条件', eg: 'This gives us a competitive advantage.', trans: '这给了我们竞争优势。', coll: 'take advantage; competitive advantage', root: 'advance + -age' },
  { word: 'adventure', phonetic: '/ədˈventʃər/', pos: 'n.', meaning: '冒险；奇遇', eg: 'Life is an adventure.', trans: '生活就是一场冒险。', coll: 'adventure story; adventure trip', root: 'ad- + venture' },
  { word: 'advertise', phonetic: '/ˈædvətaɪz/', pos: 'v.', meaning: '做广告；宣传', eg: 'They advertise their products online.', trans: '他们在网上宣传产品。', coll: 'advertise online; advertise for', root: 'ad- + vert + -ise' },
  { word: 'advice', phonetic: '/ədˈvaɪs/', pos: 'n.', meaning: '建议；忠告', eg: 'Can you give me some advice?', trans: '你能给我一些建议吗？', coll: 'give advice; take advice', root: 'advise 的名词' },
  { word: 'advise', phonetic: '/ədˈvaɪz/', pos: 'v.', meaning: '建议；劝告', eg: 'I advise you to reconsider.', trans: '我建议你重新考虑。', coll: 'advise against; advise to', root: 'ad- + vise' },
  { word: 'affair', phonetic: '/əˈfeər/', pos: 'n.', meaning: '事务；事件', eg: 'This is a personal affair.', trans: '这是私事。', coll: 'state affairs; public affairs', root: 'af- + fair' },
  { word: 'affect', phonetic: '/əˈfekt/', pos: 'v.', meaning: '影响；打动', eg: 'The weather affects our mood.', trans: '天气影响我们的心情。', coll: 'be affected; affect greatly', root: 'af- + fect' },
  { word: 'afford', phonetic: '/əˈfɔːrd/', pos: 'v.', meaning: '负担得起；提供', eg: 'I can\'t afford a new car.', trans: '我买不起新车。', coll: 'can afford; afford to', root: 'af- + ford' },
  { word: 'afraid', phonetic: '/əˈfreɪd/', pos: 'adj.', meaning: '害怕的；担心的', eg: 'She is afraid of spiders.', trans: '她害怕蜘蛛。', coll: 'be afraid; I\'m afraid', root: '古英语 āfǣr' },
  { word: 'after', phonetic: '/ˈɑːftər/', pos: 'prep./adv.', meaning: '在...之后；后来', eg: 'We\'ll meet after class.', trans: '我们课后见面。', coll: 'after all; look after', root: '古英语 æfter' },
  { word: 'afternoon', phonetic: '/ˌɑːftərˈnuːn/', pos: 'n.', meaning: '下午', eg: 'Let\'s meet in the afternoon.', trans: '我们下午见面吧。', coll: 'in afternoon; afternoon tea', root: 'after + noon' },
  { word: 'again', phonetic: '/əˈɡen/', pos: 'adv.', meaning: '再次；又', eg: 'Please try again.', trans: '请再试一次。', coll: 'again and again; once again', root: '古英语 ongean' },
  { word: 'against', phonetic: '/əˈɡeɪnst/', pos: 'prep.', meaning: '反对；靠着', eg: 'She is against the proposal.', trans: '她反对这个提议。', coll: 'go against; against wall', root: '古英语 ongean' },
  { word: 'age', phonetic: '/eɪdʒ/', pos: 'n./v.', meaning: '年龄；变老', eg: 'What\'s your age?', trans: '你几岁了？', coll: 'at age; come of age', root: '拉丁语 aetas' },
  { word: 'agency', phonetic: '/ˈeɪdʒənsi/', pos: 'n.', meaning: '代理；机构', eg: 'She works at a travel agency.', trans: '她在一家旅行社工作。', coll: 'travel agency; ad agency', root: 'agent + -cy' },
  { word: 'agent', phonetic: '/ˈeɪdʒənt/', pos: 'n.', meaning: '代理人；代理', eg: 'He is my insurance agent.', trans: '他是我的保险代理人。', coll: 'real estate agent; secret agent', root: 'ag- + -ent' },
  { word: 'aggressive', phonetic: '/əˈɡresɪv/', pos: 'adj.', meaning: '侵略性的；积极的', eg: 'He has an aggressive business strategy.', trans: '他有积极的商业策略。', coll: 'aggressive behavior; aggressive market', root: 'aggress + -ive' },
  { word: 'ago', phonetic: '/əˈɡoʊ/', pos: 'adv.', meaning: '以前', eg: 'I met her three years ago.', trans: '我三年前见过她。', coll: 'long ago; years ago', root: '古英语 āgān' },
  { word: 'agree', phonetic: '/əˈɡriː/', pos: 'v.', meaning: '同意；一致', eg: 'I agree with your opinion.', trans: '我同意你的看法。', coll: 'agree on; agree to', root: 'a- + gree' },
  { word: 'agreement', phonetic: '/əˈɡriːmənt/', pos: 'n.', meaning: '协议；同意', eg: 'We reached an agreement.', trans: '我们达成了协议。', coll: 'reach agreement; in agreement', root: 'agree + -ment' },
  { word: 'agriculture', phonetic: '/ˈæɡrɪkʌltʃər/', pos: 'n.', meaning: '农业；农学', eg: 'Agriculture is vital for food security.', trans: '农业对粮食安全至关重要。', coll: 'modern agriculture; agri products', root: 'agri- + culture' },
  { word: 'ahead', phonetic: '/əˈhed/', pos: 'adv.', meaning: '向前；提前', eg: 'There are challenges ahead.', trans: '前方有挑战。', coll: 'ahead of; go ahead', root: 'a- + head' },
  { word: 'aid', phonetic: '/eɪd/', pos: 'n./v.', meaning: '援助；帮助', eg: 'They provided aid to the victims.', trans: '他们向受害者提供援助。', coll: 'first aid; foreign aid', root: '拉丁语 adjuvare' },
  { word: 'aim', phonetic: '/eɪm/', pos: 'n./v.', meaning: '目标；瞄准', eg: 'What is your aim in life?', trans: '你的人生目标是什么？', coll: 'aim at; aim for', root: '古法语 aesmer' },
  { word: 'air', phonetic: '/eər/', pos: 'n./v.', meaning: '空气；播出', eg: 'The air is fresh here.', trans: '这里的空气很清新。', coll: 'fresh air; by air', root: '拉丁语 aer' },
  { word: 'airport', phonetic: '/ˈeərpɔːrt/', pos: 'n.', meaning: '机场', eg: 'We arrived at the airport early.', trans: '我们早早到达了机场。', coll: 'international airport; airport terminal', root: 'air + port' },
  { word: 'alarm', phonetic: '/əˈlɑːrm/', pos: 'n./v.', meaning: '警报；使惊恐', eg: 'The fire alarm went off.', trans: '火警警报响了。', coll: 'fire alarm; alarm clock', root: '意大利语 allarme' },
  { word: 'album', phonetic: '/ˈælbəm/', pos: 'n.', meaning: '相册；专辑', eg: 'I received a photo album as a gift.', trans: '我收到了一本相册作为礼物。', coll: 'photo album; music album', root: '拉丁语 album' },
  { word: 'alcohol', phonetic: '/ˈælkəhɔːl/', pos: 'n.', meaning: '酒精；酒', eg: 'He doesn\'t drink alcohol.', trans: '他不喝酒。', coll: 'alcohol free; alcohol content', root: '阿拉伯语 al-kuhl' },
  { word: 'alike', phonetic: '/əˈlaɪk/', pos: 'adj./adv.', meaning: '相似的；同样地', eg: 'The twins look very much alike.', trans: '这对双胞胎长得非常像。', coll: 'look alike; think alike', root: 'a- + like' },
  { word: 'alive', phonetic: '/əˈlaɪv/', pos: 'adj.', meaning: '活着的；活跃的', eg: 'She is still alive.', trans: '她还活着。', coll: 'keep alive; come alive', root: 'a- + live' },
  { word: 'all', phonetic: '/ɔːl/', pos: 'adj./adv./n.', meaning: '所有的；全部', eg: 'All students must attend.', trans: '所有学生都必须参加。', coll: 'all over; all right', root: '古英语 eall' },
  { word: 'allow', phonetic: '/əˈlaʊ/', pos: 'v.', meaning: '允许；准许', eg: 'Smoking is not allowed here.', trans: '这里不允许吸烟。', coll: 'allow for; allow to', root: '古英语 ālǣwan' },
  { word: 'almost', phonetic: '/ˈɔːlmoʊst/', pos: 'adv.', meaning: '几乎；差不多', eg: 'I almost missed the bus.', trans: '我差点错过公交车。', coll: 'almost all; almost every', root: 'all + most' },
  { word: 'alone', phonetic: '/əˈloʊn/', pos: 'adj./adv.', meaning: '单独的；独自', eg: 'She lives alone.', trans: '她独自生活。', coll: 'leave alone; let alone', root: 'a- + lone' },
  { word: 'along', phonetic: '/əˈlɔːŋ/', pos: 'prep./adv.', meaning: '沿着；一起', eg: 'Walk along this street.', trans: '沿着这条街走。', coll: 'along with; get along', root: '古英语 andlang' },
  { word: 'aloud', phonetic: '/əˈlaʊd/', pos: 'adv.', meaning: '大声地；出声地', eg: 'Please read the text aloud.', trans: '请大声朗读课文。', coll: 'read aloud; think aloud', root: 'a- + loud' },
  { word: 'alphabet', phonetic: '/ˈælfəbet/', pos: 'n.', meaning: '字母表', eg: 'Children learn the alphabet in kindergarten.', trans: '孩子们在幼儿园学习字母表。', coll: 'English alphabet; alphabet order', root: '希腊语 alpha+beta' },
  { word: 'already', phonetic: '/ɔːlˈredi/', pos: 'adv.', meaning: '已经', eg: 'I have already finished my homework.', trans: '我已经完成作业了。', coll: 'already know; already done', root: 'all + ready' },
  { word: 'also', phonetic: '/ˈɔːlsoʊ/', pos: 'adv.', meaning: '也；同样', eg: 'I also like reading.', trans: '我也喜欢阅读。', coll: 'not only but also', root: 'all + so' },
  { word: 'alter', phonetic: '/ˈɔːltər/', pos: 'v.', meaning: '改变；修改', eg: 'We need to alter our plans.', trans: '我们需要修改计划。', coll: 'alter course; alter design', root: '拉丁语 alter' },
  { word: 'alternative', phonetic: '/ɔːlˈtɜːrnətɪv/', pos: 'adj./n.', meaning: '替代的；替代品', eg: 'We have alternative options.', trans: '我们有替代方案。', coll: 'alternative energy; alternative plan', root: 'alter + -native' },
  { word: 'although', phonetic: '/ɔːlˈðoʊ/', pos: 'conj.', meaning: '虽然；尽管', eg: 'Although it rained, we went out.', trans: '虽然下雨了，我们还是出去了。', coll: 'although yet; although still', root: 'all + though' },
  { word: 'always', phonetic: '/ˈɔːlweɪz/', pos: 'adv.', meaning: '总是；一直', eg: 'She always arrives on time.', trans: '她总是准时到达。', coll: 'always remember; almost always', root: 'all + ways' },
  { word: 'amaze', phonetic: '/əˈmeɪz/', pos: 'v.', meaning: '使惊讶；使惊奇', eg: 'The view amazed everyone.', trans: '景色让所有人都感到惊讶。', coll: 'be amazed; amazing discovery', root: 'a- + maze' },
  { word: 'ambition', phonetic: '/æmˈbɪʃən/', pos: 'n.', meaning: '野心；抱负', eg: 'He has great ambition.', trans: '他有远大的抱负。', coll: 'political ambition; achieve ambition', root: 'amb- + -ition' },
  { word: 'ambitious', phonetic: '/æmˈbɪʃəs/', pos: 'adj.', meaning: '有野心的；有抱负的', eg: 'She is an ambitious young woman.', trans: '她是一个有抱负的年轻女性。', coll: 'ambitious goal; ambitious project', root: 'ambition + -ous' },
  { word: 'amount', phonetic: '/əˈmaʊnt/', pos: 'n./v.', meaning: '数量；总计', eg: 'The amount is too large.', trans: '数量太大了。', coll: 'large amount; amount to', root: 'a- + mount' },
  { word: 'analysis', phonetic: '/əˈnæləsɪs/', pos: 'n.', meaning: '分析；解析', eg: 'We need to do a thorough analysis.', trans: '我们需要进行彻底分析。', coll: 'data analysis; market analysis', root: 'ana- + lysis' },
  { word: 'analyze', phonetic: '/ˈænəlaɪz/', pos: 'v.', meaning: '分析；研究', eg: 'Let\'s analyze the problem.', trans: '让我们分析这个问题。', coll: 'analyze results; analyze problem', root: 'analysis 的动词' },
  { word: 'ancestor', phonetic: '/ˈænsestər/', pos: 'n.', meaning: '祖先；祖宗', eg: 'We traced our ancestors back to the 18th century.', trans: '我们追溯祖先到18世纪。', coll: 'common ancestor; ancestor worship', root: 'ante- + cest-' },
  { word: 'ancient', phonetic: '/ˈeɪnʃənt/', pos: 'adj.', meaning: '古代的；古老的', eg: 'This is an ancient city.', trans: '这是一座古城。', coll: 'ancient history; ancient civilization', root: '拉丁语 antiquus' },
  { word: 'and', phonetic: '/ænd/', pos: 'conj.', meaning: '和；与', eg: 'You and I are friends.', trans: '你和我是朋友。', coll: 'and so on; and then', root: '古英语 and' },
  { word: 'anger', phonetic: '/ˈæŋɡər/', pos: 'n./v.', meaning: '愤怒；使生气', eg: 'He tried to hide his anger.', trans: '他试图掩饰自己的愤怒。', coll: 'in anger; show anger', root: '古英语 angr' },
  { word: 'angle', phonetic: '/ˈæŋɡl/', pos: 'n./v.', meaning: '角度；倾斜', eg: 'The angle is 45 degrees.', trans: '角度是45度。', coll: 'at angle; right angle', root: '拉丁语 angulus' },
  { word: 'angry', phonetic: '/ˈæŋɡri/', pos: 'adj.', meaning: '生气的；愤怒的', eg: 'She was angry about the delay.', trans: '她对延误感到生气。', coll: 'be angry; get angry', root: 'anger + -y' },
  { word: 'animal', phonetic: '/ˈænɪməl/', pos: 'n.', meaning: '动物', eg: 'The zoo has many animals.', trans: '动物园有很多动物。', coll: 'wild animal; animal rights', root: '拉丁语 animalis' },
  { word: 'announce', phonetic: '/əˈnaʊns/', pos: 'v.', meaning: '宣布；宣告', eg: 'They announced their engagement.', trans: '他们宣布了订婚。', coll: 'announce publicly; announce decision', root: 'an- + nounce' },
  { word: 'announcement', phonetic: '/əˈnaʊnsmənt/', pos: 'n.', meaning: '公告；通知', eg: 'There will be an important announcement.', trans: '将有一个重要公告。', coll: 'make announcement; official announcement', root: 'announce + -ment' },
  { word: 'annoy', phonetic: '/əˈnɔɪ/', pos: 'v.', meaning: '使烦恼；打扰', eg: 'Please don\'t annoy me.', trans: '请不要烦我。', coll: 'be annoyed; annoy someone', root: '古法语 anoier' },
  { word: 'annual', phonetic: '/ˈænjuəl/', pos: 'adj.', meaning: '每年的；年度的', eg: 'We have an annual meeting.', trans: '我们每年开一次年会。', coll: 'annual report; annual event', root: '拉丁语 annus' },
  { word: 'another', phonetic: '/əˈnʌðər/', pos: 'adj./pron.', meaning: '另一个；再一个', eg: 'Can I have another cup?', trans: '我能再要一杯吗？', coll: 'one another; another way', root: 'an- + other' },
  { word: 'answer', phonetic: '/ˈɑːnsər/', pos: 'n./v.', meaning: '回答；答案', eg: 'Please answer my question.', trans: '请回答我的问题。', coll: 'answer phone; answer question', root: '古英语 andswaru' },
  { word: 'anxiety', phonetic: '/æŋˈzaɪəti/', pos: 'n.', meaning: '焦虑；忧虑', eg: 'She felt anxiety before the exam.', trans: '考试前她感到焦虑。', coll: 'feel anxiety; anxiety disorder', root: '拉丁语 anxietas' },
  { word: 'anxious', phonetic: '/ˈæŋkʃəs/', pos: 'adj.', meaning: '焦虑的；渴望的', eg: 'He is anxious to know the result.', trans: '他急于知道结果。', coll: 'anxious about; anxious to', root: 'anxiety + -ous' },
  { word: 'any', phonetic: '/ˈeni/', pos: 'adj./pron.', meaning: '任何；一些', eg: 'Do you have any questions?', trans: '你有问题吗？', coll: 'any time; any way', root: '古英语 ænig' },
  { word: 'anybody', phonetic: '/ˈenibʌdi/', pos: 'pron.', meaning: '任何人', eg: 'Anybody can do this.', trans: '任何人都能做到。', coll: 'anybody else; anybody there', root: 'any + body' },
  { word: 'anyone', phonetic: '/ˈeniwʌn/', pos: 'pron.', meaning: '任何人', eg: 'Anyone can join the club.', trans: '任何人都可以加入俱乐部。', coll: 'anyone else; anyone knows', root: 'any + one' },
  { word: 'anything', phonetic: '/ˈeniθɪŋ/', pos: 'pron.', meaning: '任何事；任何东西', eg: 'Is there anything I can do?', trans: '有什么我能做的吗？', coll: 'anything but; anything else', root: 'any + thing' },
  { word: 'anyway', phonetic: '/ˈeniweɪ/', pos: 'adv.', meaning: '无论如何；不管怎样', eg: 'Anyway, I will try my best.', trans: '无论如何，我会尽力。', coll: 'anyway you look', root: 'any + way' },
  { word: 'anywhere', phonetic: '/ˈeniwer/', pos: 'adv.', meaning: '任何地方', eg: 'You can go anywhere you want.', trans: '你可以去任何你想去的地方。', coll: 'anywhere else; not anywhere', root: 'any + where' },
  { word: 'apart', phonetic: '/əˈpɑːrt/', pos: 'adv./adj.', meaning: '分开；分离的', eg: 'The two buildings are 10 meters apart.', trans: '这两栋楼相距10米。', coll: 'apart from; take apart', root: 'a- + part' },
  { word: 'apartment', phonetic: '/əˈpɑːrtmənt/', pos: 'n.', meaning: '公寓；套房', eg: 'I live in a small apartment.', trans: '我住在一个小公寓里。', coll: 'apartment building; studio apartment', root: 'apart + -ment' },
  { word: 'apologize', phonetic: '/əˈpɒlədʒaɪz/', pos: 'v.', meaning: '道歉；认错', eg: 'I apologize for being late.', trans: '我为迟到道歉。', coll: 'apologize to; apologize for', root: '希腊语 apologos' },
  { word: 'apology', phonetic: '/əˈpɒlədʒi/', pos: 'n.', meaning: '道歉；歉意', eg: 'Please accept my apology.', trans: '请接受我的道歉。', coll: 'make apology; sincere apology', root: 'apologize 的名词' },
  { word: 'apparent', phonetic: '/əˈpærənt/', pos: 'adj.', meaning: '明显的；表面上的', eg: 'It is apparent that he is lying.', trans: '很明显他在撒谎。', coll: 'apparent reason; apparent difference', root: '拉丁语 apparens' },
  { word: 'apparently', phonetic: '/əˈpærəntli/', pos: 'adv.', meaning: '显然；似乎', eg: 'Apparently, he forgot the meeting.', trans: '显然他忘记了会议。', coll: 'apparently true; apparently not', root: 'apparent + -ly' },
  { word: 'appeal', phonetic: '/əˈpiːl/', pos: 'n./v.', meaning: '呼吁；吸引', eg: 'The appeal for help was successful.', trans: '求助呼吁成功了。', coll: 'appeal to; make appeal', root: '拉丁语 appellare' },
  { word: 'appear', phonetic: '/əˈpɪər/', pos: 'v.', meaning: '出现；似乎', eg: 'She appeared at the door.', trans: '她出现在门口。', coll: 'appear to be; appear in', root: '拉丁语 apparere' },
  { word: 'appearance', phonetic: '/əˈpɪərəns/', pos: 'n.', meaning: '外貌；出现', eg: 'Don\'t judge by appearance.', trans: '不要以貌取人。', coll: 'make appearance; good appearance', root: 'appear + -ance' },
  { word: 'application', phonetic: '/ˌæplɪˈkeɪʃən/', pos: 'n.', meaning: '应用；申请', eg: 'I submitted my application.', trans: '我提交了申请。', coll: 'job application; application form', root: 'apply + -ation' },
  { word: 'apply', phonetic: '/əˈplaɪ/', pos: 'v.', meaning: '申请；应用', eg: 'I want to apply for this job.', trans: '我想申请这份工作。', coll: 'apply for; apply to', root: '拉丁语 applicare' },
  { word: 'appoint', phonetic: '/əˈpɔɪnt/', pos: 'v.', meaning: '任命；约定', eg: 'They appointed him as manager.', trans: '他们任命他为经理。', coll: 'appoint as; appoint to', root: '古法语 apointer' },
  { word: 'appointment', phonetic: '/əˈpɔɪntmənt/', pos: 'n.', meaning: '约会；任命', eg: 'I have an appointment at 3 pm.', trans: '我下午3点有个约会。', coll: 'make appointment; keep appointment', root: 'appoint + -ment' },
  { word: 'appreciate', phonetic: '/əˈpriːʃieɪt/', pos: 'v.', meaning: '欣赏；感激', eg: 'I appreciate your help.', trans: '我感激你的帮助。', coll: 'appreciate beauty; appreciate help', root: '拉丁语 appretiatus' },
  { word: 'approach', phonetic: '/əˈproʊtʃ/', pos: 'n./v.', meaning: '方法；接近', eg: 'This is a new approach.', trans: '这是一种新方法。', coll: 'approach to; new approach', root: '拉丁语 appropiare' },
  { word: 'appropriate', phonetic: '/əˈproʊpriət/', pos: 'adj./v.', meaning: '适当的；拨出', eg: 'Please choose an appropriate time.', trans: '请选择一个合适的时间。', coll: 'appropriate for; appropriate measure', root: '拉丁语 appropriatus' },
  { word: 'approval', phonetic: '/əˈpruːvl/', pos: 'n.', meaning: '批准；认可', eg: 'The plan needs approval.', trans: '这个计划需要批准。', coll: 'give approval; get approval', root: 'approve 的名词' },
  { word: 'approve', phonetic: '/əˈpruːv/', pos: 'v.', meaning: '批准；赞成', eg: 'The committee approved the plan.', trans: '委员会批准了这个计划。', coll: 'approve of; approve plan', root: '拉丁语 approbare' },
  { word: 'approximately', phonetic: '/əˈprɒksɪmətli/', pos: 'adv.', meaning: '大约；近似', eg: 'There are approximately 200 people.', trans: '大约有200人。', coll: 'approximately equal; approximately half', root: '拉丁语 approximatus' },
  { word: 'arbitrary', phonetic: '/ˈɑːrbɪtreri/', pos: 'adj.', meaning: '任意的；武断的', eg: 'This is an arbitrary decision.', trans: '这是一个武断的决定。', coll: 'arbitrary choice; arbitrary rule', root: '拉丁语 arbitrarius' },
  { word: 'arch', phonetic: '/ɑːrtʃ/', pos: 'n./v.', meaning: '拱门；拱起', eg: 'The bridge has a stone arch.', trans: '这座桥有一个石拱门。', coll: 'arch bridge; arch over', root: '拉丁语 arcus' },
  { word: 'architect', phonetic: '/ˈɑːrkɪtekt/', pos: 'n.', meaning: '建筑师；设计师', eg: 'He is a famous architect.', trans: '他是一位著名的建筑师。', coll: 'chief architect; software architect', root: '希腊语 architekton' },
  { word: 'architecture', phonetic: '/ˈɑːrkɪtektʃər/', pos: 'n.', meaning: '建筑；建筑学', eg: 'I study architecture at university.', trans: '我在大学学习建筑学。', coll: 'modern architecture; classical architecture', root: 'architect + -ure' },
  { word: 'area', phonetic: '/ˈeriə/', pos: 'n.', meaning: '区域；面积', eg: 'This area is very beautiful.', trans: '这个区域非常美丽。', coll: 'urban area; rural area', root: '拉丁语 area' },
  { word: 'argue', phonetic: '/ˈɑːrɡjuː/', pos: 'v.', meaning: '争论；辩论', eg: 'They argued about the plan.', trans: '他们为这个计划争论。', coll: 'argue with; argue about', root: '拉丁语 arguere' },
  { word: 'argument', phonetic: '/ˈɑːrɡjumənt/', pos: 'n.', meaning: '论点；争论', eg: 'His argument is very strong.', trans: '他的论点非常有力。', coll: 'strong argument; against argument', root: 'argue + -ment' },
  { word: 'arise', phonetic: '/əˈraɪz/', pos: 'v.', meaning: '出现；产生', eg: 'Problems may arise at any time.', trans: '问题可能随时出现。', coll: 'arise from; arise out of', root: '古英语 arisan' },
  { word: 'arithmetic', phonetic: '/əˈrɪθmətɪk/', pos: 'n.', meaning: '算术；计算', eg: 'Children learn arithmetic in school.', trans: '孩子们在学校学习算术。', coll: 'arithmetic operation; mental arithmetic', root: '希腊语 arithmos' },
  { word: 'arm', phonetic: '/ɑːrm/', pos: 'n./v.', meaning: '手臂；武装', eg: 'He raised his arm.', trans: '他举起了手臂。', coll: 'arm in arm; take up arms', root: '古英语 earm' },
  { word: 'army', phonetic: '/ˈɑːrmi/', pos: 'n.', meaning: '军队；陆军', eg: 'He joined the army last year.', trans: '他去年参军了。', coll: 'army officer; army base', root: '拉丁语 arma' },
  { word: 'around', phonetic: '/əˈraʊnd/', pos: 'prep./adv.', meaning: '围绕；大约', eg: 'There are around 50 people.', trans: '大约有50人。', coll: 'around corner; turn around', root: '古英语 andround' },
  { word: 'arrange', phonetic: '/əˈreɪndʒ/', pos: 'v.', meaning: '安排；整理', eg: 'Please arrange the meeting.', trans: '请安排会议。', coll: 'arrange for; arrange in order', root: '古法语 arranger' },
  { word: 'arrangement', phonetic: '/əˈreɪndʒmənt/', pos: 'n.', meaning: '安排；布置', eg: 'The arrangement is perfect.', trans: '安排很完美。', coll: 'seating arrangement; make arrangements', root: 'arrange + -ment' },
  { word: 'arrest', phonetic: '/əˈrest/', pos: 'v./n.', meaning: '逮捕；拘留', eg: 'The police arrested the suspect.', trans: '警察逮捕了嫌疑犯。', coll: 'under arrest; arrest warrant', root: '拉丁语 arrestare' },
  { word: 'arrival', phonetic: '/əˈraɪvl/', pos: 'n.', meaning: '到达；到来', eg: 'His arrival was unexpected.', trans: '他的到来出乎意料。', coll: 'on arrival; arrival time', root: 'arrive 的名词' },
  { word: 'arrive', phonetic: '/əˈraɪv/', pos: 'v.', meaning: '到达；抵达', eg: 'We arrived at the station.', trans: '我们到达了车站。', coll: 'arrive at; arrive in', root: '拉丁语 arrivare' },
  { word: 'arrow', phonetic: '/ˈæroʊ/', pos: 'n.', meaning: '箭头；箭', eg: 'The arrow hit the target.', trans: '箭射中了目标。', coll: 'arrowhead; arrow sign', root: '古英语 arwe' },
  { word: 'art', phonetic: '/ɑːrt/', pos: 'n./adj.', meaning: '艺术；艺术的', eg: 'Art is everywhere.', trans: '艺术无处不在。', coll: 'modern art; art gallery', root: '拉丁语 ars' },
  { word: 'article', phonetic: '/ˈɑːrtɪkl/', pos: 'n.', meaning: '文章；物品', eg: 'I read an interesting article.', trans: '我读了一篇有趣的文章。', coll: 'news article; article of clothing', root: '拉丁语 articulus' },
  { word: 'artificial', phonetic: '/ˌɑːrtɪˈfɪʃəl/', pos: 'adj.', meaning: '人工的；人造的', eg: 'This is an artificial flower.', trans: '这是一朵人造花。', coll: 'artificial intelligence; artificial flower', root: '拉丁语 artificialis' },
  { word: 'artist', phonetic: '/ˈɑːrtɪst/', pos: 'n.', meaning: '艺术家；艺人', eg: 'She is a talented artist.', trans: '她是一位有才华的艺术家。', coll: 'pop artist; street artist', root: 'art + -ist' },
  { word: 'as', phonetic: '/æz/', pos: 'prep./conj.', meaning: '作为；像', eg: 'Treat me as your friend.', trans: '把我当作你的朋友。', coll: 'as well as; as if', root: '古英语 æs' },
  { word: 'ash', phonetic: '/æʃ/', pos: 'n.', meaning: '灰；灰烬', eg: 'The fire left only ash.', trans: '大火只留下灰烬。', coll: 'ash tree; volcanic ash', root: '古英语 æsce' },
  { word: 'ashamed', phonetic: '/əˈʃeɪmd/', pos: 'adj.', meaning: '羞愧的；惭愧的', eg: 'He felt ashamed of his mistake.', trans: '他为自己的错误感到羞愧。', coll: 'be ashamed; feel ashamed', root: '古英语 āscamian' },
  { word: 'aspect', phonetic: '/ˈæspekt/', pos: 'n.', meaning: '方面；面貌', eg: 'This is an important aspect.', trans: '这是一个重要方面。', coll: 'aspect of life; different aspects', root: '拉丁语 aspectus' },
  { word: 'assemble', phonetic: '/əˈsembəl/', pos: 'v.', meaning: '组装；集合', eg: 'We need to assemble the machine.', trans: '我们需要组装这台机器。', coll: 'assemble team; assemble parts', root: '拉丁语 assemblare' },
  { word: 'assembly', phonetic: '/əˈsembli/', pos: 'n.', meaning: '集合；大会', eg: 'The assembly will begin soon.', trans: '大会即将开始。', coll: 'assembly line; general assembly', root: 'assemble 的名词' },
  { word: 'assess', phonetic: '/əˈses/', pos: 'v.', meaning: '评估；评定', eg: 'We need to assess the situation.', trans: '我们需要评估情况。', coll: 'assess risk; assess value', root: '拉丁语 assessare' },
  { word: 'assessment', phonetic: '/əˈsesmənt/', pos: 'n.', meaning: '评估；评价', eg: 'The assessment was fair.', trans: '评估很公平。', coll: 'needs assessment; performance assessment', root: 'assess + -ment' },
  { word: 'asset', phonetic: '/ˈæset/', pos: 'n.', meaning: '资产；财产', eg: 'Time is a valuable asset.', trans: '时间是宝贵的资产。', coll: 'asset management; financial asset', root: '拉丁语 asset' },
  { word: 'assign', phonetic: '/əˈsaɪn/', pos: 'v.', meaning: '分配；指派', eg: 'The teacher assigned homework.', trans: '老师布置了作业。', coll: 'assign to; assign task', root: '拉丁语 assignare' },
  { word: 'assignment', phonetic: '/əˈsaɪnmənt/', pos: 'n.', meaning: '作业；任务', eg: 'I finished my assignment.', trans: '我完成了作业。', coll: 'assignment deadline; homework assignment', root: 'assign + -ment' },
  { word: 'assist', phonetic: '/əˈsɪst/', pos: 'v.', meaning: '协助；帮助', eg: 'Please assist me with this.', trans: '请帮我处理这个。', coll: 'assist with; assist someone', root: '拉丁语 assistere' },
  { word: 'assistance', phonetic: '/əˈsɪstəns/', pos: 'n.', meaning: '帮助；援助', eg: 'Thank you for your assistance.', trans: '谢谢你的帮助。', coll: 'financial assistance; need assistance', root: 'assist + -ance' },
  { word: 'assistant', phonetic: '/əˈsɪstənt/', pos: 'n./adj.', meaning: '助理；辅助的', eg: 'She is my personal assistant.', trans: '她是我的私人助理。', coll: 'teaching assistant; personal assistant', root: 'assist + -ant' },
  { word: 'associate', phonetic: '/əˈsoʊʃieɪt/', pos: 'v./n.', meaning: '联系；同事', eg: 'I associate him with success.', trans: '我把他和成功联系在一起。', coll: 'associate with; associate degree', root: '拉丁语 associatus' },
  { word: 'association', phonetic: '/əˌsoʊʃiˈeɪʃən/', pos: 'n.', meaning: '协会；联合', eg: 'He joined the association.', trans: '他加入了协会。', coll: 'trade association; association member', root: 'associate + -ation' },
  { word: 'assume', phonetic: '/əˈsuːm/', pos: 'v.', meaning: '假设；承担', eg: 'Let\'s assume he is right.', trans: '假设他是对的。', coll: 'assume responsibility; assume true', root: '拉丁语 assumere' },
  { word: 'assumption', phonetic: '/əˈsʌmpʃən/', pos: 'n.', meaning: '假设；假定', eg: 'This assumption may be wrong.', trans: '这个假设可能是错误的。', coll: 'under assumption; wrong assumption', root: 'assume + -ption' },
  { word: 'assure', phonetic: '/əˈʃʊr/', pos: 'v.', meaning: '保证；确保', eg: 'I assure you it\'s safe.', trans: '我向你保证这是安全的。', coll: 'assure someone; assure safety', root: '拉丁语 assicurare' },
  { word: 'astonish', phonetic: '/əˈstɑːnɪʃ/', pos: 'v.', meaning: '使惊讶；使吃惊', eg: 'The news astonished everyone.', trans: '这个消息让所有人都感到惊讶。', coll: 'be astonished; astonish someone', root: '拉丁语 astonire' },
  { word: 'at', phonetic: '/æt/', pos: 'prep.', meaning: '在；向', eg: 'Meet me at the station.', trans: '在车站见我。', coll: 'at school; at work', root: '古英语 æt' },
  { word: 'atmosphere', phonetic: '/ˈætməsfɪər/', pos: 'n.', meaning: '气氛；大气', eg: 'The atmosphere is very friendly.', trans: '气氛非常友好。', coll: 'atmosphere pressure; good atmosphere', root: '希腊语 atmos' },
  { word: 'atom', phonetic: '/ˈætəm/', pos: 'n.', meaning: '原子', eg: 'Everything is made of atoms.', trans: '一切都是由原子构成的。', coll: 'atomic bomb; atomic structure', root: '希腊语 atomos' },
  { word: 'attach', phonetic: '/əˈtætʃ/', pos: 'v.', meaning: '附加；附上', eg: 'Please attach the file.', trans: '请附上文件。', coll: 'attach to; attach file', root: '拉丁语 attaccare' },
  { word: 'attack', phonetic: '/əˈtæk/', pos: 'v./n.', meaning: '攻击；袭击', eg: 'The enemy attacked at dawn.', trans: '敌人在黎明时发动攻击。', coll: 'attack on; attack enemy', root: '拉丁语 attaccare' },
  { word: 'attain', phonetic: '/əˈteɪn/', pos: 'v.', meaning: '获得；达到', eg: 'She attained her goal.', trans: '她达到了目标。', coll: 'attain success; attain goal', root: '拉丁语 attingere' },
  { word: 'attempt', phonetic: '/əˈtempt/', pos: 'n./v.', meaning: '尝试；企图', eg: 'He made an attempt to escape.', trans: '他企图逃跑。', coll: 'attempt to; make attempt', root: '拉丁语 attemptare' },
  { word: 'attend', phonetic: '/əˈtend/', pos: 'v.', meaning: '参加；出席', eg: 'I will attend the meeting.', trans: '我将参加会议。', coll: 'attend meeting; attend school', root: '拉丁语 attendere' },
  { word: 'attention', phonetic: '/əˈtenʃən/', pos: 'n.', meaning: '注意；关注', eg: 'Please pay attention.', trans: '请注意。', coll: 'pay attention; draw attention', root: 'attend + -ion' },
  { word: 'attractive', phonetic: '/əˈtræktɪv/', pos: 'adj.', meaning: '有吸引力的；迷人的', eg: 'She is very attractive.', trans: '她非常迷人。', coll: 'attractive price; attractive offer', root: 'attract + -ive' },
  { word: 'attribute', phonetic: '/əˈtrɪbjuːt/', pos: 'n./v.', meaning: '属性；归因于', eg: 'Patience is a good attribute.', trans: '耐心是一个好品质。', coll: 'attribute to; key attribute', root: '拉丁语 attributum' },
  { word: 'audience', phonetic: '/ˈɔːdiəns/', pos: 'n.', meaning: '观众；听众', eg: 'The audience applauded loudly.', trans: '观众热烈鼓掌。', coll: 'target audience; large audience', root: '拉丁语 audientia' },
  { word: 'audio', phonetic: '/ˈɔːdiəʊ/', pos: 'n./adj.', meaning: '音频；声音的', eg: 'The audio quality is excellent.', trans: '音频质量非常好。', coll: 'audio quality; audio file', root: '拉丁语 audire' },
  { word: 'author', phonetic: '/ˈɔːθər/', pos: 'n.', meaning: '作者；作家', eg: 'He is a famous author.', trans: '他是一位著名的作家。', coll: 'best-selling author; famous author', root: '拉丁语 auctor' },
  { word: 'authority', phonetic: '/əˈθɔːrəti/', pos: 'n.', meaning: '权威；当局', eg: 'He speaks with authority.', trans: '他说话很有权威。', coll: 'authority figure; local authority', root: 'author + -ity' },
  { word: 'auto', phonetic: '/ˈɔːtoʊ/', pos: 'n./adj.', meaning: '汽车；自动的', eg: 'The auto industry is growing.', trans: '汽车工业正在发展。', coll: 'auto parts; auto industry', root: '希腊语 autos' },
  { word: 'automatic', phonetic: '/ˌɔːtəˈmætɪk/', pos: 'adj.', meaning: '自动的；机械的', eg: 'The door opens automatically.', trans: '门自动打开。', coll: 'automatic transmission; automatic door', root: 'auto + -matic' },
  { word: 'automobile', phonetic: '/ˈɔːtəməbiːl/', pos: 'n.', meaning: '汽车', eg: 'I bought a new automobile.', trans: '我买了一辆新车。', coll: 'automobile industry; new automobile', root: 'auto + mobile' },
  { word: 'autumn', phonetic: '/ˈɔːtəm/', pos: 'n.', meaning: '秋天；秋季', eg: 'Autumn is my favorite season.', trans: '秋天是我最喜欢的季节。', coll: 'autumn leaves; golden autumn', root: '拉丁语 autumnus' },
  { word: 'available', phonetic: '/əˈveɪləbl/', pos: 'adj.', meaning: '可用的；可获得的', eg: 'The tickets are available now.', trans: '票现在可以买到了。', coll: 'available time; available now', root: 'avail + -able' },
  { word: 'average', phonetic: '/ˈævərɪdʒ/', pos: 'n./adj.', meaning: '平均；平均的', eg: 'The average age is 30.', trans: '平均年龄是30岁。', coll: 'average cost; above average', root: '拉丁语 averagium' },
  { word: 'avoid', phonetic: '/əˈvɔɪd/', pos: 'v.', meaning: '避免；避开', eg: 'Try to avoid mistakes.', trans: '尽量避免错误。', coll: 'avoid doing; avoid mistakes', root: 'a- + void' },
  { word: 'await', phonetic: '/əˈweɪt/', pos: 'v.', meaning: '等待；期待', eg: 'We await your response.', trans: '我们等待你的回复。', coll: 'await decision; await response', root: 'a- + wait' },
  { word: 'awake', phonetic: '/əˈweɪk/', pos: 'adj./v.', meaning: '醒着的；唤醒', eg: 'I was awake all night.', trans: '我整晚都没睡。', coll: 'wide awake; stay awake', root: '古英语 āwæcnan' },
  { word: 'award', phonetic: '/əˈwɔːrd/', pos: 'n./v.', meaning: '奖项；授予', eg: 'She won an award for her work.', trans: '她因工作获得了奖项。', coll: 'award ceremony; win award', root: '古英语 award' },
  { word: 'aware', phonetic: '/əˈweər/', pos: 'adj.', meaning: '意识到的；知道的', eg: 'Are you aware of the danger?', trans: '你意识到危险了吗？', coll: 'aware of; be aware', root: '古英语 gewaer' },
  { word: 'awareness', phonetic: '/əˈweərnəs/', pos: 'n.', meaning: '意识；认识', eg: 'We need to raise awareness.', trans: '我们需要提高意识。', coll: 'environmental awareness; raise awareness', root: 'aware + -ness' },
  { word: 'away', phonetic: '/əˈweɪ/', pos: 'adv.', meaning: '离开；远离', eg: 'He walked away.', trans: '他走开了。', coll: 'far away; go away', root: '古英语 aweg' },
  { word: 'awful', phonetic: '/ˈɔːfl/', pos: 'adj.', meaning: '可怕的；糟糕的', eg: 'The weather is awful today.', trans: '今天天气很糟糕。', coll: 'awful lot; awful weather', root: 'awe + -ful' },
  { word: 'awkward', phonetic: '/ˈɔːkwərd/', pos: 'adj.', meaning: '尴尬的；笨拙的', eg: 'It was an awkward moment.', trans: '那是一个尴尬的时刻。', coll: 'awkward silence; awkward moment', root: '古英语 awke' },
  { word: 'baby', phonetic: '/ˈbeɪbi/', pos: 'n.', meaning: '婴儿；宝贝', eg: 'The baby is sleeping.', trans: '婴儿正在睡觉。', coll: 'baby boy; baby girl', root: '古英语 babe' },
  { word: 'back', phonetic: '/bæk/', pos: 'n./adv.', meaning: '背部；向后', eg: 'He sat at the back.', trans: '他坐在后面。', coll: 'back to; back up', root: '古英语 bæc' },
  { word: 'background', phonetic: '/ˈbækɡraʊnd/', pos: 'n.', meaning: '背景；后台', eg: 'Tell me about your background.', trans: '告诉我你的背景。', coll: 'background check; educational background', root: 'back + ground' },
  { word: 'bad', phonetic: '/bæd/', pos: 'adj.', meaning: '坏的；不好的', eg: 'This is a bad idea.', trans: '这是个坏主意。', coll: 'bad weather; bad news', root: '古英语 bād' },
  { word: 'bag', phonetic: '/bæɡ/', pos: 'n.', meaning: '包；袋子', eg: 'I carry a bag every day.', trans: '我每天都带着一个包。', coll: 'hand bag; school bag', root: '古英语 bagg' },
  { word: 'balance', phonetic: '/ˈbæləns/', pos: 'n./v.', meaning: '平衡；平衡', eg: 'Keep your balance.', trans: '保持平衡。', coll: 'balance sheet; balance of power', root: '拉丁语 bilans' },
  { word: 'ball', phonetic: '/bɔːl/', pos: 'n.', meaning: '球；球状物', eg: 'He kicked the ball.', trans: '他踢了球。', coll: 'football; basketball', root: '古英语 beall' },
  { word: 'bank', phonetic: '/bæŋk/', pos: 'n.', meaning: '银行；河岸', eg: 'I go to the bank every week.', trans: '我每周都去银行。', coll: 'bank account; river bank', root: '意大利语 banco' },
  { word: 'base', phonetic: '/beɪs/', pos: 'n./adj.', meaning: '基础；基本的', eg: 'This is the base of the building.', trans: '这是建筑的基础。', coll: 'base on; military base', root: '拉丁语 basis' },
  { word: 'basic', phonetic: '/ˈbeɪsɪk/', pos: 'adj.', meaning: '基本的；基础的', eg: 'These are basic skills.', trans: '这些是基本技能。', coll: 'basic needs; basic knowledge', root: 'base + -ic' },
  { word: 'basis', phonetic: '/ˈbeɪsɪs/', pos: 'n.', meaning: '基础；根据', eg: 'This is the basis of our argument.', trans: '这是我们论点的基础。', coll: 'on the basis of; common basis', root: '拉丁语 basis' },
  { word: 'basket', phonetic: '/ˈbæskɪt/', pos: 'n.', meaning: '篮子；筐', eg: 'She carried a basket of flowers.', trans: '她提着一篮花。', coll: 'basket ball; fruit basket', root: '古法语 basquette' },
  { word: 'bath', phonetic: '/bæθ/', pos: 'n./v.', meaning: '洗澡；沐浴', eg: 'I take a bath every day.', trans: '我每天都洗澡。', coll: 'take a bath; bath tub', root: '古英语 bæð' },
  { word: 'battle', phonetic: '/ˈbætl/', pos: 'n./v.', meaning: '战斗；斗争', eg: 'The battle lasted for hours.', trans: '战斗持续了几个小时。', coll: 'battle field; battle against', root: '古法语 bataille' },
  { word: 'be', phonetic: '/biː/', pos: 'v.', meaning: '是；成为', eg: 'I am a student.', trans: '我是一名学生。', coll: 'be happy; be able to', root: '古英语 bēon' },
  { word: 'bear', phonetic: '/beər/', pos: 'n./v.', meaning: '熊；忍受', eg: 'I can\'t bear the pain.', trans: '我无法忍受痛苦。', coll: 'bear with; bear fruit', root: '古英语 bera' },
  { word: 'beautiful', phonetic: '/ˈbjuːtɪfl/', pos: 'adj.', meaning: '美丽的；漂亮的', eg: 'She is very beautiful.', trans: '她非常漂亮。', coll: 'beautiful scenery; beautiful girl', root: 'beauty + -ful' },
  { word: 'beauty', phonetic: '/ˈbjuːti/', pos: 'n.', meaning: '美丽；美人', eg: 'Beauty is in the eye of the beholder.', trans: '情人眼里出西施。', coll: 'natural beauty; inner beauty', root: '拉丁语 bellus' },
  { word: 'because', phonetic: '/bɪˈkɔːz/', pos: 'conj.', meaning: '因为', eg: 'I stayed home because it rained.', trans: '因为下雨我待在家里。', coll: 'because of; just because', root: '古英语 becosan' },
  { word: 'become', phonetic: '/bɪˈkʌm/', pos: 'v.', meaning: '成为；变成', eg: 'She became a doctor.', trans: '她成为了一名医生。', coll: 'become famous; become rich', root: '古英语 becuman' },
  { word: 'bed', phonetic: '/bed/', pos: 'n.', meaning: '床；床位', eg: 'I go to bed at 11 pm.', trans: '我晚上11点睡觉。', coll: 'bed room; go to bed', root: '古英语 bedd' },
  { word: 'before', phonetic: '/bɪˈfɔːr/', pos: 'prep./adv.', meaning: '在...之前；以前', eg: 'I met her before.', trans: '我以前见过她。', coll: 'before long; long before', root: '古英语 beforan' },
  { word: 'begin', phonetic: '/bɪˈɡɪn/', pos: 'v.', meaning: '开始；着手', eg: 'Let\'s begin the meeting.', trans: '让我们开始会议。', coll: 'begin with; begin to', root: '古英语 beginnan' },
  { word: 'beginning', phonetic: '/bɪˈɡɪnɪŋ/', pos: 'n.', meaning: '开始；开端', eg: 'This is the beginning of a new era.', trans: '这是一个新时代的开始。', coll: 'at the beginning; from the beginning', root: 'begin + -ning' },
  { word: 'behavior', phonetic: '/bɪˈheɪvjər/', pos: 'n.', meaning: '行为；举止', eg: 'His behavior was unacceptable.', trans: '他的行为是不可接受的。', coll: 'good behavior; social behavior', root: 'behave 的名词' },
  { word: 'behind', phonetic: '/bɪˈhaɪnd/', pos: 'prep./adv.', meaning: '在...后面；落后', eg: 'Stay behind me.', trans: '跟在我后面。', coll: 'fall behind; behind the scenes', root: