const fs = require('fs');

// 生成单词数据
function generateWords(startId, count) {
  const words = [];
  const wordList = [
    { word: 'abandon', phonetic: '/əˈbændən/', pos: 'v.', meaning: '放弃；遗弃', eg: 'He abandoned his plan.', trans: '他放弃了他的计划。', coll: 'abandon plan', root: 'aban- + -don' },
    { word: 'ability', phonetic: '/əˈbɪləti/', pos: 'n.', meaning: '能力', eg: 'She has ability.', trans: '她有能力。', coll: 'ability to', root: 'able + -ity' },
    { word: 'able', phonetic: '/ˈeɪbl/', pos: 'adj.', meaning: '能够的', eg: 'I am able.', trans: '我能够。', coll: 'be able to', root: '拉丁语 habilis' },
    { word: 'about', phonetic: '/əˈbaʊt/', pos: 'prep.', meaning: '关于', eg: 'Talk about it.', trans: '谈谈这件事。', coll: 'talk about', root: '古英语 butan' },
    { word: 'above', phonetic: '/əˈbʌv/', pos: 'prep.', meaning: '在...上', eg: 'Above the table.', trans: '在桌子上方。', coll: 'above all', root: '古英语 abufan' },
    { word: 'abroad', phonetic: '/əˈbrɔːd/', pos: 'adv.', meaning: '在国外', eg: 'Study abroad.', trans: '出国留学。', coll: 'go abroad', root: 'a- + broad' },
    { word: 'absence', phonetic: '/ˈæbsəns/', pos: 'n.', meaning: '缺席', eg: 'His absence.', trans: '他的缺席。', coll: 'in absence', root: 'abs- + -ence' },
    { word: 'absent', phonetic: '/ˈæbsənt/', pos: 'adj.', meaning: '缺席的', eg: 'He is absent.', trans: '他缺席了。', coll: 'be absent', root: 'abs- + -ent' },
    { word: 'absolute', phonetic: '/ˈæbsəluːt/', pos: 'adj.', meaning: '绝对的', eg: 'Absolute truth.', trans: '绝对真理。', coll: 'absolute value', root: 'abs- + solut-' },
    { word: 'absorb', phonetic: '/əbˈsɔːb/', pos: 'v.', meaning: '吸收', eg: 'Plants absorb.', trans: '植物吸收。', coll: 'absorb water', root: 'abs- + sorb' },
    { word: 'abstract', phonetic: '/ˈæbstrækt/', pos: 'adj.', meaning: '抽象的', eg: 'Abstract art.', trans: '抽象艺术。', coll: 'abstract concept', root: 'abs- + tract' },
    { word: 'academic', phonetic: '/ˌækəˈdemɪk/', pos: 'adj.', meaning: '学术的', eg: 'Academic research.', trans: '学术研究。', coll: 'academic degree', root: 'academy + -ic' },
    { word: 'accept', phonetic: '/əkˈsept/', pos: 'v.', meaning: '接受', eg: 'Accept the gift.', trans: '接受礼物。', coll: 'accept invitation', root: 'ac- + cept' },
    { word: 'access', phonetic: '/ˈækses/', pos: 'n.', meaning: '通道', eg: 'Access to info.', trans: '获取信息。', coll: 'have access', root: 'ac- + cess' },
    { word: 'accident', phonetic: '/ˈæksɪdənt/', pos: 'n.', meaning: '事故', eg: 'Car accident.', trans: '车祸。', coll: 'by accident', root: 'accid- + -ent' },
    { word: 'accompany', phonetic: '/əˈkʌmpəni/', pos: 'v.', meaning: '陪伴', eg: 'Accompany me.', trans: '陪我。', coll: 'accompany someone', root: 'ac- + company' },
    { word: 'accomplish', phonetic: '/əˈkʌmplɪʃ/', pos: 'v.', meaning: '完成', eg: 'Accomplish goal.', trans: '完成目标。', coll: 'accomplish task', root: 'ac- + complish' },
    { word: 'according', phonetic: '/əˈkɔːrdɪŋ/', pos: 'prep.', meaning: '根据', eg: 'According to.', trans: '根据。', coll: 'according to', root: 'accord + -ing' },
    { word: 'account', phonetic: '/əˈkaʊnt/', pos: 'n.', meaning: '账户', eg: 'Bank account.', trans: '银行账户。', coll: 'bank account', root: 'ac- + count' },
    { word: 'accurate', phonetic: '/ˈækjərət/', pos: 'adj.', meaning: '准确的', eg: 'Accurate data.', trans: '准确数据。', coll: 'accurate measurement', root: 'accur- + -ate' },
    { word: 'achieve', phonetic: '/əˈtʃiːv/', pos: 'v.', meaning: '实现', eg: 'Achieve success.', trans: '取得成功。', coll: 'achieve goal', root: 'a- + chieve' },
    { word: 'acquire', phonetic: '/əˈkwaɪər/', pos: 'v.', meaning: '获得', eg: 'Acquire skill.', trans: '获得技能。', coll: 'acquire knowledge', root: 'ac- + quire' },
    { word: 'across', phonetic: '/əˈkrɔːs/', pos: 'prep.', meaning: '穿过', eg: 'Walk across.', trans: '穿过。', coll: 'come across', root: 'a- + cross' },
    { word: 'action', phonetic: '/ˈækʃən/', pos: 'n.', meaning: '行动', eg: 'Take action.', trans: '采取行动。', coll: 'take action', root: 'act + -ion' },
    { word: 'active', phonetic: '/ˈæktɪv/', pos: 'adj.', meaning: '积极的', eg: 'Active member.', trans: '积极成员。', coll: 'active participation', root: 'act + -ive' },
    { word: 'activity', phonetic: '/ækˈtɪvəti/', pos: 'n.', meaning: '活动', eg: 'Social activity.', trans: '社交活动。', coll: 'physical activity', root: 'active + -ity' },
    { word: 'actual', phonetic: '/ˈæktʃuəl/', pos: 'adj.', meaning: '实际的', eg: 'Actual cost.', trans: '实际成本。', coll: 'in actual fact', root: 'act + -ual' },
    { word: 'adapt', phonetic: '/əˈdæpt/', pos: 'v.', meaning: '适应', eg: 'Adapt to change.', trans: '适应变化。', coll: 'adapt to', root: 'ad- + apt' },
    { word: 'add', phonetic: '/æd/', pos: 'v.', meaning: '添加', eg: 'Add sugar.', trans: '加糖。', coll: 'add up', root: '拉丁语 addere' },
    { word: 'addition', phonetic: '/əˈdɪʃən/', pos: 'n.', meaning: '加法', eg: 'Math addition.', trans: '数学加法。', coll: 'in addition', root: 'add + -ition' },
    { word: 'additional', phonetic: '/əˈdɪʃənl/', pos: 'adj.', meaning: '额外的', eg: 'Additional info.', trans: '额外信息。', coll: 'additional cost', root: 'addition + -al' },
    { word: 'address', phonetic: '/əˈdres/', pos: 'n.', meaning: '地址', eg: 'Home address.', trans: '家庭地址。', coll: 'email address', root: 'ad- + dress' },
    { word: 'adequate', phonetic: '/ˈædɪkwət/', pos: 'adj.', meaning: '足够的', eg: 'Adequate time.', trans: '足够时间。', coll: 'adequate supply', root: 'ad- + equate' },
    { word: 'adjust', phonetic: '/əˈdʒʌst/', pos: 'v.', meaning: '调整', eg: 'Adjust settings.', trans: '调整设置。', coll: 'adjust to', root: 'ad- + just' },
    { word: 'administration', phonetic: '/ədˌmɪnɪˈstreɪʃən/', pos: 'n.', meaning: '管理', eg: 'Business admin.', trans: '企业管理。', coll: 'public admin', root: 'administr- + -ation' },
    { word: 'admire', phonetic: '/ədˈmaɪər/', pos: 'v.', meaning: '钦佩', eg: 'Admire courage.', trans: '钦佩勇气。', coll: 'admire someone', root: 'ad- + mir' },
    { word: 'admit', phonetic: '/ədˈmɪt/', pos: 'v.', meaning: '承认', eg: 'Admit mistake.', trans: '承认错误。', coll: 'admit to', root: 'ad- + mit' },
    { word: 'adopt', phonetic: '/əˈdɒpt/', pos: 'v.', meaning: '采纳', eg: 'Adopt policy.', trans: '采纳政策。', coll: 'adopt child', root: 'ad- + opt' },
    { word: 'advance', phonetic: '/ədˈvɑːns/', pos: 'v.', meaning: '前进', eg: 'Advance forward.', trans: '向前推进。', coll: 'in advance', root: 'ad- + vance' },
    { word: 'advantage', phonetic: '/ədˈvɑːntɪdʒ/', pos: 'n.', meaning: '优势', eg: 'Competitive edge.', trans: '竞争优势。', coll: 'take advantage', root: 'advance + -age' },
    { word: 'adventure', phonetic: '/ədˈventʃər/', pos: 'n.', meaning: '冒险', eg: 'Go on adventure.', trans: '去冒险。', coll: 'adventure story', root: 'ad- + venture' },
    { word: 'advertise', phonetic: '/ˈædvətaɪz/', pos: 'v.', meaning: '广告', eg: 'Advertise product.', trans: '为产品做广告。', coll: 'advertise online', root: 'ad- + vert + -ise' },
    { word: 'advice', phonetic: '/ədˈvaɪs/', pos: 'n.', meaning: '建议', eg: 'Give advice.', trans: '给建议。', coll: 'take advice', root: 'advise 的名词' },
    { word: 'advise', phonetic: '/ədˈvaɪz/', pos: 'v.', meaning: '建议', eg: 'Advise caution.', trans: '建议谨慎。', coll: 'advise against', root: 'ad- + vise' },
    { word: 'affair', phonetic: '/əˈfeər/', pos: 'n.', meaning: '事务', eg: 'Personal affair.', trans: '个人事务。', coll: 'state affairs', root: 'af- + fair' },
    { word: 'affect', phonetic: '/əˈfekt/', pos: 'v.', meaning: '影响', eg: 'Affect mood.', trans: '影响心情。', coll: 'be affected', root: 'af- + fect' },
    { word: 'afford', phonetic: '/əˈfɔːrd/', pos: 'v.', meaning: '负担', eg: 'Afford house.', trans: '负担房子。', coll: 'can afford', root: 'af- + ford' },
    { word: 'afraid', phonetic: '/əˈfreɪd/', pos: 'adj.', meaning: '害怕的', eg: 'Afraid of dark.', trans: '害怕黑暗。', coll: 'be afraid', root: '古英语 āfǣr' },
    { word: 'after', phonetic: '/ˈɑːftər/', pos: 'prep.', meaning: '在...后', eg: 'After school.', trans: '放学后。', coll: 'after all', root: '古英语 æfter' },
    { word: 'afternoon', phonetic: '/ˌɑːftərˈnuːn/', pos: 'n.', meaning: '下午', eg: 'Good afternoon.', trans: '下午好。', coll: 'in afternoon', root: 'after + noon' },
    { word: 'again', phonetic: '/əˈɡen/', pos: 'adv.', meaning: '再次', eg: 'Try again.', trans: '再试一次。', coll: 'again and again', root: '古英语 ongean' },
    { word: 'against', phonetic: '/əˈɡeɪnst/', pos: 'prep.', meaning: '反对', eg: 'Against war.', trans: '反对战争。', coll: 'go against', root: '古英语 ongean' },
    { word: 'age', phonetic: '/eɪdʒ/', pos: 'n.', meaning: '年龄', eg: 'What age?', trans: '几岁？', coll: 'at age', root: '拉丁语 aetas' },
    { word: 'agency', phonetic: '/ˈeɪdʒənsi/', pos: 'n.', meaning: '机构', eg: 'Travel agency.', trans: '旅行社。', coll: 'advertising agency', root: 'agent + -cy' },
    { word: 'agent', phonetic: '/ˈeɪdʒənt/', pos: 'n.', meaning: '代理人', eg: 'Real estate agent.', trans: '房地产经纪人。', coll: 'secret agent', root: 'ag- + -ent' },
    { word: 'aggressive', phonetic: '/əˈɡresɪv/', pos: 'adj.', meaning: '侵略的', eg: 'Aggressive behavior.', trans: '侵略行为。', coll: 'aggressive market', root: 'aggress + -ive' },
    { word: 'ago', phonetic: '/əˈɡoʊ/', pos: 'adv.', meaning: '以前', eg: 'Years ago.', trans: '多年前。', coll: 'long ago', root: '古英语 āgān' },
    { word: 'agree', phonetic: '/əˈɡriː/', pos: 'v.', meaning: '同意', eg: 'Agree with you.', trans: '同意你。', coll: 'agree on', root: 'a- + gree' },
    { word: 'agreement', phonetic: '/əˈɡriːmənt/', pos: 'n.', meaning: '协议', eg: 'Sign agreement.', trans: '签署协议。', coll: 'reach agreement', root: 'agree + -ment' },
    { word: 'agriculture', phonetic: '/ˈæɡrɪkʌltʃər/', pos: 'n.', meaning: '农业', eg: 'Modern agriculture.', trans: '现代农业。', coll: 'agricultural products', root: 'agri- + culture' },
    { word: 'ahead', phonetic: '/əˈhed/', pos: 'adv.', meaning: '向前', eg: 'Go ahead.', trans: '前进。', coll: 'ahead of', root: 'a- + head' },
    { word: 'aid', phonetic: '/eɪd/', pos: 'n.', meaning: '援助', eg: 'First aid.', trans: '急救。', coll: 'foreign aid', root: '拉丁语 adjuvare' },
    { word: 'aim', phonetic: '/eɪm/', pos: 'v.', meaning: '瞄准', eg: 'Aim at target.', trans: '瞄准目标。', coll: 'aim for', root: '古法语 aesmer' },
    { word: 'air', phonetic: '/eər/', pos: 'n.', meaning: '空气', eg: 'Fresh air.', trans: '新鲜空气。', coll: 'by air', root: '拉丁语 aer' },
    { word: 'airport', phonetic: '/ˈeərpɔːrt/', pos: 'n.', meaning: '机场', eg: 'International airport.', trans: '国际机场。', coll: 'airport terminal', root: 'air + port' },
    { word: 'alarm', phonetic: '/əˈlɑːrm/', pos: 'n.', meaning: '警报', eg: 'Fire alarm.', trans: '火警。', coll: 'alarm clock', root: '意大利语 allarme' },
    { word: 'album', phonetic: '/ˈælbəm/', pos: 'n.', meaning: '相册', eg: 'Photo album.', trans: '相册。', coll: 'music album', root: '拉丁语 album' },
    { word: 'alcohol', phonetic: '/ˈælkəhɔːl/', pos: 'n.', meaning: '酒精', eg: 'Alcohol free.', trans: '无酒精。', coll: 'alcohol content', root: '阿拉伯语 al-kuhl' },
    { word: 'alike', phonetic: '/əˈlaɪk/', pos: 'adj.', meaning: '相似的', eg: 'Look alike.', trans: '看起来像。', coll: 'think alike', root: 'a- + like' },
    { word: 'alive', phonetic: '/əˈlaɪv/', pos: 'adj.', meaning: '活着的', eg: 'Stay alive.', trans: '活着。', coll: 'come alive', root: 'a- + live' },
    { word: 'all', phonetic: '/ɔːl/', pos: 'adj.', meaning: '所有的', eg: 'All people.', trans: '所有人。', coll: 'all over', root: '古英语 eall' },
    { word: 'allow', phonetic: '/əˈlaʊ/', pos: 'v.', meaning: '允许', eg: 'Allow entry.', trans: '允许进入。', coll: 'allow for', root: '古英语 ālǣwan' },
    { word: 'almost', phonetic: '/ˈɔːlmoʊst/', pos: 'adv.', meaning: '几乎', eg: 'Almost done.', trans: '快完成了。', coll: 'almost all', root: 'all + most' },
    { word: 'alone', phonetic: '/əˈloʊn/', pos: 'adj.', meaning: '单独的', eg: 'Live alone.', trans: '独自生活。', coll: 'leave alone', root: 'a- + lone' },
    { word: 'along', phonetic: '/əˈlɔːŋ/', pos: 'prep.', meaning: '沿着', eg: 'Walk along.', trans: '沿着走。', coll: 'along with', root: '古英语 andlang' },
    { word: 'aloud', phonetic: '/əˈlaʊd/', pos: 'adv.', meaning: '大声地', eg: 'Read aloud.', trans: '大声朗读。', coll: 'think aloud', root: 'a- + loud' },
    { word: 'alphabet', phonetic: '/ˈælfəbet/', pos: 'n.', meaning: '字母表', eg: 'Learn alphabet.', trans: '学习字母表。', coll: 'English alphabet', root: '希腊语 alpha+beta' },
    { word: 'already', phonetic: '/ɔːlˈredi/', pos: 'adv.', meaning: '已经', eg: 'Already done.', trans: '已经完成。', coll: 'already know', root: 'all + ready' },
    { word: 'also', phonetic: '/ˈɔːlsoʊ/', pos: 'adv.', meaning: '也', eg: 'Also good.', trans: '也很好。', coll: 'not only but also', root: 'all + so' },
    { word: 'alter', phonetic: '/ˈɔːltər/', pos: 'v.', meaning: '改变', eg: 'Alter plans.', trans: '改变计划。', coll: 'alter course', root: '拉丁语 alter' },
    { word: 'alternative', phonetic: '/ɔːlˈtɜːrnətɪv/', pos: 'adj.', meaning: '替代的', eg: 'Alternative option.', trans: '替代方案。', coll: 'have alternative', root: 'alter + -native' },
    { word: 'although', phonetic: '/ɔːlˈðoʊ/', pos: 'conj.', meaning: '虽然', eg: 'Although tired.', trans: '虽然累。', coll: 'although yet', root: 'all + though' },
    { word: 'always', phonetic: '/ˈɔːlweɪz/', pos: 'adv.', meaning: '总是', eg: 'Always on time.', trans: '总是准时。', coll: 'always remember', root: 'all + ways' },
    { word: 'amaze', phonetic: '/əˈmeɪz/', pos: 'v.', meaning: '使惊讶', eg: 'Amaze everyone.', trans: '让所有人惊讶。', coll: 'be amazed', root: 'a- + maze' },
    { word: 'ambition', phonetic: '/æmˈbɪʃən/', pos: 'n.', meaning: '野心', eg: 'Great ambition.', trans: '伟大抱负。', coll: 'political ambition', root: 'amb- + -ition' },
    { word: 'ambitious', phonetic: '/æmˈbɪʃəs/', pos: 'adj.', meaning: '有野心的', eg: 'Ambitious plan.', trans: '雄心勃勃的计划。', coll: 'ambitious goal', root: 'ambition + -ous' },
    { word: 'amount', phonetic: '/əˈmaʊnt/', pos: 'n.', meaning: '数量', eg: 'Large amount.', trans: '大量。', coll: 'amount to', root: 'a- + mount' },
    { word: 'analysis', phonetic: '/əˈnæləsɪs/', pos: 'n.', meaning: '分析', eg: 'Data analysis.', trans: '数据分析。', coll: 'market analysis', root: 'ana- + lysis' },
    { word: 'analyze', phonetic: '/ˈænəlaɪz/', pos: 'v.', meaning: '分析', eg: 'Analyze data.', trans: '分析数据。', coll: 'analyze results', root: 'analysis 的动词' },
    { word: 'ancestor', phonetic: '/ˈænsestər/', pos: 'n.', meaning: '祖先', eg: 'Our ancestors.', trans: '我们的祖先。', coll: 'common ancestor', root: 'ante- + cest-' },
    { word: 'ancient', phonetic: '/ˈeɪnʃənt/', pos: 'adj.', meaning: '古代的', eg: 'Ancient city.', trans: '古城。', coll: 'ancient history', root: '拉丁语 antiquus' },
    { word: 'and', phonetic: '/ænd/', pos: 'conj.', meaning: '和', eg: 'You and me.', trans: '你和我。', coll: 'and so on', root: '古英语 and' },
    { word: 'anger', phonetic: '/ˈæŋɡər/', pos: 'n.', meaning: '愤怒', eg: 'Show anger.', trans: '表现愤怒。', coll: 'in anger', root: '古英语 angr' },
    { word: 'angle', phonetic: '/ˈæŋɡl/', pos: 'n.', meaning: '角度', eg: 'Right angle.', trans: '直角。', coll: 'at angle', root: '拉丁语 angulus' },
    { word: 'angry', phonetic: '/ˈæŋɡri/', pos: 'adj.', meaning: '生气的', eg: 'Get angry.', trans: '生气。', coll: 'be angry', root: 'anger + -y' },
    { word: 'animal', phonetic: '/ˈænɪməl/', pos: 'n.', meaning: '动物', eg: 'Wild animal.', trans: '野生动物。', coll: 'animal rights', root: '拉丁语 animalis' },
    { word: 'announce', phonetic: '/əˈnaʊns/', pos: 'v.', meaning: '宣布', eg: 'Announce news.', trans: '宣布消息。', coll: 'announce publicly', root: 'an- + nounce' },
    { word: 'announcement', phonetic: '/əˈnaʊnsmənt/', pos: 'n.', meaning: '公告', eg: 'Official announcement.', trans: '官方公告。', coll: 'make announcement', root: 'announce + -ment' },
    { word: 'annoy', phonetic: '/əˈnɔɪ/', pos: 'v.', meaning: '使烦恼', eg: 'Annoy me.', trans: '烦我。', coll: 'be annoyed', root: '古法语 anoier' },
    { word: 'annual', phonetic: '/ˈænjuəl/', pos: 'adj.', meaning: '每年的', eg: 'Annual report.', trans: '年度报告。', coll: 'annual event', root: '拉丁语 annus' },
    { word: 'another', phonetic: '/əˈnʌðər/', pos: 'adj.', meaning: '另一个', eg: 'Another chance.', trans: '另一个机会。', coll: 'one another', root: 'an- + other' },
    { word: 'answer', phonetic: '/ˈɑːnsər/', pos: 'n.', meaning: '回答', eg: 'Answer question.', trans: '回答问题。', coll: 'answer phone', root: '古英语 andswaru' },
    { word: 'anxiety', phonetic: '/æŋˈzaɪəti/', pos: 'n.', meaning: '焦虑', eg: 'Feel anxiety.', trans: '感到焦虑。', coll: 'anxiety disorder', root: '拉丁语 anxietas' },
    { word: 'anxious', phonetic: '/ˈæŋkʃəs/', pos: 'adj.', meaning: '焦虑的', eg: 'Anxious wait.', trans: '焦急等待。', coll: 'anxious to', root: 'anxiety + -ous' },
    { word: 'any', phonetic: '/ˈeni/', pos: 'adj.', meaning: '任何', eg: 'Any question?', trans: '有问题吗？', coll: 'any time', root: '古英语 ænig' },
    { word: 'anybody', phonetic: '/ˈenibʌdi/', pos: 'pron.', meaning: '任何人', eg: 'Anybody home?', trans: '有人在家吗？', coll: 'anybody else', root: 'any + body' },
    { word: 'anyone', phonetic: '/ˈeniwʌn/', pos: 'pron.', meaning: '任何人', eg: 'Anyone can join.', trans: '任何人都可以加入。', coll: 'anyone else', root: 'any + one' },
    { word: 'anything', phonetic: '/ˈeniθɪŋ/', pos: 'pron.', meaning: '任何事', eg: 'Anything else?', trans: '还有别的吗？', coll: 'anything but', root: 'any + thing' },
    { word: 'anyway', phonetic: '/ˈeniweɪ/', pos: 'adv.', meaning: '无论如何', eg: 'Anyway, start.', trans: '无论如何，开始吧。', coll: 'anyway look', root: 'any + way' },
    { word: 'anywhere', phonetic: '/ˈeniwer/', pos: 'adv.', meaning: '任何地方', eg: 'Go anywhere.', trans: '去任何地方。', coll: 'anywhere else', root: 'any + where' },
    { word: 'apart', phonetic: '/əˈpɑːrt/', pos: 'adv.', meaning: '分开', eg: 'Pull apart.', trans: '拉开。', coll: 'apart from', root: 'a- + part' },
    { word: 'apartment', phonetic: '/əˈpɑːrtmənt/', pos: 'n.', meaning: '公寓', eg: 'Rent apartment.', trans: '租公寓。', coll: 'apartment building', root: 'apart + -ment' },
    { word: 'apologize', phonetic: '/əˈpɒlədʒaɪz/', pos: 'v.', meaning: '道歉', eg: 'Apologize for.', trans: '为...道歉。', coll: 'apologize to', root: '希腊语 apologos' },
    { word: 'apology', phonetic: '/əˈpɒlədʒi/', pos: 'n.', meaning: '道歉', eg: 'Sincere apology.', trans: '真诚道歉。', coll: 'make apology', root: 'apologize 的名词' },
    { word: 'apparent', phonetic: '/əˈpærənt/', pos: 'adj.', meaning: '明显的', eg: 'Apparent mistake.', trans: '明显的错误。', coll: 'apparent reason', root: '拉丁语 apparens' },
    { word: 'apparently', phonetic: '/əˈpærəntli/', pos: 'adv.', meaning: '显然', eg: 'Apparently true.', trans: '显然是真的。', coll: 'apparently not', root: 'apparent + -ly' },
    { word: 'appeal', phonetic: '/əˈpiːl/', pos: 'n.', meaning: '呼吁', eg: 'Make appeal.', trans: '呼吁。', coll: 'appeal to', root: '拉丁语 appellare' },
    { word: 'appear', phonetic: '/əˈpɪər/', pos: 'v.', meaning: '出现', eg: 'Appear today.', trans: '今天出现。', coll: 'appear to be', root: '拉丁语 apparere' },
    { word: 'appearance', phonetic: '/əˈpɪərəns/', pos: 'n.', meaning: '外貌', eg: 'Good appearance.', trans: '良好外貌。', coll: 'make appearance', root: 'appear + -ance' },
    { word: 'application', phonetic: '/ˌæplɪˈkeɪʃən/', pos: 'n.', meaning: '应用', eg: 'Job application.', trans: '工作申请。', coll: 'application form', root: 'apply + -ation' },
    { word: 'apply', phonetic: '/əˈplaɪ/', pos: 'v.', meaning: '申请', eg: 'Apply for job.', trans: '申请工作。', coll: 'apply to', root: '拉丁语 applicare' },
    { word: 'appoint', phonetic: '/əˈpɔɪnt/', pos: 'v.', meaning: '任命', eg: 'Appoint manager.', trans: '任命经理。', coll: 'appoint as', root: '古法语 apointer' },
    { word: 'appointment', phonetic: '/əˈpɔɪntmənt/', pos: 'n.', meaning: '约会', eg: 'Make appointment.', trans: '预约。', coll: 'keep appointment', root: 'appoint + -ment' },
    { word: 'appreciate', phonetic: '/əˈpriːʃieɪt/', pos: 'v.', meaning: '欣赏', eg: 'Appreciate art.', trans: '欣赏艺术。', coll: 'appreciate help', root: '拉丁语 appretiatus' },
    { word: 'approach', phonetic: '/əˈproʊtʃ/', pos: 'n.', meaning: '方法', eg: 'New approach.', trans: '新方法。', coll: 'approach to', root: '拉丁语 appropiare' },
    { word: 'appropriate', phonetic: '/əˈproʊpriət/', pos: 'adj.', meaning: '适当的', eg: 'Appropriate action.', trans: '适当行动。', coll: 'appropriate for', root: '拉丁语 appropriatus' },
    { word: 'approval', phonetic: '/əˈpruːvl/', pos: 'n.', meaning: '批准', eg: 'Get approval.', trans: '获得批准。', coll: 'give approval', root: 'approve 的名词' },
    { word: 'approve', phonetic: '/əˈpruːv/', pos: 'v.', meaning: '批准', eg: 'Approve plan.', trans: '批准计划。', coll: 'approve of', root: '拉丁语 approbare' },
    { word: 'approximately', phonetic: '/əˈprɒksɪmətli/', pos: 'adv.', meaning: '大约', eg: 'Approx 100.', trans: '大约100。', coll: 'approximately equal', root: '拉丁语 approximatus' },
    { word: 'arbitrary', phonetic: '/ˈɑːrbɪtreri/', pos: 'adj.', meaning: '任意的', eg: 'Arbitrary choice.', trans: '任意选择。', coll: 'arbitrary rule', root: '拉丁语 arbitrarius' },
    { word: 'arch', phonetic: '/ɑːrtʃ/', pos: 'n.', meaning: '拱门', eg: 'Stone arch.', trans: '石拱门。', coll: 'arch bridge', root: '拉丁语 arcus' },
    { word: 'architect', phonetic: '/ˈɑːrkɪtekt/', pos: 'n.', meaning: '建筑师', eg: 'Famous architect.', trans: '著名建筑师。', coll: 'chief architect', root: '希腊语 architekton' },
    { word: 'architecture', phonetic: '/ˈɑːrkɪtektʃər/', pos: 'n.', meaning: '建筑', eg: 'Modern architecture.', trans: '现代建筑。', coll: 'classical architecture', root: 'architect + -ure' },
    { word: 'area', phonetic: '/ˈeriə/', pos: 'n.', meaning: '区域', eg: 'Urban area.', trans: '城市区域。', coll: 'rural area', root: '拉丁语 area' },
    { word: 'argue', phonetic: '/ˈɑːrɡjuː/', pos: 'v.', meaning: '争论', eg: 'Argue about.', trans: '争论。', coll: 'argue with', root: '拉丁语 arguere' },
    { word: 'argument', phonetic: '/ˈɑːrɡjumənt/', pos: 'n.', meaning: '论点', eg: 'Strong argument.', trans: '有力论点。', coll: 'against argument', root: 'argue + -ment' },
    { word: 'arise', phonetic: '/əˈraɪz/', pos: 'v.', meaning: '出现', eg: 'Problems arise.', trans: '出现问题。', coll: 'arise from', root: '古英语 arisan' },
    { word: 'arithmetic', phonetic: '/əˈrɪθmətɪk/', pos: 'n.', meaning: '算术', eg: 'Mental arithmetic.', trans: '心算。', coll: 'arithmetic operation', root: '希腊语 arithmos' },
    { word: 'arm', phonetic: '/ɑːrm/', pos: 'n.', meaning: '手臂', eg: 'Raise arm.', trans: '举起手臂。', coll: 'arm in arm', root: '古英语 earm' },
    { word: 'army', phonetic: '/ˈɑːrmi/', pos: 'n.', meaning: '军队', eg: 'Join army.', trans: '参军。', coll: 'army officer', root: '拉丁语 arma' },
    { word: 'around', phonetic: '/əˈraʊnd/', pos: 'prep.', meaning: '围绕', eg: 'Around house.', trans: '房子周围。', coll: 'around corner', root: '古英语 andround' },
    { word: 'arrange', phonetic: '/əˈreɪndʒ/', pos: 'v.', meaning: '安排', eg: 'Arrange meeting.', trans: '安排会议。', coll: 'arrange for', root: '古法语 arranger' },
    { word: 'arrangement', phonetic: '/əˈreɪndʒmənt/', pos: 'n.', meaning: '安排', eg: 'Perfect arrangement.', trans: '完美安排。', coll: 'seating arrangement', root: 'arrange + -ment' },
    { word: 'arrest', phonetic: '/əˈrest/', pos: 'v.', meaning: '逮捕', eg: 'Arrest suspect.', trans: '逮捕嫌疑犯。', coll: 'under arrest', root: '拉丁语 arrestare' },
    { word: 'arrival', phonetic: '/əˈraɪvl/', pos: 'n.', meaning: '到达', eg: 'Late arrival.', trans: '迟到。', coll: 'on arrival', root: 'arrive 的名词' },
    { word: 'arrive', phonetic: '/əˈraɪv/', pos: 'v.', meaning: '到达', eg: 'Arrive home.', trans: '到家。', coll: 'arrive at', root: '拉丁语 arrivare' },
    { word: 'arrow', phonetic: '/ˈæroʊ/', pos: 'n.', meaning: '箭头', eg: 'Arrow sign.', trans: '箭头标志。', coll: 'arrowhead', root: '古英语 arwe' },
    { word: 'art', phonetic: '/ɑːrt/', pos: 'n.', meaning: '艺术', eg: 'Modern art.', trans: '现代艺术。', coll: 'art gallery', root: '拉丁语 ars' },
    { word: 'article', phonetic: '/ˈɑːrtɪkl/', pos: 'n.', meaning: '文章', eg: 'News article.', trans: '新闻文章。', coll: 'article of clothing', root: '拉丁语 articulus' },
    { word: 'artificial', phonetic: '/ˌɑːrtɪˈfɪʃəl/', pos: 'adj.', meaning: '人工的', eg: 'Artificial flower.', trans: '人造花。', coll: 'artificial intelligence', root: '拉丁语 artificialis' },
    { word: 'artist', phonetic: '/ˈɑːrtɪst/', pos: 'n.', meaning: '艺术家', eg: 'Famous artist.', trans: '著名艺术家。', coll: 'pop artist', root: 'art + -ist' },
    { word: 'as', phonetic: '/æz/', pos: 'prep.', meaning: '作为', eg: 'As student.', trans: '作为学生。', coll: 'as well as', root: '古英语 æs' },
    { word: 'ash', phonetic: '/æʃ/', pos: 'n.', meaning: '灰', eg: 'Volcanic ash.', trans: '火山灰。', coll: 'ash tree', root: '古英语 æsce' },
    { word: 'ashamed', phonetic: '/əˈʃeɪmd/', pos: 'adj.', meaning: '羞愧的', eg: 'Feel ashamed.', trans: '感到羞愧。', coll: 'be ashamed', root: '古英语 āscamian' },
    { word: 'aspect', phonetic: '/ˈæspekt/', pos: 'n.', meaning: '方面', eg: 'Important aspect.', trans: '重要方面。', coll: 'aspect of life', root: '拉丁语 aspectus' },
    { word: 'assemble', phonetic: '/əˈsembəl/', pos: 'v.', meaning: '组装', eg: 'Assemble parts.', trans: '组装零件。', coll: 'assemble team', root: '拉丁语 assemblare' },
    { word: 'assembly', phonetic: '/əˈsembli/', pos: 'n.', meaning: '集合', eg: 'General assembly.', trans: '大会。', coll: 'assembly line', root: 'assemble 的名词' },
    { word: 'assess', phonetic: '/əˈses/', pos: 'v.', meaning: '评估', eg: 'Assess value.', trans: '评估价值。', coll: 'assess risk', root: '拉丁语 assessare' },
    { word: 'assessment', phonetic: '/əˈsesmənt/', pos: 'n.', meaning: '评估', eg: 'Performance assessment.', trans: '绩效评估。', coll: 'needs assessment', root: 'assess + -ment' },
    { word: 'asset', phonetic: '/ˈæset/', pos: 'n.', meaning: '资产', eg: 'Financial asset.', trans: '金融资产。', coll: 'asset management', root: '拉丁语 asset' },
    { word: 'assign', phonetic: '/əˈsaɪn/', pos: 'v.', meaning: '分配', eg: 'Assign task.', trans: '分配任务。', coll: 'assign to', root: '拉丁语 assignare' },
    { word: 'assignment', phonetic: '/əˈsaɪnmənt/', pos: 'n.', meaning: '作业', eg: 'Homework assignment.', trans: '家庭作业。', coll: 'assignment deadline', root: 'assign + -ment' },
    { word: 'assist', phonetic: '/əˈsɪst/', pos: 'v.', meaning: '协助', eg: 'Assist others.', trans: '协助他人。', coll: 'assist with', root: '拉丁语 assistere' },
    { word: 'assistance', phonetic: '/əˈsɪstəns/', pos: 'n.', meaning: '帮助', eg: 'Need assistance.', trans: '需要帮助。', coll: 'financial assistance', root: 'assist + -ance' },
    { word: 'assistant', phonetic: '/əˈsɪstənt/', pos: 'n.', meaning: '助理', eg: 'Teaching assistant.', trans: '助教。', coll: 'personal assistant', root: 'assist + -ant' },
    { word: 'associate', phonetic: '/əˈsoʊʃieɪt/', pos: 'v.', meaning: '联系', eg: 'Associate with.', trans: '联系。', coll: 'associate with', root: '拉丁语 associatus' },
    { word: 'association', phonetic: '/əˌsoʊʃiˈeɪʃən/', pos: 'n.', meaning: '协会', eg: 'Trade association.', trans: '贸易协会。', coll: 'association member', root: 'associate + -ation' },
    { word: 'assume', phonetic: '/əˈsuːm/', pos: 'v.', meaning: '假设', eg: 'Assume true.', trans: '假设为真。', coll: 'assume responsibility', root: '拉丁语 assumere' },
    { word: 'assumption', phonetic: '/əˈsʌmpʃən/', pos: 'n.', meaning: '假设', eg: 'Wrong assumption.', trans: '错误假设。', coll: 'under assumption', root: 'assume + -ption' },
    { word: 'assure', phonetic: '/əˈʃʊr/', pos: 'v.', meaning: '保证', eg: 'Assure safety.', trans: '保证安全。', coll: 'assure someone', root: '拉丁语 assicurare' },
    { word: 'astonish', phonetic: '/əˈstɑːnɪʃ/', pos: 'v.', meaning: '使惊讶', eg: 'Astonish me.', trans: '让我惊讶。', coll: 'be astonished', root: '拉丁语 astonire' },
    { word: 'at', phonetic: '/æt/', pos: 'prep.', meaning: '在', eg: 'At home.', trans: '在家。', coll: 'at school', root: '古英语 æt' },
    { word: 'atmosphere', phonetic: '/ˈætməsfɪər/', pos: 'n.', meaning: '气氛', eg: 'Good atmosphere.', trans: '良好氛围。', coll: 'atmosphere pressure', root: '希腊语 atmos' },
    { word: 'atom', phonetic: '/ˈætəm/', pos: 'n.', meaning: '原子', eg: 'Atomic structure.', trans: '原子结构。', coll: 'atomic bomb', root: '希腊语 atomos' },
    { word: 'attach', phonetic: '/əˈtætʃ/', pos: 'v.', meaning: '附加', eg: 'Attach file.', trans: '附加文件。', coll: 'attach to', root: '拉丁语 attaccare' },
    { word: 'attack', phonetic: '/əˈtæk/', pos: 'v.', meaning: '攻击', eg: 'Attack enemy.', trans: '攻击敌人。', coll: 'attack on', root: '拉丁语 attaccare' },
    { word: 'attain', phonetic: '/əˈteɪn/', pos: 'v.', meaning: '获得', eg: 'Attain goal.', trans: '达到目标。', coll: 'attain success', root: '拉丁语 attingere' },
    { word: 'attempt', phonetic: '/əˈtempt/', pos: 'n.', meaning: '尝试', eg: 'Make attempt.', trans: '尝试。', coll: 'attempt to', root: '拉丁语 attemptare' },
    { word: 'attend', phonetic: '/əˈtend/', pos: 'v.', meaning: '参加', eg: 'Attend meeting.', trans: '参加会议。', coll: 'attend school', root: '拉丁语 attendere' },
    { word: 'attention', phonetic: '/əˈtenʃən/', pos: 'n.', meaning: '注意', eg: 'Pay attention.', trans: '注意。', coll: 'draw attention', root: 'attend + -ion' },
    { word: 'attractive', phonetic: '/əˈtræktɪv/', pos: 'adj.', meaning: '有吸引力的', eg: 'Attractive offer.', trans: '诱人的报价。', coll: 'attractive price', root: 'attract + -ive' },
    { word: 'attribute', phonetic: '/əˈtrɪbjuːt/', pos: 'n.', meaning: '属性', eg: 'Key attribute.', trans: '关键属性。', coll: 'attribute to', root: '拉丁语 attributum' },
    { word: 'audience', phonetic: '/ˈɔːdiəns/', pos: 'n.', meaning: '观众', eg: 'Large audience.', trans: '大量观众。', coll: 'target audience', root: '拉丁语 audientia' },
    { word: 'audio', phonetic: '/ˈɔːdiəʊ/', pos: 'n.', meaning: '音频', eg: 'Audio file.', trans: '音频文件。', coll: 'audio quality', root: '拉丁语 audire' },
    { word: 'author', phonetic: '/ˈɔːθər/', pos: 'n.', meaning: '作者', eg: 'Famous author.', trans: '著名作者。', coll: 'best-selling author', root: '拉丁语 auctor' },
    { word: 'authority', phonetic: '/əˈθɔːrəti/', pos: 'n.', meaning: '权威', eg: 'Local authority.', trans: '地方当局。', coll: 'authority figure', root: 'author + -ity' },
    { word: 'auto', phonetic: '/ˈɔːtoʊ/', pos: 'n.', meaning: '汽车', eg: 'Auto industry.', trans: '汽车工业。', coll: 'auto parts', root: '希腊语 autos' },
    { word: 'automatic', phonetic: '/ˌɔːtəˈmætɪk/', pos: 'adj.', meaning: '自动的', eg: 'Automatic door.', trans: '自动门。', coll: 'automatic transmission', root: 'auto + -matic' },
    { word: 'automobile', phonetic: '/ˈɔːtəməbiːl/', pos: 'n.', meaning: '汽车', eg: 'New automobile.', trans: '新车。', coll: 'automobile industry', root: 'auto + mobile' },
    { word: 'autumn', phonetic: '/ˈɔːtəm/', pos: 'n.', meaning: '秋天', eg: 'Golden autumn.', trans: '金秋。', coll: 'autumn leaves', root: '拉丁语 autumnus' },
    { word: 'available', phonetic: '/əˈveɪləbl/', pos: 'adj.', meaning: '可用的', eg: 'Available now.', trans: '现在可用。', coll: 'available time', root: 'avail + -able' },
    { word: 'average', phonetic: '/ˈævərɪdʒ/', pos: 'n.', meaning: '平均', eg: 'Above average.', trans: '高于平均。', coll: 'average cost', root: '拉丁语 averagium' },
    { word: 'avoid', phonetic: '/əˈvɔɪd/', pos: 'v.', meaning: '避免', eg: 'Avoid mistakes.', trans: '避免错误。', coll: 'avoid doing', root: 'a- + void' },
    { word: 'await', phonetic: '/əˈweɪt/', pos: 'v.', meaning: '等待', eg: 'Await response.', trans: '等待回应。', coll: 'await decision', root: 'a- + wait' },
    { word: 'awake', phonetic: '/əˈweɪk/', pos: 'adj.', meaning: '醒着的', eg: 'Stay awake.', trans: '保持清醒。', coll: 'wide awake', root: '古英语 āwæcnan' },
    { word: 'award', phonetic: '/əˈwɔːrd/', pos: 'n.', meaning: '奖项', eg: 'Win award.', trans: '获奖。', coll: 'award ceremony', root: '古英语 award' },
    { word: 'aware', phonetic: '/əˈweər/', pos: 'adj.', meaning: '意识到的', eg: 'Be aware.', trans: '意识到。', coll: 'aware of', root: '古英语 gewaer' },
    { word: 'awareness', phonetic: '/əˈweərnəs/', pos: 'n.', meaning: '意识', eg: 'Raise awareness.', trans: '提高意识。', coll: 'environmental awareness', root: 'aware + -ness' },
    { word: 'away', phonetic: '/əˈweɪ/', pos: 'adv.', meaning: '离开', eg: 'Go away.', trans: '走开。', coll: 'far away', root: '古英语 aweg' },
    { word: 'awful', phonetic: '/ˈɔːfl/', pos: 'adj.', meaning: '可怕的', eg: 'Awful weather.', trans: '糟糕的天气。', coll: 'awful lot', root: 'awe + -ful' },
    { word: 'awkward', phonetic: '/ˈɔːkwərd/', pos: 'adj.', meaning: '尴尬的', eg: 'Awkward moment.', trans: '尴尬时刻。', coll: 'awkward silence', root: '古英语 awke' },
    { word: 'baby', phonetic: '/ˈbeɪbi/', pos: 'n.', meaning: '婴儿', eg: 'Cute baby.', trans: '可爱的婴儿。', coll: 'baby boy', root: '古英语 babi' },
    { word: 'back', phonetic: '/bæk/', pos: 'n.', meaning: '背部', eg: 'Turn back.', trans: '转身。', coll: 'back to', root: '古英语 bæc' },
    { word: 'background', phonetic: '/ˈbækɡraʊnd/', pos: 'n.', meaning: '背景', eg: 'White background.', trans: '白色背景。', coll: 'background check', root: 'back + ground' },
    { word: 'bad', phonetic: '/bæd/', pos: 'adj.', meaning: '坏的', eg: 'Bad news.', trans: '坏消息。', coll: 'bad luck', root: '古英语 bæddel' },
    { word: 'badly', phonetic: '/ˈbædli/', pos: 'adv.', meaning: '严重地', eg: 'Hurt badly.', trans: '伤得很重。', coll: 'badly need', root: 'bad + -ly' },
    { word: 'bag', phonetic: '/bæɡ/', pos: 'n.', meaning: '包', eg: 'Leather bag.', trans: '皮包。', coll: 'hand bag', root: '古英语 bagge' },
    { word: 'balance', phonetic: '/ˈbæləns/', pos: 'n.', meaning: '平衡', eg: 'Keep balance.', trans: '保持平衡。', coll: 'balance sheet', root: '拉丁语 bilanx' },
    { word: 'ball', phonetic: '/bɔːl/', pos: 'n.', meaning: '球', eg: 'Play ball.', trans: '打球。', coll: 'ball game', root: '古英语 beall' },
    { word: 'ban', phonetic: '/bæn/', pos: 'v.', meaning: '禁止', eg: 'Ban smoking.', trans: '禁止吸烟。', coll: 'ban on', root: '古英语 bannan' },
    { word: 'band', phonetic: '/bænd/', pos: 'n.', meaning: '乐队', eg: 'Rock band.', trans: '摇滚乐队。', coll: 'band member', root: '古英语 bend' },
    { word: 'bank', phonetic: '/bæŋk/', pos: 'n.', meaning: '银行', eg: 'Central bank.', trans: '中央银行。', coll: 'bank account', root: '意大利语 banco' },
    { word: 'bar', phonetic: '/bɑːr/', pos: 'n.', meaning: '酒吧', eg: 'Go to bar.', trans: '去酒吧。', coll: 'bar counter', root: '拉丁语 barra' },
    { word: 'barrier', phonetic: '/ˈbæriər/', pos: 'n.', meaning: '障碍', eg: 'Language barrier.', trans: '语言障碍。', coll: 'trade barrier', root: 'bar + -ier' },
    { word: 'base', phonetic: '/beɪs/', pos: 'n.', meaning: '基础', eg: 'Military base.', trans: '军事基地。', coll: 'base on', root: '拉丁语 basis' },
    { word: 'basic', phonetic: '/ˈbeɪsɪk/', pos: 'adj.', meaning: '基本的', eg: 'Basic skills.', trans: '基本技能。', coll: 'basic knowledge', root: 'base + -ic' },
    { word: 'basis', phonetic: '/ˈbeɪsɪs/', pos: 'n.', meaning: '基础', eg: 'On basis.', trans: '基于。', coll: 'on the basis', root: '希腊语 basis' },
    { word: 'basket', phonetic: '/ˈbæskɪt/', pos: 'n.', meaning: '篮子', eg: 'Picnic basket.', trans: '野餐篮。', coll: 'basket ball', root: '古英语 bæsket' },
    { word: 'bath', phonetic: '/bæθ/', pos: 'n.', meaning: '沐浴', eg: 'Take bath.', trans: '洗澡。', coll: 'bath room', root: '古英语 bæð' },
    { word: 'battery', phonetic: '/ˈbætəri/', pos: 'n.', meaning: '电池', eg: 'Car battery.', trans: '汽车电池。', coll: 'battery life', root: '法语 batterie' },
    { word: 'battle', phonetic: '/ˈbætl/', pos: 'n.', meaning: '战斗', eg: 'Battle field.', trans: '战场。', coll: 'battle for', root: '古法语 bataille' },
    { word: 'be', phonetic: '/biː/', pos: 'v.', meaning: '是', eg: 'I am.', trans: '我是。', coll: 'be happy', root: '古英语 beon' },
    { word: 'beach', phonetic: '/biːtʃ/', pos: 'n.', meaning: '海滩', eg: 'Sandy beach.', trans: '沙滩。', coll: 'beach resort', root: '古英语 bēce' },
    { word: 'bear', phonetic: '/beər/', pos: 'v.', meaning: '承受', eg: 'Bear pain.', trans: '承受痛苦。', coll: 'bear with', root: '古英语 beran' },
    { word: 'beautiful', phonetic: '/ˈbjuːtɪfl/', pos: 'adj.', meaning: '美丽的', eg: 'Beautiful view.', trans: '美丽景色。', coll: 'beautiful day', root: 'beauty + -ful' },
    { word: 'beauty', phonetic: '/ˈbjuːti/', pos: 'n.', meaning: '美丽', eg: 'Natural beauty.', trans: '自然美。', coll: 'beauty contest', root: '拉丁语 bellus' },
    { word: 'because', phonetic: '/bɪˈkɔːz/', pos: 'conj.', meaning: '因为', eg: 'Because of.', trans: '因为。', coll: 'because of', root: '古英语 becaus' },
    { word: 'become', phonetic: '/bɪˈkʌm/', pos: 'v.', meaning: '成为', eg: 'Become famous.', trans: '成名。', coll: 'become of', root: '古英语 becuman' },
    { word: 'bed', phonetic: '/bed/', pos: 'n.', meaning: '床', eg: 'Go to bed.', trans: '上床睡觉。', coll: 'bed room', root: '古英语 bedd' },
    { word: 'before', phonetic: '/bɪˈfɔːr/', pos: 'prep.', meaning: '在...前', eg: 'Before dinner.', trans: '晚饭前。', coll: 'before long', root: '古英语 beforan' },
    { word: 'begin', phonetic: '/bɪˈɡɪn/', pos: 'v.', meaning: '开始', eg: 'Begin now.', trans: '现在开始。', coll: 'begin with', root: '古英语 beginnan' },
    { word: 'beginning', phonetic: '/bɪˈɡɪnɪŋ/', pos: 'n.', meaning: '开始', eg: 'New beginning.', trans: '新开始。', coll: 'at beginning', root: 'begin + -ing' },
    { word: 'behavior', phonetic: '/bɪˈheɪvjər/', pos: 'n.', meaning: '行为', eg: 'Good behavior.', trans: '良好行为。', coll: 'behavior pattern', root: '拉丁语 behavior' },
    { word: 'behind', phonetic: '/bɪˈhaɪnd/', pos: 'prep.', meaning: '在...后', eg: 'Behind door.', trans: '门后。', coll: 'fall behind', root: '古英语 behindan' },
    { word: 'believe', phonetic: '/bɪˈliːv/', pos: 'v.', meaning: '相信', eg: 'Believe in.', trans: '相信。', coll: 'believe in', root: '古英语 belȳfan' },
    { word: 'bell', phonetic: '/bel/', pos: 'n.', meaning: '铃', eg: 'Ring bell.', trans: '按铃。', coll: 'door bell', root: '古英语 belle' },
    { word: 'belong', phonetic: '/bɪˈlɔːŋ/', pos: 'v.', meaning: '属于', eg: 'Belong to.', trans: '属于。', coll: 'belong to', root: '古英语 belang' },
    { word: 'below', phonetic: '/bɪˈloʊ/', pos: 'prep.', meaning: '在...下', eg: 'Below zero.', trans: '零下。', coll: 'below average', root: '古英语 belawe' },
    { word: 'benefit', phonetic: '/ˈbenɪfɪt/', pos: 'n.', meaning: '利益', eg: 'Get benefit.', trans: '获得利益。', coll: 'benefit from', root: '拉丁语 beneficium' },
    { word: 'best', phonetic: '/best/', pos: 'adj.', meaning: '最好的', eg: 'Best friend.', trans: '最好的朋友。', coll: 'do best', root: '古英语 betst' },
    { word: 'bet', phonetic: '/bet/', pos: 'v.', meaning: '打赌', eg: 'Bet on.', trans: '打赌。', coll: 'bet on', root: '古英语 bētan' },
    { word: 'better', phonetic: '/ˈbetər/', pos: 'adj.', meaning: '更好的', eg: 'Better than.', trans: '比...更好。', coll: 'better off', root: '古英语 betera' },
    { word: 'between', phonetic: '/bɪˈtwiːn/', pos: 'prep.', meaning: '在...之间', eg: 'Between us.', trans: '在我们之间。', coll: 'between and', root: '古英语 betweonum' },
    { word: 'beyond', phonetic: '/bɪˈjɒnd/', pos: 'prep.', meaning: '超越', eg: 'Beyond reach.', trans: '超出范围。', coll: 'beyond doubt', root: '古英语 begeondan' },
    { word: 'big', phonetic: '/bɪɡ/', pos: 'adj.', meaning: '大的', eg: 'Big house.', trans: '大房子。', coll: 'big deal', root: '古英语 big' },
    { word: 'bill', phonetic: '/bɪl/', pos: 'n.', meaning: '账单', eg: 'Pay bill.', trans: '付账单。', coll: 'phone bill', root: '古英语 bill' },
    { word: 'billion', phonetic: '/ˈbɪljən/', pos: 'num.', meaning: '十亿', eg: 'One billion.', trans: '十亿。', coll: 'billion dollar', root: '拉丁语 bi- + million' },
    { word: 'bind', phonetic: '/baɪnd/', pos: 'v.', meaning: '捆绑', eg: 'Bind together.', trans: '绑在一起。', coll: 'bind up', root: '古英语 bindan' },
    { word: 'biology', phonetic: '/baɪˈɒlədʒi/', pos: 'n.', meaning: '生物学', eg: 'Study biology.', trans: '学习生物学。', coll: 'molecular biology', root: '希腊语 bios + logia' },
    { word: 'bird', phonetic: '/bɜːrd/', pos: 'n.', meaning: '鸟', eg: 'Little bird.', trans: '小鸟。', coll: 'bird watching', root: '古英语 brid' },
    { word: 'birth', phonetic: '/bɜːrθ/', pos: 'n.', meaning: '出生', eg: 'Date of birth.', trans: '出生日期。', coll: 'give birth', root: '古英语 birt' },
    { word: 'bit', phonetic: '/bɪt/', pos: 'n.', meaning: '一点', eg: 'A bit.', trans: '一点。', coll: 'a bit of', root: '古英语 bite' },
    { word: 'black', phonetic: '/blæk/', pos: 'adj.', meaning: '黑色的', eg: 'Black cat.', trans: '黑猫。', coll: 'black and white', root: '古英语 blæc' },
    { word: 'blame', phonetic: '/bleɪm/', pos: 'v.', meaning: '责备', eg: 'Blame me.', trans: '责备我。', coll: 'blame for', root: '古法语 blasmer' },
    { word: 'blank', phonetic: '/blæŋk/', pos: 'adj.', meaning: '空白的', eg: 'Blank page.', trans: '空白页。', coll: 'blank check', root: '古法语 blanc' },
    { word: 'bleed', phonetic: '/bliːd/', pos: 'v.', meaning: '流血', eg: 'Bleed heavily.', trans: '大量流血。', coll: 'bleed to death', root: '古英语 blēdan' },
    { word: 'blend', phonetic: '/blend/', pos: 'v.', meaning: '混合', eg: 'Blend colors.', trans: '混合颜色。', coll: 'blend in', root: '古英语 blendan' },
    { word: 'blind', phonetic: '/blaɪnd/', pos: 'adj.', meaning: '盲的', eg: 'Blind man.', trans: '盲人。', coll: 'blind eye', root: '古英语 blind' },
    { word: 'block', phonetic: '/blɒk/', pos: 'n.', meaning: '块', eg: 'Block of wood.', trans: '木块。', coll: 'block off', root: '古法语 bloc' },
    { word: 'blood', phonetic: '/blʌd/', pos: 'n.', meaning: '血液', eg: 'Fresh blood.', trans: '新鲜血液。', coll: 'blood pressure', root: '古英语 blōd' },
    { word: 'blow', phonetic: '/bloʊ/', pos: 'v.', meaning: '吹', eg: 'Blow wind.', trans: '风吹。', coll: 'blow up', root: '古英语 blāwan' },
    { word: 'blue', phonetic: '/bluː/', pos: 'adj.', meaning: '蓝色的', eg: 'Blue sky.', trans: '蓝天。', coll: 'blue eyes', root: '古英语 blāw' },
    { word: 'board', phonetic: '/bɔːrd/', pos: 'n.', meaning: '板', eg: 'Notice board.', trans: '布告板。', coll: 'board meeting', root: '古英语 bord' },
    { word: 'boat', phonetic: '/boʊt/', pos: 'n.', meaning: '船', eg: 'Sail boat.', trans: '帆船。', coll: 'boat trip', root: '古英语 bāt' },
    { word: 'body', phonetic: '/ˈbɒdi/', pos: 'n.', meaning: '身体', eg: 'Healthy body.', trans: '健康的身体。', coll: 'body language', root: '古英语 bodig' },
    { word: 'boil', phonetic: '/bɔɪl/', pos: 'v.', meaning: '沸腾', eg: 'Boil water.', trans: '烧水。', coll: 'boil over', root: '古法语 bouillir' },
    { word: 'bold', phonetic: '/boʊld/', pos: 'adj.', meaning: '大胆的', eg: 'Bold move.', trans: '大胆的举动。', coll: 'bold type', root: '古英语 beald' },
    { word: 'bone', phonetic: '/boʊn/', pos: 'n.', meaning: '骨头', eg: 'Broken bone.', trans: '骨折。', coll: 'bone marrow', root: '古英语 bān' },
    { word: 'book', phonetic: '/bʊk/', pos: 'n.', meaning: '书', eg: 'Read book.', trans: '读书。', coll: 'book store', root: '古英语 bōc' },
    { word: 'border', phonetic: '/ˈbɔːrdər/', pos: 'n.', meaning: '边界', eg: 'Cross border.', trans: '越界。', coll: 'border control', root: '古法语 bordure' },
    { word: 'borrow', phonetic: '/ˈbɒroʊ/', pos: 'v.', meaning: '借', eg: 'Borrow money.', trans: '借钱。', coll: 'borrow from', root: '古英语 borgian' },
    { word: 'boss', phonetic: '/bɒs/', pos: 'n.', meaning: '老板', eg: 'My boss.', trans: '我的老板。', coll: 'boss around', root: '荷兰语 baas' },
    { word: 'both', phonetic: '/boʊθ/', pos: 'adj.', meaning: '两者都', eg: 'Both sides.', trans: '两边都。', coll: 'both and', root: '古英语 b