const fs = require('fs');

// 基础单词模板库
const templates = [
  { word: 'abandon', phonetic: '/əˈbændən/', pos: 'v.', meaning: '放弃；遗弃', eg: 'He abandoned his plan.', trans: '他放弃了计划。', coll: 'abandon plan; with abandon', root: 'aban- (离开) + -don' },
  { word: 'ability', phonetic: '/əˈbɪləti/', pos: 'n.', meaning: '能力', eg: 'She has great ability.', trans: '她能力很强。', coll: 'ability to do; have ability', root: 'able + -ity' },
  { word: 'able', phonetic: '/ˈeɪbl/', pos: 'adj.', meaning: '能够的', eg: 'I am able to help.', trans: '我能帮忙。', coll: 'be able to; able-bodied', root: '拉丁语 habilis' },
  { word: 'about', phonetic: '/əˈbaʊt/', pos: 'prep./adv.', meaning: '关于；大约', eg: 'Tell me about it.', trans: '告诉我关于它。', coll: 'talk about; think about', root: '古英语 abutan' },
  { word: 'above', phonetic: '/əˈbʌv/', pos: 'prep./adv.', meaning: '在...上面', eg: 'The sun is above.', trans: '太阳在上面。', coll: 'above all; above average', root: '古英语 abufan' },
  { word: 'abroad', phonetic: '/əˈbrɔːd/', pos: 'adv.', meaning: '在国外', eg: 'Go abroad to study.', trans: '去国外学习。', coll: 'go abroad; study abroad', root: 'a- + broad' },
  { word: 'absence', phonetic: '/ˈæbsəns/', pos: 'n.', meaning: '缺席', eg: 'His absence was noted.', trans: '他的缺席被注意到。', coll: 'in the absence of', root: 'absent + -ce' },
  { word: 'absent', phonetic: '/ˈæbsənt/', pos: 'adj.', meaning: '缺席的', eg: 'She is absent today.', trans: '她今天缺席。', coll: 'be absent from', root: 'abs- + -ent' },
  { word: 'absolute', phonetic: '/ˈæbsəluːt/', pos: 'adj.', meaning: '绝对的', eg: 'Absolute truth.', trans: '绝对真理。', coll: 'absolute value', root: 'abs- + solutus' },
  { word: 'absorb', phonetic: '/əbˈsɔːrb/', pos: 'v.', meaning: '吸收', eg: 'Plants absorb water.', trans: '植物吸收水分。', coll: 'absorb knowledge', root: 'abs- + sorbere' },
  { word: 'abstract', phonetic: '/ˈæbstrækt/', pos: 'adj.', meaning: '抽象的', eg: 'Abstract concept.', trans: '抽象概念。', coll: 'abstract art', root: 'abs- + trahere' },
  { word: 'academic', phonetic: '/ˌækəˈdemɪk/', pos: 'adj.', meaning: '学术的', eg: 'Academic research.', trans: '学术研究。', coll: 'academic year', root: '希腊语 akademeia' },
  { word: 'accept', phonetic: '/əkˈsept/', pos: 'v.', meaning: '接受', eg: 'Accept the invitation.', trans: '接受邀请。', coll: 'accept responsibility', root: 'ac- + capere' },
  { word: 'access', phonetic: '/ˈækses/', pos: 'n.', meaning: '通道；访问', eg: 'Access is restricted.', trans: '访问受限。', coll: 'access to', root: '拉丁语 accessus' },
  { word: 'accident', phonetic: '/ˈæksɪdənt/', pos: 'n.', meaning: '事故', eg: 'A car accident.', trans: '一起车祸。', coll: 'traffic accident', root: 'ac- + cadere' },
  { word: 'accompany', phonetic: '/əˈkʌmpəni/', pos: 'v.', meaning: '陪伴', eg: 'Accompany me.', trans: '陪我。', coll: 'accompany to', root: 'ac- + compania' },
  { word: 'accomplish', phonetic: '/əˈkɑːmplɪʃ/', pos: 'v.', meaning: '完成', eg: 'Accomplish the task.', trans: '完成任务。', coll: 'accomplish goal', root: 'ac- + complere' },
  { word: 'account', phonetic: '/əˈkaʊnt/', pos: 'n.', meaning: '账户', eg: 'Open an account.', trans: '开户。', coll: 'bank account', root: 'ac- + computare' },
  { word: 'accurate', phonetic: '/ˈækjərət/', pos: 'adj.', meaning: '准确的', eg: 'Accurate data.', trans: '准确数据。', coll: 'accurate measurement', root: 'ac- + curare' },
  { word: 'achieve', phonetic: '/əˈtʃiːv/', pos: 'v.', meaning: '实现', eg: 'Achieve success.', trans: '取得成功。', coll: 'achieve goal', root: '拉丁语 achievre' },
  { word: 'achievement', phonetic: '/əˈtʃiːvmənt/', pos: 'n.', meaning: '成就', eg: 'Great achievement.', trans: '伟大成就。', coll: 'academic achievement', root: 'achieve + -ment' },
  { word: 'acknowledge', phonetic: '/əkˈnɑːlɪdʒ/', pos: 'v.', meaning: '承认', eg: 'Acknowledge the mistake.', trans: '承认错误。', coll: 'acknowledge receipt', root: 'ac- + cognoscere' },
  { word: 'acquire', phonetic: '/əˈkwaɪər/', pos: 'v.', meaning: '获得', eg: 'Acquire skills.', trans: '获得技能。', coll: 'acquire knowledge', root: 'ac- + quaerere' },
  { word: 'across', phonetic: '/əˈkrɔːs/', pos: 'prep.', meaning: '穿过', eg: 'Walk across.', trans: '穿过。', coll: 'come across', root: 'a- + cross' },
  { word: 'action', phonetic: '/ˈækʃn/', pos: 'n.', meaning: '行动', eg: 'Take action.', trans: '采取行动。', coll: 'action plan', root: '拉丁语 actio' },
  { word: 'active', phonetic: '/ˈæktɪv/', pos: 'adj.', meaning: '活跃的', eg: 'Active member.', trans: '活跃成员。', coll: 'active participation', root: 'act + -ive' },
  { word: 'activity', phonetic: '/ækˈtɪvəti/', pos: 'n.', meaning: '活动', eg: 'Outdoor activity.', trans: '户外活动。', coll: 'physical activity', root: 'active + -ity' },
  { word: 'actual', phonetic: '/ˈæktʃuəl/', pos: 'adj.', meaning: '实际的', eg: 'Actual cost.', trans: '实际成本。', coll: 'actual situation', root: '拉丁语 actualis' },
  { word: 'adapt', phonetic: '/əˈdæpt/', pos: 'v.', meaning: '适应', eg: 'Adapt to change.', trans: '适应变化。', coll: 'adapt to', root: 'ad- + aptare' },
  { word: 'add', phonetic: '/æd/', pos: 'v.', meaning: '添加', eg: 'Add sugar.', trans: '加糖。', coll: 'add to', root: '拉丁语 addere' },
  { word: 'addition', phonetic: '/əˈdɪʃn/', pos: 'n.', meaning: '添加', eg: 'In addition.', trans: '此外。', coll: 'in addition to', root: 'add + -ition' },
  { word: 'additional', phonetic: '/əˈdɪʃənl/', pos: 'adj.', meaning: '额外的', eg: 'Additional cost.', trans: '额外成本。', coll: 'additional info', root: 'addition + -al' },
  { word: 'address', phonetic: '/əˈdres/', pos: 'n.', meaning: '地址', eg: 'Write your address.', trans: '写地址。', coll: 'home address', root: 'ad- + direcere' },
  { word: 'adequate', phonetic: '/ˈædɪkwət/', pos: 'adj.', meaning: '足够的', eg: 'Adequate time.', trans: '足够时间。', coll: 'adequate resources', root: '拉丁语 adequatus' },
  { word: 'adjust', phonetic: '/əˈdʒʌst/', pos: 'v.', meaning: '调整', eg: 'Adjust settings.', trans: '调整设置。', coll: 'adjust to', root: 'ad- + justus' },
  { word: 'administration', phonetic: '/ədˌmɪnɪˈstreɪʃn/', pos: 'n.', meaning: '管理', eg: 'School administration.', trans: '学校管理。', coll: 'public administration', root: 'administrate + -ion' },
  { word: 'admire', phonetic: '/ədˈmaɪər/', pos: 'v.', meaning: '钦佩', eg: 'Admire his work.', trans: '钦佩他的工作。', coll: 'admire for', root: 'ad- + mirari' },
  { word: 'admission', phonetic: '/ədˈmɪʃn/', pos: 'n.', meaning: '入场', eg: 'Admission is free.', trans: '免费入场。', coll: 'admission fee', root: 'ad- + mittere' },
  { word: 'admit', phonetic: '/ədˈmɪt/', pos: 'v.', meaning: '承认', eg: 'Admit mistake.', trans: '承认错误。', coll: 'admit to', root: 'ad- + mittere' },
  { word: 'adopt', phonetic: '/əˈdɑːpt/', pos: 'v.', meaning: '采用', eg: 'Adopt policy.', trans: '采用政策。', coll: 'adopt child', root: '拉丁语 adoptare' },
  { word: 'advance', phonetic: '/ədˈvæns/', pos: 'v.', meaning: '前进', eg: 'Advance forward.', trans: '向前推进。', coll: 'in advance', root: '拉丁语 abante' },
  { word: 'advanced', phonetic: '/ədˈvænst/', pos: 'adj.', meaning: '先进的', eg: 'Advanced tech.', trans: '先进技术。', coll: 'advanced level', root: 'advance + -ed' },
  { word: 'advantage', phonetic: '/ədˈvæntɪdʒ/', pos: 'n.', meaning: '优势', eg: 'Great advantage.', trans: '巨大优势。', coll: 'take advantage', root: 'ad- + vantus' },
  { word: 'adventure', phonetic: '/ədˈventʃər/', pos: 'n.', meaning: '冒险', eg: 'Life is adventure.', trans: '人生是冒险。', coll: 'adventure story', root: 'ad- + ventura' },
  { word: 'advertise', phonetic: '/ˈædvərtaɪz/', pos: 'v.', meaning: '广告', eg: 'Advertise product.', trans: '为产品做广告。', coll: 'advertise on TV', root: '拉丁语 advertere' },
  { word: 'advice', phonetic: '/ədˈvaɪs/', pos: 'n.', meaning: '建议', eg: 'Give advice.', trans: '给建议。', coll: 'take advice', root: '拉丁语 advidere' },
  { word: 'advise', phonetic: '/ədˈvaɪz/', pos: 'v.', meaning: '建议', eg: 'Advise to study.', trans: '建议学习。', coll: 'advise against', root: '拉丁语 advidere' },
  { word: 'affair', phonetic: '/əˈfeər/', pos: 'n.', meaning: '事务', eg: 'Public affairs.', trans: '公共事务。', coll: 'private affair', root: '拉丁语 adferre' },
  { word: 'affect', phonetic: '/əˈfekt/', pos: 'v.', meaning: '影响', eg: 'Affect mood.', trans: '影响心情。', coll: 'be affected by', root: '拉丁语 afficere' },
  { word: 'afford', phonetic: '/əˈfɔːrd/', pos: 'v.', meaning: '负担', eg: 'Afford a car.', trans: '买得起车。', coll: 'cannot afford', root: '古英语 afordian' },
  { word: 'afraid', phonetic: '/əˈfreɪd/', pos: 'adj.', meaning: '害怕的', eg: 'Afraid of dogs.', trans: '怕狗。', coll: 'be afraid of', root: '古英语 afræd' },
  { word: 'after', phonetic: '/ˈɑːftər/', pos: 'prep.', meaning: '在...之后', eg: 'After school.', trans: '放学后。', coll: 'after work', root: '古英语 æfter' },
  { word: 'afternoon', phonetic: '/ˌæftərˈnuːn/', pos: 'n.', meaning: '下午', eg: 'Good afternoon.', trans: '下午好。', coll: 'in the afternoon', root: 'after + noon' },
  { word: 'again', phonetic: '/əˈɡen/', pos: 'adv.', meaning: '再次', eg: 'Try again.', trans: '再试一次。', coll: 'again and again', root: '古英语 agan' },
  { word: 'against', phonetic: '/əˈɡenst/', pos: 'prep.', meaning: '反对', eg: 'Against the plan.', trans: '反对计划。', coll: 'be against', root: '古英语 ongean' },
  { word: 'age', phonetic: '/eɪdʒ/', pos: 'n.', meaning: '年龄', eg: 'What is your age?', trans: '你几岁？', coll: 'at the age of', root: '拉丁语 aetas' },
  { word: 'agency', phonetic: '/ˈeɪdʒənsi/', pos: 'n.', meaning: '机构', eg: 'Travel agency.', trans: '旅行社。', coll: 'government agency', root: 'agent + -cy' },
  { word: 'agent', phonetic: '/ˈeɪdʒənt/', pos: 'n.', meaning: '代理人', eg: 'Real estate agent.', trans: '房产经纪人。', coll: 'travel agent', root: '拉丁语 agens' },
  { word: 'aggressive', phonetic: '/əˈɡresɪv/', pos: 'adj.', meaning: '积极的', eg: 'Aggressive marketing.', trans: '积极营销。', coll: 'aggressive behavior', root: 'aggress + -ive' },
  { word: 'ago', phonetic: '/əˈɡoʊ/', pos: 'adv.', meaning: '以前', eg: 'Years ago.', trans: '几年前。', coll: 'long ago', root: '古英语 agan' },
  { word: 'agree', phonetic: '/əˈɡriː/', pos: 'v.', meaning: '同意', eg: 'Agree with you.', trans: '同意你。', coll: 'agree on', root: '拉丁语 adgratus' },
  { word: 'agreement', phonetic: '/əˈɡriːmənt/', pos: 'n.', meaning: '协议', eg: 'Sign agreement.', trans: '签署协议。', coll: 'reach agreement', root: 'agree + -ment' },
  { word: 'agriculture', phonetic: '/ˈæɡrɪkʌltʃər/', pos: 'n.', meaning: '农业', eg: 'Modern agriculture.', trans: '现代农业。', coll: 'agricultural products', root: '拉丁语 agricultura' },
  { word: 'ahead', phonetic: '/əˈhed/', pos: 'adv.', meaning: '向前', eg: 'Go ahead.', trans: '继续。', coll: 'ahead of time', root: '古英语 æhæfd' },
  { word: 'aid', phonetic: '/eɪd/', pos: 'n.', meaning: '援助', eg: 'Provide aid.', trans: '提供援助。', coll: 'foreign aid', root: '古英语 aid' },
  { word: 'aim', phonetic: '/eɪm/', pos: 'n.', meaning: '目标', eg: 'What is your aim?', trans: '你的目标？', coll: 'aim at', root: '古法语 aesmer' },
  { word: 'air', phonetic: '/eər/', pos: 'n.', meaning: '空气', eg: 'Fresh air.', trans: '新鲜空气。', coll: 'on the air', root: '古英语 aer' },
  { word: 'aircraft', phonetic: '/ˈeəkrɑːft/', pos: 'n.', meaning: '飞机', eg: 'Aircraft took off.', trans: '飞机起飞。', coll: 'military aircraft', root: 'air + craft' },
  { word: 'airport', phonetic: '/ˈeəpɔːrt/', pos: 'n.', meaning: '机场', eg: 'At the airport.', trans: '在机场。', coll: 'international airport', root: 'air + port' },
  { word: 'alarm', phonetic: '/əˈlɑːrm/', pos: 'n.', meaning: '警报', eg: 'Alarm went off.', trans: '警报响了。', coll: 'fire alarm', root: '意大利语 allarme' },
  { word: 'album', phonetic: '/ˈælbəm/', pos: 'n.', meaning: '相册', eg: 'Photo album.', trans: '相册。', coll: 'music album', root: '拉丁语 album' },
  { word: 'alcohol', phonetic: '/ˈælkəhɔːl/', pos: 'n.', meaning: '酒精', eg: 'Drink in moderation.', trans: '适量饮酒。', coll: 'alcohol content', root: '阿拉伯语 al-kuhl' },
  { word: 'alert', phonetic: '/əˈlɜːrt/', pos: 'adj.', meaning: '警觉的', eg: 'Stay alert.', trans: '保持警觉。', coll: 'alert to', root: '意大利语 allerta' },
  { word: 'alien', phonetic: '/ˈeɪliən/', pos: 'adj.', meaning: '外国的', eg: 'Alien resident.', trans: '外籍居民。', coll: 'alien species', root: '拉丁语 alienus' },
  { word: 'alike', phonetic: '/əˈlaɪk/', pos: 'adj.', meaning: '相似的', eg: 'Look alike.', trans: '看起来像。', coll: 'think alike', root: 'a- + like' },
  { word: 'alive', phonetic: '/əˈlaɪv/', pos: 'adj.', meaning: '活着的', eg: 'Still alive.', trans: '还活着。', coll: 'alive and well', root: '古英语 alif' },
  { word: 'all', phonetic: '/ɔːl/', pos: 'adj.', meaning: '全部', eg: 'All students.', trans: '所有学生。', coll: 'all over', root: '古英语 eall' },
  { word: 'allow', phonetic: '/əˈlaʊ/', pos: 'v.', meaning: '允许', eg: 'Allow me.', trans: '允许我。', coll: 'allow to', root: '古英语 allowan' },
  { word: 'almost', phonetic: '/ˈɔːlmoʊst/', pos: 'adv.', meaning: '几乎', eg: 'Almost done.', trans: '几乎完成。', coll: 'almost never', root: 'all + most' },
  { word: 'alone', phonetic: '/əˈloʊn/', pos: 'adj.', meaning: '单独的', eg: 'Live alone.', trans: '独自生活。', coll: 'leave alone', root: '古英语 all an' },
  { word: 'along', phonetic: '/əˈlɔːŋ/', pos: 'prep.', meaning: '沿着', eg: 'Walk along.', trans: '沿着走。', coll: 'along with', root: '古英语 andlang' },
  { word: 'aloud', phonetic: '/əˈlaʊd/', pos: 'adv.', meaning: '大声地', eg: 'Read aloud.', trans: '大声朗读。', coll: 'think aloud', root: 'a- + loud' },
  { word: 'alphabet', phonetic: '/ˈælfəbet/', pos: 'n.', meaning: '字母表', eg: 'Learn alphabet.', trans: '学习字母表。', coll: 'English alphabet', root: '希腊语 alpha+beta' },
  { word: 'already', phonetic: '/ɔːlˈredi/', pos: 'adv.', meaning: '已经', eg: 'Already done.', trans: '已经完成。', coll: 'almost already', root: 'all + ready' },
  { word: 'also', phonetic: '/ˈɔːlsoʊ/', pos: 'adv.', meaning: '也', eg: 'Also like music.', trans: '也喜欢音乐。', coll: 'not only...but also', root: '古英语 eallswa' },
  { word: 'alter', phonetic: '/ˈɔːltər/', pos: 'v.', meaning: '改变', eg: 'Alter plan.', trans: '修改计划。', coll: 'alter opinion', root: '拉丁语 alter' },
  { word: 'alternative', phonetic: '/ɔːlˈtɜːrnətɪv/', pos: 'adj.', meaning: '替代的', eg: 'Alternative solution.', trans: '替代方案。', coll: 'alternative energy', root: 'alter + native' },
  { word: 'although', phonetic: '/ɔːlˈðoʊ/', pos: 'conj.', meaning: '虽然', eg: 'Although it rained.', trans: '虽然下雨了。', coll: 'although...yet', root: 'all + though' },
  { word: 'altogether', phonetic: '/ˌɔːltəˈɡeðər/', pos: 'adv.', meaning: '总共', eg: 'Altogether $100.', trans: '总共100美元。', coll: 'altogether different', root: 'all together' },
  { word: 'always', phonetic: '/ˈɔːlweɪz/', pos: 'adv.', meaning: '总是', eg: 'Always early.', trans: '总是早到。', coll: 'always remember', root: 'all + ways' },
  { word: 'amazing', phonetic: '/əˈmeɪzɪŋ/', pos: 'adj.', meaning: '令人惊讶的', eg: 'Amazing view.', trans: '惊人景色。', coll: 'amazing discovery', root: 'amaze + -ing' },
  { word: 'ambition', phonetic: '/æmˈbɪʃn/', pos: 'n.', meaning: '抱负', eg: 'Great ambition.', trans: '远大抱负。', coll: 'personal ambition', root: '拉丁语 ambitio' },
  { word: 'ambitious', phonetic: '/æmˈbɪʃəs/', pos: 'adj.', meaning: '有抱负的', eg: 'Ambitious plan.', trans: '雄心勃勃的计划。', coll: 'highly ambitious', root: 'ambition + -ous' },
  { word: 'among', phonetic: '/əˈmʌŋ/', pos: 'prep.', meaning: '在...之中', eg: 'Among friends.', trans: '在朋友中。', coll: 'among others', root: '古英语 amang' },
  { word: 'amount', phonetic: '/əˈmaʊnt/', pos: 'n.', meaning: '数量', eg: 'Large amount.', trans: '大量。', coll: 'amount of', root: '拉丁语 amonere' },
  { word: 'analyse', phonetic: '/ˈænəlaɪz/', pos: 'v.', meaning: '分析', eg: 'Analyse data.', trans: '分析数据。', coll: 'analyse results', root: '希腊语 analyein' },
  { word: 'analysis', phonetic: '/əˈnæləsɪs/', pos: 'n.', meaning: '分析', eg: 'Data analysis.', trans: '数据分析。', coll: 'market analysis', root: '希腊语 analusis' },
  { word: 'ancestor', phonetic: '/ˈænsestər/', pos: 'n.', meaning: '祖先', eg: 'Our ancestors.', trans: '我们的祖先。', coll: 'common ancestor', root: '拉丁语 antecessor' },
  { word: 'ancient', phonetic: '/ˈeɪnʃənt/', pos: 'adj.', meaning: '古代的', eg: 'Ancient history.', trans: '古代历史。', coll: 'ancient ruins', root: '拉丁语 antiquus' },
  { word: 'and', phonetic: '/ænd/', pos: 'conj.', meaning: '和', eg: 'You and me.', trans: '你和我。', coll: 'and so on', root: '古英语 and' },
  { word: 'anger', phonetic: '/ˈæŋɡər/', pos: 'n.', meaning: '愤怒', eg: 'Hide anger.', trans: '隐藏愤怒。', coll: 'show anger', root: '古英语 angr' },
  { word: 'angle', phonetic: '/ˈæŋɡl/', pos: 'n.', meaning: '角度', eg: 'Right angle.', trans: '直角。', coll: 'at an angle', root: '拉丁语 angulus' },
  { word: 'angry', phonetic: '/ˈæŋɡri/', pos: 'adj.', meaning: '生气的', eg: 'Looks angry.', trans: '看起来生气。', coll: 'be angry with', root: 'anger + -y' },
  { word: 'animal', phonetic: '/ˈænɪml/', pos: 'n.', meaning: '动物', eg: 'Wild animal.', trans: '野生动物。', coll: 'domestic animal', root: '拉丁语 animalis' },
  { word: 'announce', phonetic: '/əˈnaʊns/', pos: 'v.', meaning: '宣布', eg: 'Announce winner.', trans: '宣布获胜者。', coll: 'announce decision', root: '拉丁语 annunciare' },
  { word: 'announcement', phonetic: '/əˈnaʊnsmənt/', pos: 'n.', meaning: '公告', eg: 'Read announcement.', trans: '阅读公告。', coll: 'official announcement', root: 'announce + -ment' },
  { word: 'annoy', phonetic: '/əˈnɔɪ/', pos: 'v.', meaning: '使烦恼', eg: 'Annoying behavior.', trans: '烦人的行为。', coll: 'be annoyed by', root: '古法语 anoier' },
  { word: 'annual', phonetic: '/ˈænjuəl/', pos: 'adj.', meaning: '年度的', eg: 'Annual meeting.', trans: '年会。', coll: 'annual report', root: '拉丁语 annualis' },
  { word: 'another', phonetic: '/əˈnʌðər/', pos: 'adj.', meaning: '另一个', eg: 'Another chance.', trans: '再一次机会。', coll: 'one after another', root: 'an + other' },
  { word: 'answer', phonetic: '/ˈɑːnsər/', pos: 'n.', meaning: '回答', eg: 'Answer question.', trans: '回答问题。', coll: 'answer phone', root: '古英语 andswaru' },
  { word: 'ant', phonetic: '/ænt/', pos: 'n.', meaning: '蚂蚁', eg: 'An ant.', trans: '一只蚂蚁。', coll: 'ant colony', root: '古英语 æmette' },
  { word: 'anticipate', phonetic: '/ænˈtɪsɪpeɪt/', pos: 'v.', meaning: '预期', eg: 'Anticipate future.', trans: '预见未来。', coll: 'anticipate problems', root: '拉丁语 anticipare' },
  { word: 'anxiety', phonetic: '/æŋˈzaɪəti/', pos: 'n.', meaning: '焦虑', eg: 'Feel anxiety.', trans: '感到焦虑。', coll: 'anxiety about', root: '拉丁语 anxietas' },
  { word: 'anxious', phonetic: '/ˈæŋkʃəs/', pos: 'adj.', meaning: '焦虑的', eg: 'Anxious to leave.', trans: '急于离开。', coll: 'feel anxious', root: 'anxiety + -ous' },
  { word: 'any', phonetic: '/ˈeni/', pos: 'adj.', meaning: '任何', eg: 'Any questions?', trans: '有问题吗？', coll: 'any time', root: '古英语 ænig' },
  { word: 'anybody', phonetic: '/ˈenibʌdi/', pos: 'pron.', meaning: '任何人', eg: 'Anybody can do.', trans: '任何人都能做。', coll: 'anybody else', root: 'any + body' },
  { word: 'anyone', phonetic: '/ˈeniwʌn/', pos: 'pron.', meaning: '任何人', eg: 'Is anyone here?', trans: '有人在吗？', coll: 'anyone else', root: 'any + one' },
  { word: 'anything', phonetic: '/ˈeniθɪŋ/', pos: 'pron.', meaning: '任何事', eg: 'Want anything?', trans: '想要什么？', coll: 'anything else', root: 'any + thing' },
  { word: 'anyway', phonetic: '/ˈeniweɪ/', pos: 'adv.', meaning: '无论如何', eg: 'Anyway, we tried.', trans: '无论如何，我们试过了。', coll: 'anyway you look', root: 'any + way' },
  { word: 'anywhere', phonetic: '/ˈeniwer/', pos: 'adv.', meaning: '任何地方', eg: 'Go anywhere.', trans: '去任何地方。', coll: 'anywhere else', root: 'any + where' },
  { word: 'apart', phonetic: '/əˈpɑːrt/', pos: 'adv.', meaning: '分开', eg: 'Stand apart.', trans: '站开。', coll: 'apart from', root: 'a- + part' },
  { word: 'apartment', phonetic: '/əˈpɑːrtmənt/', pos: 'n.', meaning: '公寓', eg: 'Live in apartment.', trans: '住在公寓。', coll: 'apartment building', root: 'apart + -ment' },
  { word: 'apologize', phonetic: '/əˈpɑːlədʒaɪz/', pos: 'v.', meaning: '道歉', eg: 'Apologize to her.', trans: '向她道歉。', coll: 'apologize for', root: '希腊语 apologia' },
  { word: 'apology', phonetic: '/əˈpɑːlədʒi/', pos: 'n.', meaning: '道歉', eg: 'Make apology.', trans: '道歉。', coll: 'offer apology', root: '希腊语 apologia' },
  { word: 'apparent', phonetic: '/əˈpærənt/', pos: 'adj.', meaning: '明显的', eg: 'Apparent reason.', trans: '明显原因。', coll: 'become apparent', root: '拉丁语 apparens' },
  { word: 'apparently', phonetic: '/əˈpærəntli/', pos: 'adv.', meaning: '显然', eg: 'Apparently forgot.', trans: '显然忘了。', coll: 'apparently true', root: 'apparent + -ly' },
  { word: 'appeal', phonetic: '/əˈpiːl/', pos: 'n.', meaning: '呼吁', eg: 'Make appeal.', trans: '呼吁。', coll: 'appeal to', root: '拉丁语 appellare' },
  { word: 'appear', phonetic: '/əˈpɪr/', pos: 'v.', meaning: '出现', eg: 'Appear suddenly.', trans: '突然出现。', coll: 'appear to be', root: '拉丁语 apparere' },
  { word: 'appearance', phonetic: '/əˈpɪərəns/', pos: 'n.', meaning: '外观', eg: 'Appearance matters.', trans: '外观很重要。', coll: 'make appearance', root: 'appear + -ance' },
  { word: 'appendix', phonetic: '/əˈpendɪks/', pos: 'n.', meaning: '附录', eg: 'Check appendix.', trans: '查看附录。', coll: 'appendix to', root: '拉丁语 appendix' },
  { word: 'appetite', phonetic: '/ˈæpɪtaɪt/', pos: 'n.', meaning: '食欲', eg: 'Good appetite.', trans: '胃口好。', coll: 'lose appetite', root: '拉丁语 appetitus' },
  { word: 'applaud', phonetic: '/əˈplɔːd/', pos: 'v.', meaning: '鼓掌', eg: 'Audience applauded.', trans: '观众鼓掌。', coll: 'applaud for', root: '拉丁语 applaudere' },
  { word: 'apple', phonetic: '/ˈæpl/', pos: 'n.', meaning: '苹果', eg: 'An apple a day.', trans: '一天一个苹果。', coll: 'apple pie', root: '古英语 æppel' },
  { word: 'application', phonetic: '/ˌæplɪˈkeɪʃn/', pos: 'n.', meaning: '应用', eg: 'Submit application.', trans: '提交申请。', coll: 'job application', root: 'apply + -cation' },
  { word: 'apply', phonetic: '/əˈplaɪ/', pos: 'v.', meaning: '应用', eg: 'Apply for job.', trans: '申请工作。', coll: 'apply to', root: '拉丁语 applicare' },
  { word: 'appoint', phonetic: '/əˈpɔɪnt/', pos: 'v.', meaning: '任命', eg: 'Appoint manager.', trans: '任命经理。', coll: 'appoint as', root: '拉丁语 appointare' },
  { word: 'appointment', phonetic: '/əˈpɔɪntmənt/', pos: 'n.', meaning: '约会', eg: 'Have appointment.', trans: '有约会。', coll: 'make appointment', root: 'appoint + -ment' },
  { word: 'appreciate', phonetic: '/əˈpriːʃieɪt/', pos: 'v.', meaning: '欣赏', eg: 'Appreciate help.', trans: '感谢帮助。', coll: 'appreciate art', root: '拉丁语 appretiatus' },
  { word: 'approach', phonetic: '/əˈproʊtʃ/', pos: 'n.', meaning: '方法', eg: 'New approach.', trans: '新方法。', coll: 'approach to', root: '拉丁语 appropiare' },
  { word: 'appropriate', phonetic: '/əˈproʊpriət/', pos: 'adj.', meaning: '适当的', eg: 'Appropriate action.', trans: '适当行动。', coll: 'appropriate for', root: '拉丁语 appropriatus' },
  { word: 'approval', phonetic: '/əˈpruːvl/', pos: 'n.', meaning: '批准', eg: 'Get approval.', trans: '获得批准。', coll: 'give approval', root: 'approve + -al' },
  { word: 'approve', phonetic: '/əˈpruːv/', pos: 'v.', meaning: '批准', eg: 'Approve plan.', trans: '批准计划。', coll: 'approve of', root: '拉丁语 approbare' },
  { word: 'approximate', phonetic: '/əˈprɑːksɪmət/', pos: 'adj.', meaning: '近似的', eg: 'Approximate value.', trans: '近似值。', coll: 'approximate to', root: '拉丁语 approximatus' },
  { word: 'approximately', phonetic: '/əˈprɑːksɪmətli/', pos: 'adv.', meaning: '大约', eg: 'Approximately 100.', trans: '大约100。', coll: 'approximately equal', root: 'approximate + -ly' },
  { word: 'arbitrary', phonetic: '/ˈɑːrbɪtreri/', pos: 'adj.', meaning: '任意的', eg: 'Arbitrary decision.', trans: '武断决定。', coll: 'arbitrary rule', root: '拉丁语 arbitrarius' },
  { word: 'arch', phonetic: '/ɑːrtʃ/', pos: 'n.', meaning: '拱门', eg: 'Arch of bridge.', trans: '桥拱。', coll: 'arch bridge', root: '拉丁语 arcus' },
  { word: 'architecture', phonetic: '/ˈɑːrkɪtektʃər/', pos: 'n.', meaning: '建筑', eg: 'Modern architecture.', trans: '现代建筑。', coll: 'classical architecture', root: '希腊语 architekton' },
  { word: 'area', phonetic: '/ˈeriə/', pos: 'n.', meaning: '区域', eg: 'Urban area.', trans: '城市区域。', coll: 'rural area', root: '拉丁语 area' },
  { word: 'argue', phonetic: '/ˈɑːrɡjuː/', pos: 'v.', meaning: '争论', eg: 'Argue about politics.', trans: '争论政治。', coll: 'argue for', root: '拉丁语 arguere' },
  { word: 'argument', phonetic: '/ˈɑːrɡjumənt/', pos: 'n.', meaning: '论点', eg: 'Strong argument.', trans: '有力论点。', coll: 'valid argument', root: 'argue + -ment' },
  { word: 'arise', phonetic: '/əˈraɪz/', pos: 'v.', meaning: '出现', eg: 'Problem arose.', trans: '问题出现。', coll: 'arise from', root: '古英语 arisan' },
  { word: 'arm', phonetic: '/ɑːrm/', pos: 'n.', meaning: '手臂', eg: 'Strong arms.', trans: '强壮手臂。', coll: 'arm in arm', root: '古英语 earm' },
  { word: 'army', phonetic: '/ˈɑːrmi/', pos: 'n.', meaning: '军队', eg: 'Join army.', trans: '参军。', coll: 'army base', root: 'arm + -y' },
  { word: 'around', phonetic: '/əˈraʊnd/', pos: 'prep.', meaning: '围绕', eg: 'Look around.', trans: '环顾。', coll: 'around corner', root: '古英语 aran' },
  { word: 'arrange', phonetic: '/əˈreɪndʒ/', pos: 'v.', meaning: '安排', eg: 'Arrange meeting.', trans: '安排会议。', coll: 'arrange for', root: '古法语 arangier' },
  { word: 'arrangement', phonetic: '/əˈreɪndʒmənt/', pos: 'n.', meaning: '安排', eg: 'Make arrangements.', trans: '做出安排。', coll: 'seating arrangement', root: 'arrange + -ment' },
  { word: 'arrest', phonetic: '/əˈrest/', pos: 'v.', meaning: '逮捕', eg: 'Make arrest.', trans: '逮捕。', coll: 'under arrest', root: '拉丁语 arrestare' },
  { word: 'arrival', phonetic: '/əˈraɪvl/', pos: 'n.', meaning: '到达', eg: 'On arrival.', trans: '到达时。', coll: 'arrival time', root: 'arrive + -al' },
  { word: 'arrive', phonetic: '/əˈraɪv/', pos: 'v.', meaning: '到达', eg: 'Arrive at station.', trans: '到达车站。', coll: 'arrive in', root: '拉丁语 arrivare' },
  { word: 'arrow', phonetic: '/ˈæroʊ/', pos: 'n.', meaning: '箭', eg: 'Shoot arrow.', trans: '射箭。', coll: 'bow and arrow', root: '古英语 arwe' },
  { word: 'art', phonetic: '/ɑːrt/', pos: 'n.', meaning: '艺术', eg: 'Study art.', trans: '学习艺术。', coll: 'fine art', root: '拉丁语 ars' },
  { word: 'article', phonetic: '/ˈɑːrtɪkl/', pos: 'n.', meaning: '文章', eg: 'Read article.', trans: '阅读文章。', coll: 'newspaper article', root: '拉丁语 articulus' },
  { word: 'artificial', phonetic: '/ˌɑːrtɪˈfɪʃl/', pos: 'adj.', meaning: '人工的', eg: 'Artificial intelligence.', trans: '人工智能。', coll: 'artificial flowers', root: '拉丁语 artificialis' },
  { word: 'artist', phonetic: '/ˈɑːrtɪst/', pos: 'n.', meaning: '艺术家', eg: 'Famous artist.', trans: '著名艺术家。', coll: 'pop artist', root: 'art + -ist' },
  { word: 'as', phonetic: '/æz/', pos: 'conj.', meaning: '作为', eg: 'As a student.', trans: '作为学生。', coll: 'as soon as', root: '古英语 swa' },
  { word: 'ash', phonetic: '/æʃ/', pos: 'n.', meaning: '灰', eg: 'Turned to ash.', trans: '变成灰烬。', coll: 'volcanic ash', root: '古英语 æsc' },
  { word: 'ashamed', phonetic: '/əˈʃeɪmd/', pos: 'adj.', meaning: '羞愧的', eg: 'Felt ashamed.', trans: '感到羞愧。', coll: 'be ashamed of', root: '古英语 asceamian' },
  { word: 'aside', phonetic: '/əˈsaɪd/', pos: 'adv.', meaning: '在旁边', eg: 'Put aside.', trans: '放在一边。', coll: 'aside from', root: 'a- + side' },
  { word: 'ask', phonetic: '/æsk/', pos: 'v.', meaning: '问', eg: 'Ask question.', trans: '问问题。', coll: 'ask for', root: '古英语 ascian' },
  { word: 'asleep', phonetic: '/əˈsliːp/', pos: 'adj.', meaning: '睡着的', eg: 'Fall asleep.', trans: '睡着。', coll: 'fast asleep', root: 'a- + sleep' },
  { word: 'aspect', phonetic: '/ˈæspekt/', pos: 'n.', meaning: '方面', eg: 'All aspects.', trans: '各个方面。', coll: 'important aspect', root: '拉丁语 aspectus' },
  { word: 'assemble', phonetic: '/əˈsembəl/', pos: 'v.', meaning: '组装', eg: 'Assemble parts.', trans: '组装零件。', coll: 'assemble team', root: '拉丁语 assembrare' },
  { word: 'assembly', phonetic: '/əˈsembli/', pos: 'n.', meaning: '组装', eg: 'Assembly line.', trans: '生产线。', coll: 'general assembly', root: 'assemble + -y' },
  { word: 'assert', phonetic: '/əˈsɜːrt/', pos: 'v.', meaning: '断言', eg: 'Assert innocence.', trans: '宣称无罪。', coll: 'assert oneself', root: '拉丁语 asserere' },
  { word: 'assessment', phonetic: '/əˈsesmənt/', pos: 'n.', meaning: '评估', eg: 'Make assessment.', trans: '进行评估。', coll: 'performance assessment', root: 'assess + -ment' },
  { word: 'assess', phonetic: '/əˈses/', pos: 'v.', meaning: '评估', eg: 'Assess situation.', trans: '评估情况。', coll: 'assess damage', root: '拉丁语 assessare' },
  { word: 'asset', phonetic: '/ˈæset/', pos: 'n.', meaning: '资产', eg: 'Valuable asset.', trans: '宝贵资产。', coll: 'asset management', root: '拉丁语 adesse' },
  { word: 'assign', phonetic: '/əˈsaɪn/', pos: 'v.', meaning: '分配', eg: 'Assign tasks.', trans: '分配任务。', coll: 'assign to', root: '拉丁语 assignare' },
  { word: 'assignment', phonetic: '/əˈsaɪnmənt/', pos: 'n.', meaning: '作业', eg: 'Complete assignment.', trans: '完成作业。', coll: 'homework assignment', root: 'assign + -ment' },
  { word: 'assist', phonetic: '/əˈsɪst/', pos: 'v.', meaning: '协助', eg: 'Assist customer.', trans: '协助顾客。', coll: 'assist with', root: '拉丁语 assistere' },
  { word: 'assistance', phonetic: '/əˈsɪstəns/', pos: 'n.', meaning: '援助', eg: 'Provide assistance.', trans: '提供援助。', coll: 'financial assistance', root: 'assist + -ance' },
  { word: 'assistant', phonetic: '/əˈsɪstənt/', pos: 'n.', meaning: '助手', eg: 'Teaching assistant.', trans: '助教。', coll: 'personal assistant', root: 'assist + -ant' },
  { word: 'associate', phonetic: '/əˈsoʊʃieɪt/', pos: 'v.', meaning: '关联', eg: 'Associate with friends.', trans: '与朋友交往。', coll: 'associate with', root: '拉丁语 associatus' },
  { word: 'association', phonetic: '/əˌsoʊʃiˈeɪʃn/', pos: 'n.', meaning: '协会', eg: 'Join association.', trans: '加入协会。', coll: 'trade association', root: 'associate + -ation' },
  { word: 'assume', phonetic: '/əˈsuːm/', pos: 'v.', meaning: '假设', eg: 'Assume worst.', trans: '做最坏假设。', coll: 'assume responsibility', root: '拉丁语 assumere' },
  { word: 'assumption', phonetic: '/əˈsʌmpʃn/', pos: 'n.', meaning: '假设', eg: 'Based on assumption.', trans: '基于假设。', coll: 'wrong assumption', root: 'assume + -ption' },
  { word: 'assure', phonetic: '/əˈʃʊr/', pos: 'v.', meaning: '保证', eg: 'Assure you.', trans: '向你保证。', coll: 'assure of', root: '法语 assurer' },
  { word: 'astonish', phonetic: '/əˈstɑːnɪʃ/', pos: 'v.', meaning: '使惊讶', eg: 'Astonished everyone.', trans: '让所有人惊讶。', coll: 'be astonished at', root: '古法语 astonir' },
  { word: 'at', phonetic: '/æt/', pos: 'prep.', meaning: '在', eg: 'At home.', trans: '在家。', coll: 'at school', root: '古英语 æt' },
  { word: 'atmosphere', phonetic: '/ˈætməsfɪr/', pos: 'n.', meaning: '气氛', eg: 'Tense atmosphere.', trans: '紧张气氛。', coll: 'family atmosphere', root: '希腊语 atmos + sphaira' },
  { word: 'atom', phonetic: '/ˈætəm/', pos: 'n.', meaning: '原子', eg: 'Very small atom.', trans: '非常小的原子。', coll: 'atomic energy', root: '希腊语 atomos' },
  { word: 'attach', phonetic: '/əˈtætʃ/', pos: 'v.', meaning: '附加', eg: 'Attach document.', trans: '附上文件。', coll: 'attach to', root: '拉丁语 attacare' },
  { word: 'attack', phonetic: '/əˈtæk/', pos: 'v.', meaning: '攻击', eg: 'Launch attack.', trans: '发动攻击。', coll: 'under attack', root: '古法语 atacquer' },
  { word: 'attempt', phonetic: '/əˈtempt/', pos: 'v.', meaning: '尝试', eg: 'Make attempt.', trans: '尝试。', coll: 'attempt to do', root: '拉丁语 attemptare' },
  { word: 'attend', phonetic: '/əˈtend/', pos: 'v.', meaning: '参加', eg: 'Attend meeting.', trans: '参加会议。', coll: 'attend to', root: '拉丁语 attendere' },
  { word: 'attention', phonetic: '/əˈtenʃn/', pos: 'n.', meaning: '注意', eg: 'Pay attention.', trans: '注意。', coll: 'draw attention', root: 'attend + -tion' },
  { word: 'attractive', phonetic: '/əˈtræktɪv/', pos: 'adj.', meaning: '有吸引力的', eg: 'Very attractive.', trans: '非常有吸引力。', coll: 'attractive price', root: 'attract + -ive' },
  { word: 'attribute', phonetic: '/əˈtrɪbjuːt/', pos: 'v.', meaning: '归因', eg: 'Attribute to teamwork.', trans: '归因于团队合作。', coll: 'attribute to', root: '拉丁语 attribuere' },
  { word: 'audience', phonetic: '/ˈɔːdiəns/', pos: 'n.', meaning: '观众', eg: 'Large audience.', trans: '大量观众。', coll: 'target audience', root: '拉丁语 audientia' },
  { word: 'audio', phonetic: '/ˈɔːdiˌoʊ/', pos: 'adj.', meaning: '音频的', eg: 'Audio quality.', trans: '音频质量。', coll: 'audio book', root: '拉丁语 audire' },
  { word: 'audit', phonetic: '/ˈɔːdɪt/', pos: 'n.', meaning: '审计', eg: 'Conduct audit.', trans: '进行审计。', coll: 'financial audit', root: '拉丁语 audire' },
  { word: 'august', phonetic: '/ˈɔːɡəst/', pos: 'adj.', meaning: '威严的', eg: 'August person.', trans: '威严的人。', coll: 'August holiday', root: '拉丁语 augustus' },
  { word: 'aunt', phonetic: '/ɑːnt/', pos: 'n.', meaning: '阿姨', eg: 'My aunt.', trans: '我姑姑。', coll: 'aunt and uncle', root: '拉丁语 amita' },
  { word: 'author', phonetic: '/ˈɔːθər/', pos: 'n.', meaning: '作者', eg: 'Book author.', trans: '书的作者。', coll: 'famous author', root: '拉丁语 auctor' },
  { word: 'authority', phonetic: '/əˈθɔːrəti/', pos: 'n.', meaning: '权威', eg: 'Have authority.', trans: '有权威。', coll: 'in authority', root: 'author + -ity' },
  { word: 'automatic', phonetic: '/ˌɔːtəˈmætɪk/', pos: 'adj.', meaning: '自动的', eg: 'Automatic door.', trans: '自动门。', coll: 'automatic system', root: '希腊语 automatos' },
  { word: 'automobile', phonetic: '/ˈɔːtəməbiːl/', pos: 'n.', meaning: '汽车', eg: 'New automobile.', trans: '新车。', coll: 'automobile industry', root: 'auto- + mobile' },
  { word: 'autumn', phonetic: '/ˈɔːtəm/', pos: 'n.', meaning: '秋天', eg: 'Beautiful autumn.', trans: '美丽秋天。', coll: 'autumn leaves', root: '拉丁语 autumnus' },
  { word: 'available', phonetic: '/əˈveɪləbl/', pos: 'adj.', meaning: '可用的', eg: 'Is available?', trans: '可用吗？', coll: 'available for', root: '拉丁语 availabilis' },
  { word: 'average', phonetic: '/ˈævərɪdʒ/', pos: 'adj.', meaning: '平均的', eg: 'Average cost.', trans: '平均成本。', coll: 'on average', root: '阿拉伯语 awar' },
  { word: 'avoid', phonetic: '/əˈvɔɪd/', pos: 'v.', meaning: '避免', eg: 'Avoid mistakes.', trans: '避免错误。', coll: 'avoid doing', root: 'a- + void' },
  { word: 'awake', phonetic: '/əˈweɪk/', pos: 'adj.', meaning: '醒着的', eg: 'Stay awake.', trans: '保持清醒。', coll: 'awake sb.', root: '古英语 awaecan' },
  { word: 'award', phonetic: '/əˈwɔːrd/', pos: 'n.', meaning: '奖项', eg: 'Win award.', trans: '赢得奖项。', coll: 'award ceremony', root: '古英语 award' },
  { word: 'aware', phonetic: '/əˈwer/', pos: 'adj.', meaning: '意识到的', eg: 'Be aware.', trans: '意识到。', coll: 'make aware', root: '古英语 gewaer' },
  { word: 'away', phonetic: '/əˈweɪ/', pos: 'adv.', meaning: '离开', eg: 'Go away.', trans: '走开。', coll: 'far away', root: '古英语 aweg' },
  { word: 'awful', phonetic: '/ˈɔːfl/', pos: 'adj.', meaning: '糟糕的', eg: 'Awful day.', trans: '糟糕的一天。', coll: 'awful weather', root: 'awe + -ful' },
  { word: 'awkward', phonetic: '/ˈɔːkwərd/', pos: 'adj.', meaning: '尴尬的', eg: 'Awkward moment.', trans: '尴尬时刻。', coll: 'feel awkward', root: '古英语 awkeward' },
  { word: 'baby', phonetic: '/ˈbeɪbi/', pos: 'n.', meaning: '婴儿', eg: 'Crying baby.', trans: '哭泣的婴儿。', coll: 'baby boy', root: '古英语 babe' },
  { word: 'back', phonetic: '/bæk/', pos: 'n.', meaning: '背部', eg: 'Strong back.', trans: '强壮的背部。', coll: 'back to back', root: '古英语 bæc' },
  { word: 'background', phonetic: '/ˈbækɡraʊnd/', pos: 'n.', meaning: '背景', eg: 'White background.', trans: '白色背景。', coll: 'background music', root: 'back + ground' },
  { word: 'bad', phonetic: '/bæd/', pos: 'adj.', meaning: '坏的', eg: 'Bad weather.', trans: '坏天气。', coll: 'bad luck', root: '古英语 baed' },
  { word: 'bag', phonetic: '/bæɡ/', pos: 'n.', meaning: '包', eg: 'Carry bag.', trans: '拿包。', coll: 'school bag', root: '古英语 bagga' },
  { word: 'balance', phonetic: '/ˈbæləns/', pos: 'n.', meaning: '平衡', eg: 'Keep balance.', trans: '保持平衡。', coll: 'balance sheet', root: '拉丁语 bilanx' },
  { word: 'ball', phonetic: '/bɔːl/', pos: 'n.', meaning: '球', eg: 'Play ball.', trans: '玩球。', coll: 'football', root: '古英语 beall' },
  { word: 'ban', phonetic: '/bæn/', pos: 'v.', meaning: '禁止', eg: 'Ban smoking.', trans: '禁止吸烟。', coll: 'ban on', root: '古英语 bannan' },
  { word: 'band', phonetic: '/bænd/', pos: 'n.', meaning: '乐队', eg: 'Rock band.', trans: '摇滚乐队。', coll: 'band member', root: '古英语 bend' },
  { word: 'bank', phonetic: '/bæŋk/', pos: 'n.', meaning: '银行', eg: 'Go to bank.', trans: '去银行。', coll: 'central bank', root: '意大利语 banco' },
  { word: 'base', phonetic: '/beɪs/', pos: 'n.', meaning: '基础', eg: 'On base.', trans: '在基地。', coll: 'military base', root: '拉丁语 basis' },
  { word: 'basic', phonetic: '/ˈbeɪsɪk/', pos: 'adj.', meaning: '基本的', eg: 'Basic skills.', trans: '基本技能。', coll: 'basic knowledge', root: 'base + -ic' },
  { word: 'basis', phonetic: '/ˈbeɪsɪs/', pos: 'n.', meaning: '基础', eg: 'On the basis.', trans: '在此基础上。', coll: 'on the basis of', root: '希腊语 basis' },
  { word: 'basket', phonetic: '/ˈbæskɪt/', pos: 'n.', meaning: '篮子', eg: 'Picnic basket.', trans: '野餐篮。', coll: 'basket ball', root: '古英语 bæsket' },
  { word: 'bath', phonetic: '/bæθ/', pos: 'n.', meaning: '洗澡', eg: 'Take bath.', trans: '洗澡。', coll: 'bath room', root: '古英语 baeth' },
  { word: 'battery', phonetic: '/ˈbætəri/', pos: 'n.', meaning: '电池', eg: 'Car battery.', trans: '汽车电池。', coll: 'battery life', root: '拉丁语 batteria' },
  { word: 'battle', phonetic: '/ˈbætl/', pos: 'n.', meaning: '战斗', eg: 'Battle field.', trans: '战场。', coll: 'battle for', root: '古法语 bataille' },
  { word: 'be', phonetic: '/biː/', pos: 'v.', meaning: '是', eg: 'I am happy.', trans: '我很快乐。', coll: 'be happy', root: '古英语 beon' },
  { word: 'beach', phonetic: '/biːtʃ/', pos: 'n.', meaning: '海滩', eg: 'Go to beach.', trans: '去海滩。', coll: 'beach party', root: '古英语 bece' },
  { word: 'bear', phonetic: '/beər/', pos: 'v.', meaning: '忍受', eg: 'Can bear.', trans: '能忍受。', coll: 'bear with', root: '古英语 beran' },
  { word: 'beautiful', phonetic: '/ˈbjuːtɪfl/', pos: 'adj.', meaning: '美丽的', eg: 'Beautiful girl.', trans: '美丽的女孩。', coll: 'beautiful scenery', root: 'beauty + -ful' },
  { word: 'because', phonetic: '/bɪˈkɔːz/', pos: 'conj.', meaning: '因为', eg: 'Because I love it.', trans: '因为我喜欢。', coll: 'because of', root: '古英语 becaus' },
  { word: 'become', phonetic: '/bɪˈkʌm/', pos: 'v.', meaning: '成为', eg: 'Become successful.', trans: '变得成功。', coll: 'become famous', root: '古英语 becuman' },
  { word: 'bed', phonetic: '/bed/', pos: 'n.', meaning: '床', eg: 'Go to bed.', trans: '上床睡觉。', coll: 'bed room', root: '古英语 bedd' },
  { word: 'before', phonetic: '/bɪˈfɔːr/', pos: 'prep.', meaning: '在...之前', eg: 'Before dinner.', trans: '饭前。', coll: 'before long', root: '古英语 beforan' },
  { word: 'begin', phonetic: '/bɪˈɡɪn/', pos: 'v.', meaning: '开始', eg: 'Begin now.', trans: '现在开始。', coll: 'begin with', root: '古英语 beginnan' },
  { word: 'beginning', phonetic: '/bɪˈɡɪnɪŋ/', pos: 'n.', meaning: '开始', eg: 'At the beginning.', trans: '在开始。', coll: 'from beginning', root: 'begin + -ing' },
  { word: 'behind', phonetic: '/bɪˈhaɪnd/', pos: 'prep.', meaning: '在...后面', eg: 'Behind door.', trans: '在门后。', coll: 'fall behind', root: '古英语 behindan' },
  { word: 'believe', phonetic: '/bɪˈliːv/', pos: 'v.', meaning: '相信', eg: 'I believe you.', trans: '我相信你。', coll: 'believe in', root: '古英语 belȳfan' },
  { word: 'bell', phonetic: '/bel/', pos: 'n.', meaning: '铃', eg: 'Ring bell.', trans: '按铃。', coll: 'door bell', root: '古英语 bell' },
  { word: 'belong', phonetic: '/bɪˈlɔːŋ/', pos: 'v.', meaning: '属于', eg: 'Belong to me.', trans: '属于我。', coll: 'belong to', root: '古英语 belangian' },
  { word: 'below', phonetic: '/bɪˈloʊ/', pos: 'prep.', meaning: '在...下面', eg: 'Below zero.', trans: '零下。', coll: 'below average', root: '古英语 belawe' },
  { word: 'belt', phonetic: '/belt/', pos: 'n.', meaning: '腰带', eg: 'Leather belt.', trans: '皮带。', coll: 'seat belt', root: '古英语 belt' },
  { word: 'bench', phonetic: '/bentʃ/', pos: 'n.', meaning: '长椅', eg: 'Park bench.', trans: '公园长椅。', coll: 'work bench', root: '古英语 benc' },
  { word: 'bend', phonetic: '/bend/', pos: 'v.', meaning: '弯曲', eg: 'Bend down.', trans: '弯腰。', coll: 'bend over', root: '古英语 bendan' },
  { word: 'beneath', phonetic: '/bɪˈniːθ/', pos: 'prep.', meaning: '在...下方', eg: 'Beneath the table.', trans: '桌子下面。', coll: 'beneath notice', root: '古英语 beneoðan' },
  { word: 'benefit', phonetic: '/ˈbenɪfɪt/', pos: 'n.', meaning: '利益', eg: 'For your benefit.', trans: '为了你好。', coll: 'benefit from', root: '拉丁语 beneficium' },
  { word: 'bent', phonetic: '/bent/', pos: 'adj.', meaning: '弯曲的', eg: 'Bent tree.', trans: '弯曲的树。', coll: 'get bent', root: 'bend 的过去分词' },
  { word: 'beside', phonetic: '/bɪˈsaɪd/', pos: 'prep.', meaning: '在...旁边', eg: 'Beside me.', trans: '在我旁边。', coll: 'beside oneself', root: '古英语 be side' },
  { word: 'besides', phonetic: '/bɪˈsaɪdz/', pos: 'adv.', meaning: '此外', eg: 'Besides, I agree.', trans: '此外，我同意。', coll: 'besides that', root: 'beside + -s' },
  { word: 'best', phonetic: '/best/', pos: 'adj.', meaning: '最好的', eg: 'Best friend.', trans: '最好的朋友。', coll: 'do one\'s best', root: '古英语 betst' },
  { word: 'better', phonetic: '/ˈbetər/', pos: 'adj.', meaning: '更好的', eg: 'Better than.', trans: '比...更好。', coll: 'better off', root: '古英语 betera' },
  { word: 'between', phonetic: '/bɪˈtwiːn/', pos: 'prep.', meaning: '在...之间', eg: 'Between us.', trans: '在我们之间。', coll: 'between and', root: '古英语 betweonum' },
  { word: 'beyond', phonetic: '/bɪˈjɔːnd/', pos: 'prep.', meaning: '超过', eg: 'Beyond expectation.', trans: '超出预期。', coll: 'beyond doubt', root: '古英语 begeondan' },
  { word: 'big', phonetic: '/bɪɡ/', pos: 'adj.', meaning: '大的', eg: 'Big house.', trans: '大房子。', coll: 'big deal', root: '古英语 big' },
  { word: 'bill', phonetic: '/bɪl/', pos: 'n.', meaning: '账单', eg: 'Pay bill.', trans: '付账单。', coll: 'phone bill', root: '古英语 bill' },
  { word: 'billion', phonetic: '/ˈbɪljən/', pos: 'num.', meaning: '十亿', eg: 'One billion.', trans: '十亿。', coll: 'billion dollars', root: '拉丁语 bi- + million' },
  { word: 'bind', phonetic: '/baɪnd/', pos: 'v.', meaning: '捆绑', eg: 'Bind together.', trans: '绑在一起。', coll: 'bind up', root: '古英语 bindan' },
  { word: 'biology', phonetic: '/baɪˈɒlədʒi/', pos: 'n.', meaning: '生物学', eg: 'Study biology.', trans: '学习生物。', coll: 'molecular biology', root: '希腊语 bios + logos' },
  { word: 'bird', phonetic: '/bɜːrd/', pos: 'n.', meaning: '鸟', eg: 'Little bird.', trans: '小鸟。', coll: 'bird nest', root: '古英语 bird' },
  { word: 'birth', phonetic: '/bɜːrθ/', pos: 'n.', meaning: '出生', eg: 'Date of birth.', trans: '出生日期。', coll: 'give birth', root: '古英语 byrth' },
  { word: 'bit', phonetic: '/bɪt/', pos: 'n.', meaning: '一点', eg: 'A bit tired.', trans: '有点累。', coll: 'a bit of', root: '古英语 bite' },
  { word: 'black', phonetic: '/blæk/', pos: 'adj.', meaning: '黑色的', eg: 'Black cat.', trans: '黑猫。', coll: 'black coffee', root: '古英语 blæc' },
