const fs = require('fs');
const path = require('path');

const words = [
  { word: 'abandon', phonetic: '/əˈbændən/', pos: 'v.', meaning: '放弃；遗弃', eg: 'He abandoned his plan to travel abroad.', trans: '他放弃了出国旅行的计划。', coll: 'abandon one\'s plan/dream; with abandon', root: 'aban- (离开) + -don (给予)' },
  { word: 'ability', phonetic: '/əˈbɪləti/', pos: 'n.', meaning: '能力', eg: 'She has the ability to speak three languages.', trans: '她有能力说三种语言。', coll: 'have the ability to; ability to do', root: 'able (能够的) + -ity (名词后缀)' },
  { word: 'able', phonetic: '/ˈeɪbl/', pos: 'adj.', meaning: '能够的；有能力的', eg: 'I am able to finish this task on time.', trans: '我能够按时完成这项任务。', coll: 'be able to; able-bodied', root: '来自拉丁语 habilis (合适的)' },
  { word: 'about', phonetic: '/əˈbaʊt/', pos: 'prep./adv.', meaning: '关于；大约', eg: 'Tell me about your trip.', trans: '告诉我关于你的旅行。', coll: 'talk about; think about', root: '来自古英语 abutan (周围)' },
  { word: 'above', phonetic: '/əˈbʌv/', pos: 'prep./adv.', meaning: '在...上面', eg: 'The sun is above the mountain.', trans: '太阳在山的上方。', coll: 'above all; above average', root: '来自古英语 abufan (在上面)' },
  { word: 'abroad', phonetic: '/əˈbrɔːd/', pos: 'adv.', meaning: '在国外', eg: 'He went abroad to study.', trans: '他去国外学习了。', coll: 'go abroad; study abroad', root: 'a- (离开) + broad (宽阔的)' },
  { word: 'absence', phonetic: '/ˈæbsəns/', pos: 'n.', meaning: '缺席；缺乏', eg: 'His absence was noticed.', trans: '他的缺席引起了注意。', coll: 'absence of; in the absence of', root: 'absent (缺席的) + -ce (名词后缀)' },
  { word: 'absent', phonetic: '/ˈæbsənt/', pos: 'adj./v.', meaning: '缺席的；使缺席', eg: 'She was absent from school.', trans: '她没来上学。', coll: 'be absent from; absent oneself', root: 'abs- (离开) + -ent (形容词后缀)' },
  { word: 'absolute', phonetic: '/ˈæbsəluːt/', pos: 'adj.', meaning: '绝对的；完全的', eg: 'This is an absolute truth.', trans: '这是绝对真理。', coll: 'absolute value; absolute majority', root: 'abs- (完全) + solutus (松开的)' },
  { word: 'absorb', phonetic: '/əbˈsɔːrb/', pos: 'v.', meaning: '吸收；吸引', eg: 'Plants absorb water from the soil.', trans: '植物从土壤中吸收水分。', coll: 'absorb water; absorb knowledge', root: 'abs- (朝向) + sorbere (吸吮)' },
  { word: 'abstract', phonetic: '/ˈæbstrækt/', pos: 'adj./n.', meaning: '抽象的；摘要', eg: 'This is an abstract concept.', trans: '这是一个抽象概念。', coll: 'abstract art; abstract idea', root: 'abs- (离开) + trahere (拉)' },
  { word: 'academic', phonetic: '/ˌækəˈdemɪk/', pos: 'adj./n.', meaning: '学术的；学者', eg: 'He is an academic researcher.', trans: '他是一位学术研究者。', coll: 'academic research; academic year', root: '来自希腊语 akademeia (学院)' },
  { word: 'accept', phonetic: '/əkˈsept/', pos: 'v.', meaning: '接受；认可', eg: 'She accepted the invitation.', trans: '她接受了邀请。', coll: 'accept an invitation; accept responsibility', root: 'ac- (朝向) + capere (拿取)' },
  { word: 'access', phonetic: '/ˈækses/', pos: 'n./v.', meaning: '通道；访问', eg: 'Access to the building is restricted.', trans: '进入大楼受到限制。', coll: 'access to; have access', root: '来自拉丁语 accessus (接近)' },
  { word: 'accident', phonetic: '/ˈæksɪdənt/', pos: 'n.', meaning: '事故；意外', eg: 'There was a car accident.', trans: '发生了一起车祸。', coll: 'car accident; traffic accident', root: 'ac- (朝向) + cadere (落下)' },
  { word: 'accompany', phonetic: '/əˈkʌmpəni/', pos: 'v.', meaning: '陪伴；伴随', eg: 'She accompanied him to the hospital.', trans: '她陪他去了医院。', coll: 'accompany sb. to; be accompanied by', root: 'ac- (朝向) + compania (同伴)' },
  { word: 'accomplish', phonetic: '/əˈkɑːmplɪʃ/', pos: 'v.', meaning: '完成；实现', eg: 'He accomplished his goal.', trans: '他完成了他的目标。', coll: 'accomplish a task; accomplish one\'s goal', root: 'ac- (完全) + complere (填满)' },
  { word: 'according', phonetic: '/əˈkɔːrdɪŋ/', pos: 'prep.', meaning: '根据；按照', eg: 'According to the report.', trans: '根据报告。', coll: 'according to; according as', root: '来自拉丁语 accordare (使一致)' },
  { word: 'account', phonetic: '/əˈkaʊnt/', pos: 'n./v.', meaning: '账户；解释', eg: 'Open a bank account.', trans: '开一个银行账户。', coll: 'bank account; account for', root: 'ac- (朝向) + computare (计算)' },
  { word: 'accurate', phonetic: '/ˈækjərət/', pos: 'adj.', meaning: '准确的；精确的', eg: 'Give me an accurate report.', trans: '给我一份准确的报告。', coll: 'accurate information; accurate measurement', root: 'ac- (朝向) + curare (关心)' },
  { word: 'achieve', phonetic: '/əˈtʃiːv/', pos: 'v.', meaning: '实现；达到', eg: 'He achieved success.', trans: '他取得了成功。', coll: 'achieve success; achieve a goal', root: '来自拉丁语 achievre (完成)' },
  { word: 'achievement', phonetic: '/əˈtʃiːvmənt/', pos: 'n.', meaning: '成就；成绩', eg: 'This is a great achievement.', trans: '这是一项伟大的成就。', coll: 'academic achievement; personal achievement', root: 'achieve (实现) + -ment (名词后缀)' },
  { word: 'acknowledge', phonetic: '/əkˈnɑːlɪdʒ/', pos: 'v.', meaning: '承认；感谢', eg: 'He acknowledged the mistake.', trans: '他承认了错误。', coll: 'acknowledge a mistake; acknowledge receipt', root: 'ac- (朝向) + cognoscere (知道)' },
  { word: 'acquire', phonetic: '/əˈkwaɪər/', pos: 'v.', meaning: '获得；取得', eg: 'She acquired new skills.', trans: '她获得了新技能。', coll: 'acquire skills; acquire knowledge', root: 'ac- (朝向) + quaerere (寻求)' },
  { word: 'across', phonetic: '/əˈkrɔːs/', pos: 'prep./adv.', meaning: '穿过；横过', eg: 'Walk across the street.', trans: '穿过马路。', coll: 'across the street; come across', root: 'a- (朝向) + cross (十字)' },
  { word: 'action', phonetic: '/ˈækʃn/', pos: 'n.', meaning: '行动；动作', eg: 'Take action now.', trans: '现在采取行动。', coll: 'take action; action plan', root: '来自拉丁语 actio (行动)' },
  { word: 'active', phonetic: '/ˈæktɪv/', pos: 'adj.', meaning: '活跃的；积极的', eg: 'He is an active member.', trans: '他是一名活跃成员。', coll: 'active member; active participation', root: 'act (行动) + -ive (形容词后缀)' },
  { word: 'activity', phonetic: '/ækˈtɪvəti/', pos: 'n.', meaning: '活动；活力', eg: 'Outdoor activities are fun.', trans: '户外活动很有趣。', coll: 'outdoor activity; physical activity', root: 'active (活跃的) + -ity (名词后缀)' },
  { word: 'actual', phonetic: '/ˈæktʃuəl/', pos: 'adj.', meaning: '实际的；真实的', eg: 'The actual cost is higher.', trans: '实际成本更高。', coll: 'actual cost; actual situation', root: '来自拉丁语 actualis (行动的)' },
  { word: 'adapt', phonetic: '/əˈdæpt/', pos: 'v.', meaning: '适应；改编', eg: 'She adapted to the new environment.', trans: '她适应了新环境。', coll: 'adapt to; adapt from', root: 'ad- (朝向) + aptare (适合)' },
  { word: 'add', phonetic: '/æd/', pos: 'v.', meaning: '添加；增加', eg: 'Add some sugar.', trans: '加一些糖。', coll: 'add to; add up', root: '来自拉丁语 addere (添加)' },
  { word: 'addition', phonetic: '/əˈdɪʃn/', pos: 'n.', meaning: '添加；加法', eg: 'In addition, we need more time.', trans: '此外，我们需要更多时间。', coll: 'in addition; addition to', root: 'add (添加) + -ition (名词后缀)' },
  { word: 'additional', phonetic: '/əˈdɪʃənl/', pos: 'adj.', meaning: '额外的；附加的', eg: 'We need additional resources.', trans: '我们需要额外的资源。', coll: 'additional cost; additional information', root: 'addition (添加) + -al (形容词后缀)' },
  { word: 'address', phonetic: '/əˈdres/', pos: 'n./v.', meaning: '地址；演讲', eg: 'Please write your address.', trans: '请写下你的地址。', coll: 'home address; business address', root: 'ad- (朝向) + direcere (引导)' },
  { word: 'adequate', phonetic: '/ˈædɪkwət/', pos: 'adj.', meaning: '足够的；适当的', eg: 'We have adequate supplies.', trans: '我们有足够的供应。', coll: 'adequate time; adequate resources', root: '来自拉丁语 adequatus (相等的)' },
  { word: 'adjust', phonetic: '/əˈdʒʌst/', pos: 'v.', meaning: '调整；适应', eg: 'Adjust the temperature.', trans: '调整温度。', coll: 'adjust to; adjust for', root: 'ad- (朝向) + justus (正确的)' },
  { word: 'administration', phonetic: '/ədˌmɪnɪˈstreɪʃn/', pos: 'n.', meaning: '管理；行政', eg: 'The administration building.', trans: '行政大楼。', coll: 'public administration; school administration', root: 'administrate (管理) + -ion (名词后缀)' },
  { word: 'admire', phonetic: '/ədˈmaɪər/', pos: 'v.', meaning: '钦佩；赞赏', eg: 'I admire his courage.', trans: '我钦佩他的勇气。', coll: 'admire sb. for; admire greatly', root: 'ad- (朝向) + mirari (惊奇)' },
  { word: 'admission', phonetic: '/ədˈmɪʃn/', pos: 'n.', meaning: '承认；入场', eg: 'Admission is free.', trans: '免费入场。', coll: 'admission fee; admission ticket', root: 'ad- (朝向) + mittere (发送)' },
  { word: 'admit', phonetic: '/ədˈmɪt/', pos: 'v.', meaning: '承认；允许进入', eg: 'He admitted his mistake.', trans: '他承认了错误。', coll: 'admit a mistake; admit to', root: 'ad- (朝向) + mittere (发送)' },
  { word: 'adopt', phonetic: '/əˈdɑːpt/', pos: 'v.', meaning: '采用；收养', eg: 'The company adopted new policies.', trans: '公司采用了新政策。', coll: 'adopt a policy; adopt a child', root: '来自拉丁语 adoptare (选择)' },
  { word: 'advance', phonetic: '/ədˈvæns/', pos: 'v./n.', meaning: '前进；进展', eg: 'The army advanced forward.', trans: '军队向前推进。', coll: 'advance towards; in advance', root: '来自拉丁语 abante (在前)' },
  { word: 'advanced', phonetic: '/ədˈvænst/', pos: 'adj.', meaning: '先进的；高级的', eg: 'Advanced technology.', trans: '先进技术。', coll: 'advanced level; advanced course', root: 'advance (前进) + -ed (形容词后缀)' },
  { word: 'advantage', phonetic: '/ədˈvæntɪdʒ/', pos: 'n.', meaning: '优势；好处', eg: 'This is a great advantage.', trans: '这是一个很大的优势。', coll: 'take advantage of; competitive advantage', root: 'ad- (朝向) + vantus (在前)' },
  { word: 'adventure', phonetic: '/ədˈventʃər/', pos: 'n.', meaning: '冒险；奇遇', eg: 'Life is an adventure.', trans: '人生是一场冒险。', coll: 'adventure story; adventure travel', root: 'ad- (朝向) + ventura (运气)' },
  { word: 'advertise', phonetic: '/ˈædvərtaɪz/', pos: 'v.', meaning: '做广告；宣传', eg: 'We need to advertise our product.', trans: '我们需要为我们的产品做广告。', coll: 'advertise on TV; advertise for', root: '来自拉丁语 advertere (转向)' },
  { word: 'advice', phonetic: '/ədˈvaɪs/', pos: 'n.', meaning: '建议；忠告', eg: 'Give me some advice.', trans: '给我一些建议。', coll: 'give advice; take advice', root: '来自拉丁语 advidere (考虑)' },
  { word: 'advise', phonetic: '/ədˈvaɪz/', pos: 'v.', meaning: '建议；劝告', eg: 'I advise you to study.', trans: '我建议你学习。', coll: 'advise sb. to do; advise against', root: '来自拉丁语 advidere (考虑)' },
  { word: 'affair', phonetic: '/əˈfeər/', pos: 'n.', meaning: '事情；事务', eg: 'This is a private affair.', trans: '这是私事。', coll: 'private affair; public affairs', root: '来自拉丁语 adferre (带来)' },
  { word: 'affect', phonetic: '/əˈfekt/', pos: 'v.', meaning: '影响；感动', eg: 'The weather affects our mood.', trans: '天气影响我们的心情。', coll: 'affect sb. deeply; be affected by', root: '来自拉丁语 afficere (作用)' },
  { word: 'afford', phonetic: '/əˈfɔːrd/', pos: 'v.', meaning: '负担得起；提供', eg: 'We can afford a new car.', trans: '我们买得起一辆新车。', coll: 'afford to buy; cannot afford', root: '来自古英语 afordian (提供)' },
  { word: 'afraid', phonetic: '/əˈfreɪd/', pos: 'adj.', meaning: '害怕的；担心的', eg: 'I am afraid of dogs.', trans: '我害怕狗。', coll: 'be afraid of; I am afraid that', root: '来自古英语 afræd (受惊的)' },
  { word: 'after', phonetic: '/ˈɑːftər/', pos: 'prep./adv.', meaning: '在...之后', eg: 'After dinner, we watched TV.', trans: '晚饭后，我们看电视。', coll: 'after school; after work', root: '来自古英语 æfter (在后)' },
  { word: 'afternoon', phonetic: '/ˌæftərˈnuːn/', pos: 'n.', meaning: '下午', eg: 'See you in the afternoon.', trans: '下午见。', coll: 'in the afternoon; afternoon tea', root: 'after (之后) + noon (中午)' },
  { word: 'again', phonetic: '/əˈɡen/', pos: 'adv.', meaning: '再次；又', eg: 'Try again.', trans: '再试一次。', coll: 'again and again; once again', root: '来自古英语 agan (返回)' },
  { word: 'against', phonetic: '/əˈɡenst/', pos: 'prep.', meaning: '反对；靠着', eg: 'He is against the plan.', trans: '他反对这个计划。', coll: 'be against; against the wall', root: '来自古英语 ongean (相反)' },
  { word: 'age', phonetic: '/eɪdʒ/', pos: 'n./v.', meaning: '年龄；变老', eg: 'What is your age?', trans: '你几岁了？', coll: 'at the age of; old age', root: '来自拉丁语 aetas (时代)' },
  { word: 'agency', phonetic: '/ˈeɪdʒənsi/', pos: 'n.', meaning: '机构；代理', eg: 'An advertising agency.', trans: '一家广告公司。', coll: 'travel agency; government agency', root: 'agent (代理人) + -cy (名词后缀)' },
  { word: 'agent', phonetic: '/ˈeɪdʒənt/', pos: 'n.', meaning: '代理人；代理商', eg: 'He is my agent.', trans: '他是我的代理人。', coll: 'real estate agent; travel agent', root: '来自拉丁语 agens (行动者)' },
  { word: 'aggressive', phonetic: '/əˈɡresɪv/', pos: 'adj.', meaning: '侵略的；积极的', eg: 'He has an aggressive attitude.', trans: '他态度积极。', coll: 'aggressive behavior; aggressive marketing', root: 'aggress (侵略) + -ive (形容词后缀)' },
  { word: 'ago', phonetic: '/əˈɡoʊ/', pos: 'adv.', meaning: '以前', eg: 'I met him three years ago.', trans: '我三年前见过他。', coll: 'years ago; long ago', root: '来自古英语 agan (过去)' },
  { word: 'agree', phonetic: '/əˈɡriː/', pos: 'v.', meaning: '同意；赞成', eg: 'I agree with you.', trans: '我同意你的看法。', coll: 'agree with; agree on', root: '来自拉丁语 adgratus (感激的)' },
  { word: 'agreement', phonetic: '/əˈɡriːmənt/', pos: 'n.', meaning: '协议；同意', eg: 'Sign the agreement.', trans: '签署协议。', coll: 'reach an agreement; written agreement', root: 'agree (同意) + -ment (名词后缀)' },
  { word: 'agriculture', phonetic: '/ˈæɡrɪkʌltʃər/', pos: 'n.', meaning: '农业', eg: 'Agriculture is important.', trans: '农业很重要。', coll: 'modern agriculture; agricultural products', root: '来自拉丁语 agricultura (农业)' },
  { word: 'ahead', phonetic: '/əˈhed/', pos: 'adv.', meaning: '向前；提前', eg: 'Go ahead.', trans: '继续前进。', coll: 'ahead of time; go ahead', root: '来自古英语 æhæfd (在前)' },
  { word: 'aid', phonetic: '/eɪd/', pos: 'n./v.', meaning: '援助；帮助', eg: 'Provide aid to the poor.', trans: '向穷人提供援助。', coll: 'foreign aid; first aid', root: '来自古英语 aid (帮助)' },
  { word: 'aim', phonetic: '/eɪm/', pos: 'n./v.', meaning: '目标；瞄准', eg: 'What is your aim?', trans: '你的目标是什么？', coll: 'aim at; aim for', root: '来自古法语 aesmer (估计)' },
  { word: 'air', phonetic: '/eər/', pos: 'n./v.', meaning: '空气；广播', eg: 'The air is fresh.', trans: '空气很清新。', coll: 'fresh air; on the air', root: '来自古英语 aer (空气)' },
  { word: 'aircraft', phonetic: '/ˈeəkrɑːft/', pos: 'n.', meaning: '飞机；航空器', eg: 'The aircraft took off.', trans: '飞机起飞了。', coll: 'military aircraft; commercial aircraft', root: 'air (空气) + craft (工艺)' },
  { word: 'airport', phonetic: '/ˈeəpɔːrt/', pos: 'n.', meaning: '机场', eg: 'Meet me at the airport.', trans: '在机场接我。', coll: 'international airport; airport terminal', root: 'air (空中) + port (港口)' },
  { word: 'alarm', phonetic: '/əˈlɑːrm/', pos: 'n./v.', meaning: '警报；警告', eg: 'The alarm went off.', trans: '警报响了。', coll: 'fire alarm; alarm clock', root: '来自意大利语 allarme (警报)' },
  { word: 'album', phonetic: '/ˈælbəm/', pos: 'n.', meaning: '相册；专辑', eg: 'This is a photo album.', trans: '这是一本相册。', coll: 'photo album; music album', root: '来自拉丁语 album (白色)' },
  { word: 'alcohol', phonetic: '/ˈælkəhɔːl/', pos: 'n.', meaning: '酒精；酒', eg: 'Drink alcohol in moderation.', trans: '适量饮酒。', coll: 'alcohol content; alcohol abuse', root: '来自阿拉伯语 al-kuhl (精华)' },
  { word: 'alert', phonetic: '/əˈlɜːrt/', pos: 'adj./n.', meaning: '警觉的；警报', eg: 'Stay alert at all times.', trans: '时刻保持警觉。', coll: 'alert to; red alert', root: '来自意大利语 allerta (警惕)' },
  { word: 'alien', phonetic: '/ˈeɪliən/', pos: 'adj./n.', meaning: '外国的；外星人', eg: 'He is an alien resident.', trans: '他是外籍居民。', coll: 'alien species; illegal alien', root: '来自拉丁语 alienus (外国的)' },
  { word: 'alike', phonetic: '/əˈlaɪk/', pos: 'adj./adv.', meaning: '相似的；同样地', eg: 'They look alike.', trans: '他们看起来很像。', coll: 'look alike; think alike', root: 'a- (加强) + like (相似)' },
  { word: 'alive', phonetic: '/əˈlaɪv/', pos: 'adj.', meaning: '活着的；活跃的', eg: 'He is still alive.', trans: '他还活着。', coll: 'alive and well; keep alive', root: '来自古英语 alif (活着)' },
  { word: 'all', phonetic: '/ɔːl/', pos: 'adj./pron.', meaning: '全部；所有', eg: 'All students must attend.', trans: '所有学生必须参加。', coll: 'all over; all right', root: '来自古英语 eall (全部)' },
  { word: 'allow', phonetic: '/əˈlaʊ/', pos: 'v.', meaning: '允许；准许', eg: 'Allow me to help.', trans: '允许我帮忙。', coll: 'allow sb. to do; allow for', root: '来自古英语 allowan (认可)' },
  { word: 'almost', phonetic: '/ˈɔːlmoʊst/', pos: 'adv.', meaning: '几乎；差不多', eg: 'It is almost time.', trans: '差不多到时间了。', coll: 'almost never; almost always', root: 'all (全部) + most (最)' },
  { word: 'alone', phonetic: '/əˈloʊn/', pos: 'adj./adv.', meaning: '单独的；独自', eg: 'He lives alone.', trans: '他独自生活。', coll: 'leave alone; let alone', root: '来自古英语 all an (完全一个)' },
  { word: 'along', phonetic: '/əˈlɔːŋ/', pos: 'prep./adv.', meaning: '沿着；一起', eg: 'Walk along the street.', trans: '沿着街道走。', coll: 'along with; all along', root: '来自古英语 andlang (沿着)' },
  { word: 'aloud', phonetic: '/əˈlaʊd/', pos: 'adv.', meaning: '大声地；出声地', eg: 'Read the text aloud.', trans: '大声朗读课文。', coll: 'read aloud; think aloud', root: 'a- (加强) + loud (大声的)' },
  { word: 'alphabet', phonetic: '/ˈælfəbet/', pos: 'n.', meaning: '字母表', eg: 'Learn the alphabet.', trans: '学习字母表。', coll: 'English alphabet; Greek alphabet', root: '来自希腊语 alpha + beta' },
  { word: 'already', phonetic: '/ɔːlˈredi/', pos: 'adv.', meaning: '已经', eg: 'I have already finished.', trans: '我已经完成了。', coll: 'already done; almost already', root: 'all (全部) + ready (准备好)' },
  { word: 'also', phonetic: '/ˈɔːlsoʊ/', pos: 'adv.', meaning: '也；同样', eg: 'I also like music.', trans: '我也喜欢音乐。', coll: 'not only...but also; also known as', root: '来自古英语 eallswa (同样)' },
  { word: 'alter', phonetic: '/ˈɔːltər/', pos: 'v.', meaning: '改变；修改', eg: 'Alter the plan.', trans: '修改计划。', coll: 'alter course; alter opinion', root: '来自拉丁语 alter (其他)' },
  { word: 'alternative', phonetic: '/ɔːlˈtɜːrnətɪv/', pos: 'adj./n.', meaning: '替代的；选择', eg: 'There is an alternative solution.', trans: '有一个替代方案。', coll: 'alternative energy; have no alternative', root: 'alter (改变) + native (产生)' },
  { word: 'although', phonetic: '/ɔːlˈðoʊ/', pos: 'conj.', meaning: '虽然；尽管', eg: 'Although it rained, we went out.', trans: '虽然下雨了，我们还是出去了。', coll: 'although...yet; even although', root: 'all (全部) + though (虽然)' },
  { word: 'altogether', phonetic: '/ˌɔːltəˈɡeðər/', pos: 'adv.', meaning: '完全；总共', eg: 'Altogether, it cost $100.', trans: '总共花费了100美元。', coll: 'altogether different; not altogether', root: 'all together (全部一起)' },
  { word: 'always', phonetic: '/ˈɔːlweɪz/', pos: 'adv.', meaning: '总是；一直', eg: 'He always arrives early.', trans: '他总是早到。', coll: 'always remember; not always', root: 'all (全部) + ways (方式)' },
  { word: 'amazing', phonetic: '/əˈmeɪzɪŋ/', pos: 'adj.', meaning: '令人惊讶的', eg: 'What an amazing view!', trans: '多么令人惊叹的景色！', coll: 'amazing performance; amazing discovery', root: 'amaze (使惊讶) + -ing (形容词后缀)' },
  { word: 'ambition', phonetic: '/æmˈbɪʃn/', pos: 'n.', meaning: '野心；抱负', eg: 'He has great ambition.', trans: '他有远大的抱负。', coll: 'political ambition; personal ambition', root: '来自拉丁语 ambitio (渴望)' },
  { word: 'ambitious', phonetic: '/æmˈbɪʃəs/', pos: 'adj.', meaning: '有野心的；有抱负的', eg: 'She is an ambitious woman.', trans: '她是一个有抱负的女人。', coll: 'ambitious plan; highly ambitious', root: 'ambition (抱负) + -ous (形容词后缀)' },
  { word: 'among', phonetic: '/əˈmʌŋ/', pos: 'prep.', meaning: '在...之中', eg: 'Among the students.', trans: '在学生之中。', coll: 'among others; among friends', root: '来自古英语 amang (在中间)' },
  { word: 'amount', phonetic: '/əˈmaʊnt/', pos: 'n./v.', meaning: '数量；总计', eg: 'A large amount of money.', trans: '一大笔钱。', coll: 'amount of; amount to', root: '来自拉丁语 amonere (计算)' },
  { word: 'analyse', phonetic: '/ˈænəlaɪz/', pos: 'v.', meaning: '分析；解析', eg: 'Analyse the data.', trans: '分析数据。', coll: 'analyse results; analyse situation', root: '来自希腊语 analyein (解开)' },
  { word: 'analysis', phonetic: '/əˈnæləsɪs/', pos: 'n.', meaning: '分析；解析', eg: 'The analysis shows...', trans: '分析表明...', coll: 'data analysis; market analysis', root: '来自希腊语 analusis (解开)' },
  { word: 'ancestor', phonetic: '/ˈænsestər/', pos: 'n.', meaning: '祖先；祖宗', eg: 'Our ancestors came from China.', trans: '我们的祖先来自中国。', coll: 'common ancestor; direct ancestor', root: '来自拉丁语 antecessor (先驱)' },
  { word: 'ancient', phonetic: '/ˈeɪnʃənt/', pos: 'adj.', meaning: '古代的；古老的', eg: 'Ancient history.', trans: '古代历史。', coll: 'ancient civilization; ancient ruins', root: '来自拉丁语 antiquus (古老的)' },
  { word: 'and', phonetic: '/ænd/', pos: 'conj.', meaning: '和；与', eg: 'You and me.', trans: '你和我。', coll: 'and so on; and then', root: '来自古英语 and (和)' },
  { word: 'anger', phonetic: '/ˈæŋɡər/', pos: 'n./v.', meaning: '愤怒；激怒', eg: 'He could not hide his anger.', trans: '他无法掩饰他的愤怒。', coll: 'in anger; show anger', root: '来自古英语 angr (痛苦)' },
  { word: 'angle', phonetic: '/ˈæŋɡl/', pos: 'n./v.', meaning: '角度；钓鱼', eg: 'The angle of the roof.', trans: '屋顶的角度。', coll: 'right angle; at an angle', root: '来自拉丁语 angulus (角)' },
  { word: 'angry', phonetic: '/ˈæŋɡri/', pos: 'adj.', meaning: '生气的；愤怒的', eg: 'She looks angry.', trans: '她看起来很生气。', coll: 'be angry with; get angry', root: 'anger (愤怒) + -y (形容词后缀)' },
  { word: 'animal', phonetic: '/ˈænɪml/', pos: 'n.', meaning: '动物', eg: 'The zoo has many animals.', trans: '动物园有很多动物。', coll: 'wild animal; domestic animal', root: '来自拉丁语 animalis (有生命的)' },
  { word: 'announce', phonetic: '/əˈnaʊns/', pos: 'v.', meaning: '宣布；通知', eg: 'Announce the winner.', trans: '宣布获胜者。', coll: 'announce a decision; announce publicly', root: '来自拉丁语 annunciare (宣告)' },
  { word: 'announcement', phonetic: '/əˈnaʊnsmənt/', pos: 'n.', meaning: '公告；宣布', eg: 'Read the announcement.', trans: '阅读公告。', coll: 'make an announcement; official announcement', root: 'announce (宣布) + -ment (名词后缀)' },
  { word: 'annoy', phonetic: '/əˈnɔɪ/', pos: 'v.', meaning: '使烦恼；使生气', eg: 'His behavior annoys me.', trans: '他的行为让我很烦。', coll: 'be annoyed by; annoy sb.', root: '来自古法语 anoier (打扰)' },
  { word: 'annual', phonetic: '/ˈænjuəl/', pos: 'adj.', meaning: '年度的；每年的', eg: 'Annual meeting.', trans: '年会。', coll: 'annual report; annual event', root: '来自拉丁语 annualis (每年的)' },
  { word: 'another', phonetic: '/əˈnʌðər/', pos: 'adj./pron.', meaning: '另一个；再一个', eg: 'Give me another chance.', trans: '再给我一次机会。', coll: 'another one; one after another', root: 'an (一) + other (其他)' },
  { word: 'answer', phonetic: '/ˈɑːnsər/', pos: 'n./v.', meaning: '回答；答案', eg: 'Answer the question.', trans: '回答问题。', coll: 'answer a question; answer the phone', root: '来自古英语 andswaru (回应)' },
  { word: 'ant', phonetic: '/ænt/', pos: 'n.', meaning: '蚂蚁', eg: 'An ant is small.', trans: '蚂蚁很小。', coll: 'ant colony; ant hill', root: '来自古英语 æmette (蚂蚁)' },
  { word: 'anticipate', phonetic: '/ænˈtɪsɪpeɪt/', pos: 'v.', meaning: '预期；提前', eg: 'Anticipate the future.', trans: '预见未来。', coll: 'anticipate problems; anticipate needs', root: '来自拉丁语 anticipare (提前)' },
  { word: 'anxiety', phonetic: '/æŋˈzaɪəti/', pos: 'n.', meaning: '焦虑；忧虑', eg: 'She felt anxiety before the exam.', trans: '考试前她感到焦虑。', coll: 'anxiety about; anxiety disorder', root: '来自拉丁语 anxietas (焦虑)' },
  { word: 'anxious', phonetic: '/ˈæŋkʃəs/', pos: 'adj.', meaning: '焦虑的；渴望的', eg: 'He is anxious to leave.', trans: '他急于离开。', coll: 'be anxious about; feel anxious', root: 'anxiety (焦虑) + -ous (形容词后缀)' },
  { word: 'any', phonetic: '/ˈeni/', pos: 'adj./pron.', meaning: '任何；一些', eg: 'Any questions?', trans: '有任何问题吗？', coll: 'any more; any time', root: '来自古英语 ænig (任何)' },
  { word: 'anybody', phonetic: '/ˈenibʌdi/', pos: 'pron.', meaning: '任何人；有人', eg: 'Anybody can do it.', trans: '任何人都能做到。', coll: 'anybody else; anybody there', root: 'any (任何) + body (人)' },
  { word: 'anyone', phonetic: '/ˈeniwʌn/', pos: 'pron.', meaning: '任何人；有人', eg: 'Is anyone here?', trans: '有人在吗？', coll: 'anyone else; anyone interested', root: 'any (任何) + one (一个)' },
  { word: 'anything', phonetic: '/ˈeniθɪŋ/', pos: 'pron.', meaning: '任何事；某事', eg: 'Do you want anything?', trans: '你想要点什么吗？', coll: 'anything else; anything special', root: 'any (任何) + thing (事物)' },
  { word: 'anyway', phonetic: '/ˈeniweɪ/', pos: 'adv.', meaning: '无论如何；总之', eg: 'Anyway, we tried our best.', trans: '无论如何，我们尽力了。', coll: 'anyway you look at it; but anyway', root: 'any (任何) + way (方式)' },
  { word: 'anywhere', phonetic: '/ˈeniwer/', pos: 'adv.', meaning: '任何地方；某处', eg: 'You can go anywhere.', trans: '你可以去任何地方。', coll: 'anywhere else; not anywhere', root: 'any (任何) + where (哪里)' },
  { word: 'apart', phonetic: '/əˈpɑːrt/', pos: 'adv.', meaning: '分开；离开', eg: 'Stand apart.', trans: '站开。', coll: 'apart from; set apart', root: 'a- (离开) + part (部分)' },
  { word: 'apartment', phonetic: '/əˈpɑːrtmənt/', pos: 'n.', meaning: '公寓；房间', eg: 'He lives in an apartment.', trans: '他住在公寓里。', coll: 'apartment building; one-bedroom apartment', root: 'apart (分开) + -ment (名词后缀)' },
  { word: 'apologize', phonetic: '/əˈpɑːlədʒaɪz/', pos: 'v.', meaning: '道歉；认错', eg: 'You should apologize.', trans: '你应该道歉。', coll: 'apologize to sb.; apologize for', root: '来自希腊语 apologia (辩护)' },
  { word: 'apology', phonetic: '/əˈpɑːlədʒi/', pos: 'n.', meaning: '道歉；歉意', eg: 'Make an apology.', trans: '道歉。', coll: 'offer an apology; accept an apology', root: '来自希腊语 apologia (辩护)' },
  { word: 'apparent', phonetic: '/əˈpærənt/', pos: 'adj.', meaning: '明显的；表面的', eg: 'It is apparent that...', trans: '很明显...', coll: 'apparent reason; become apparent', root: '来自拉丁语 apparens (出现)' },
  { word: 'apparently', phonetic: '/əˈpærəntli/', pos: 'adv.', meaning: '显然；似乎', eg: 'Apparently, he forgot.', trans: '显然，他忘了。', coll: 'apparently true; apparently not', root: 'apparent (明显的) + -ly (副词后缀)' },
  { word: 'appeal', phonetic: '/əˈpiːl/', pos: 'n./v.', meaning: '呼吁；吸引力', eg: 'The appeal was successful.', trans: '呼吁成功了。', coll: 'appeal to; make an appeal', root: '来自拉丁语 appellare (呼唤)' },
  { word: 'appear', phonetic: '/əˈpɪr/', pos: 'v.', meaning: '出现；看起来', eg: 'He appeared suddenly.', trans: '他突然出现。', coll: 'appear to be; appear in public', root: '来自拉丁语 apparere (出现)' },
  { word: 'appearance', phonetic: '/əˈpɪərəns/', pos: 'n.', meaning: '外观；出现', eg: 'Appearance is important.', trans: '外表很重要。', coll: 'make an appearance; personal appearance', root: 'appear (出现) + -ance (名词后缀)' },
  { word: 'appendix', phonetic: '/əˈpendɪks/', pos: 'n.', meaning: '附录；阑尾', eg: 'Check the appendix.', trans: '查看附录。', coll: 'appendix to; appendices', root: '来自拉丁语 appendix (附加)' },
  { word: 'appetite', phonetic: '/ˈæpɪtaɪt/', pos: 'n.', meaning: '食欲；欲望', eg: 'I have a good appetite.', trans: '我食欲很好。', coll: 'good appetite; lose one\'s appetite', root: '来自拉丁语 appetitus (渴望)' },
  { word: 'applaud', phonetic: '/əˈplɔːd/', pos: 'v.', meaning: '鼓掌；称赞', eg: 'The audience applauded loudly.', trans: '观众大声鼓掌。', coll: 'applaud sb. for; applaud the decision', root: '来自拉丁语 applaudere (鼓掌)' },
  { word: 'apple', phonetic: '/ˈæpl/', pos: 'n.', meaning: '苹果', eg: 'An apple a day keeps the doctor away.', trans: '一天一个苹果，医生远离我。', coll: 'apple pie; apple tree', root: '来自古英语 æppel (苹果)' },
  { word: 'application', phonetic: '/ˌæplɪˈkeɪʃn/', pos: 'n.', meaning: '应用；申请', eg: 'Submit your application.', trans: '提交你的申请。', coll: 'job application; application form', root: 'apply (应用) + -cation (名词后缀)' },
  { word: 'apply', phonetic: '/əˈplaɪ/', pos: 'v.', meaning: '应用；申请', eg: 'Apply for the job.', trans: '申请这份工作。', coll: 'apply for; apply to', root: '来自拉丁语 applicare (应用)' },
  { word: 'appoint', phonetic: '/əˈpɔɪnt/', pos: 'v.', meaning: '任命；指定', eg: 'Appoint a new manager.', trans: '任命一位新经理。', coll: 'appoint sb. as; be appointed', root: '来自拉丁语 appointare (指派)' },
  { word: 'appointment', phonetic: '/əˈpɔɪntmənt/', pos: 'n.', meaning: '任命；约会', eg: 'I have an appointment.', trans: '我有一个约会。', coll: 'make an appointment; keep an appointment', root: 'appoint (任命) + -ment (名词后缀)' },
  { word: 'appreciate', phonetic: '/əˈpriːʃieɪt/', pos: 'v.', meaning: '欣赏；感激', eg: 'I appreciate your help.', trans: '我感谢你的帮助。', coll: 'appreciate sb.\'s help; appreciate art', root: '来自拉丁语 appretiatus (估价)' },
  { word: 'approach', phonetic: '/əˈproʊtʃ/', pos: 'n./v.', meaning: '方法；接近', eg: 'A new approach to learning.', trans: '一种新的学习方法。', coll: 'approach to; approach sb.', root: '来自拉丁语 appropiare (接近)' },
  { word: 'appropriate', phonetic: '/əˈproʊpriət/', pos: 'adj./v.', meaning: '适当的；拨给', eg: 'Take appropriate action.', trans: '采取适当的行动。', coll: 'appropriate for; appropriate measures', root: '来自拉丁语 appropriatus (适合的)' },
  { word: 'approval', phonetic: '/əˈpruːvl/', pos: 'n.', meaning: '批准；赞成', eg: 'Get approval from the manager.', trans: '得到经理的批准。', coll: 'give approval; seek approval', root: 'approve (批准) + -al (名词后缀)' },
  { word: 'approve', phonetic: '/əˈpruːv/', pos: 'v.', meaning: '批准；赞成', eg: 'The committee approved the plan.', trans: '委员会批准了这个计划。', coll: 'approve of; approve a plan', root: '来自拉丁语 approbare (批准)' },
  { word: 'approximate', phonetic: '/əˈprɑːksɪmət/', pos: 'adj./v.', meaning: '近似的；近似', eg: 'The approximate time.', trans: '大概时间。', coll: 'approximate value; approximate to', root: '来自拉丁语 approximatus (接近)' },
  { word: 'approximately', phonetic: '/əˈprɑːksɪmətli/', pos: 'adv.', meaning: '大约；近似', eg: 'Approximately 100 people.', trans: '大约100人。', coll: 'approximately equal; approximately half', root: 'approximate (近似的) + -ly (副词后缀)' },
  { word: 'arbitrary', phonetic: '/ˈɑːrbɪtreri/', pos: 'adj.', meaning: '任意的；武断的', eg: 'An arbitrary decision.', trans: '一个武断的决定。', coll: 'arbitrary rule; arbitrary choice', root: '来自拉丁语 arbitrarius (判断的)' },
  { word: 'arch', phonetic: '/ɑːrtʃ/', pos: 'n./v.', meaning: '拱门；拱起', eg: 'The arch of the bridge.', trans: '桥的拱门。', coll: 'arch bridge; arch enemy', root: '来自拉丁语 arcus (弓)' },
  { word: 'architecture', phonetic: '/ˈɑːrkɪtektʃər/', pos: 'n.', meaning: '建筑；建筑学', eg: 'Modern architecture.', trans: '现代建筑。', coll: 'classical architecture; landscape architecture', root: '来自希腊语 architekton (建筑师)' },
  { word: 'area', phonetic: '/ˈeriə/', pos: 'n.', meaning: '区域；面积', eg: 'A large area of land.', trans: '一大片土地。', coll: 'urban area; rural area', root: '来自拉丁语 area (空地)' },
  { word: 'argue', phonetic: '/ˈɑːrɡjuː/', pos: 'v.', meaning: '争论；辩论', eg: 'They argued about politics.', trans: '他们争论政治。', coll: 'argue with; argue for', root: '来自拉丁语 arguere (证明)' },
  { word: 'argument', phonetic: '/ˈɑːrɡjumənt/', pos: 'n.', meaning: '争论；论点', eg: 'Present your argument.', trans: '提出你的论点。', coll: 'strong argument; valid argument', root: 'argue (争论) + -ment (名词后缀)' },
  { word: 'arise', phonetic: '/əˈraɪz/', pos: 'v.', meaning: '出现；上升', eg: 'A problem arose.', trans: '出现了一个问题。', coll: 'arise from; arise out of', root: '来自古英语 arisan (上升)' },
  { word: 'arm', phonetic: '/ɑːrm/', pos: 'n./v.', meaning: '手臂；武装', eg: 'He has strong arms.', trans: '他有强壮的手臂。', coll: 'arm in arm; take up arms', root: '来自古英语 earm (手臂)' },
  { word: 'army', phonetic: '/ˈɑːrmi/', pos: 'n.', meaning: '军队；陆军', eg: 'Join the army.', trans: '参军。', coll: 'army base; army officer', root: 'arm (武装) + -y (名词后缀)' },
  { word: 'around', phonetic: '/əˈraʊnd/', pos: 'prep./adv.', meaning: '围绕；大约', eg: 'Look around.', trans: '环顾四周。', coll: 'around the corner; all around', root: '来自古英语 aran (周围)' },
  { word: 'arrange', phonetic: '/əˈreɪndʒ/', pos: 'v.', meaning: '安排；整理', eg: 'Arrange the chairs.', trans: '整理椅子。', coll: 'arrange a meeting; arrange for', root: '来自古法语 arangier (安排)' },
  { word: 'arrangement', phonetic: '/əˈreɪndʒmənt/', pos: 'n.', meaning: '安排；布置', eg: 'Make arrangements.', trans: '做出安排。', coll: 'make arrangements; seating arrangement', root: 'arrange (安排) + -ment (名词后缀)' },
  { word: 'arrest', phonetic: '/əˈrest/', pos: 'n./v.', meaning: '逮捕；拘留', eg: 'The police made an arrest.', trans: '警察逮捕了一个人。', coll: 'under arrest; arrest warrant', root: '来自拉丁语 arrestare (阻止)' },
  { word: 'arrival', phonetic: '/əˈraɪvl/', pos: 'n.', meaning: '到达；到来', eg: 'His arrival was expected.', trans: '他的到来是预料之中的。', coll: 'on arrival; arrival time', root: 'arrive (到达) + -al (名词后缀)' },
  { word: 'arrive', phonetic: '/əˈraɪv/', pos: 'v.', meaning: '到达；抵达', eg: 'We arrived at the station.', trans: '我们到达了车站。', coll: 'arrive at; arrive in', root: '来自拉丁语 arrivare (到达)' },
  { word: 'arrow', phonetic: '/ˈæroʊ/', pos: 'n.', meaning: '箭；箭头', eg: 'Shoot an arrow.', trans: '射箭。', coll: 'bow and arrow; arrow sign', root: '来自古英语 arwe (箭)' },
  { word: 'art', phonetic: '/ɑːrt/', pos: 'n.', meaning: '艺术；美术', eg: 'She studied art.', trans: '她学习艺术。', coll: 'fine art; modern art', root: '来自拉丁语 ars (技艺)' },
  { word: 'article', phonetic: '/ˈɑːrtɪkl/', pos: 'n.', meaning: '文章；物品', eg: 'Read the article.', trans: '阅读这篇文章。', coll: 'newspaper article; article of clothing', root: '来自拉丁语 articulus (关节)' },
  { word: 'artificial', phonetic: '/ˌɑːrtɪˈfɪʃl/', pos: 'adj.', meaning: '人工的；人造的', eg: 'Artificial intelligence.', trans: '人工智能。', coll: 'artificial flowers; artificial light', root: '来自拉丁语 artificialis (人工的)' },
  { word: 'artist', phonetic: '/ˈɑːrtɪst/', pos: 'n.', meaning: '艺术家；艺人', eg: 'He is a famous artist.', trans: '他是一位著名的艺术家。', coll: 'pop artist; street artist', root: 'art (艺术) + -ist (从事者)' },
  { word: 'as', phonetic: '/æz/', pos: 'adv./conj.', meaning: '作为；像', eg: 'As a student.', trans: '作为一名学生。', coll: 'as soon as; as well as', root: '来自古英语 swa (如此)' },
  { word: 'ash', phonetic: '/æʃ/', pos: 'n.', meaning: '灰；灰烬', eg: 'The fire turned to ash.', trans: '火变成了灰烬。', coll: 'ash tree; volcanic ash', root: '来自古英语 æsc (灰)' },
  { word: 'ashamed', phonetic: '/əˈʃeɪmd/', pos: 'adj.', meaning: '羞愧的；惭愧的', eg: 'He felt ashamed.', trans: '他感到羞愧。', coll: 'be ashamed of; feel ashamed', root: '来自古英语 asceamian (羞愧)' },
  { word: 'aside', phonetic: '/əˈsaɪd/', pos: 'adv.', meaning: '在旁边；除了', eg: 'Put it aside.', trans: '把它放在一边。', coll: 'aside from; set aside', root: 'a- (在) + side (旁边)' },
  { word: 'ask', phonetic: '/æsk/', pos: 'v.', meaning: '问；请求', eg: 'Ask a question.', trans: '问一个问题。', coll: 'ask for; ask about', root: '来自古英语 ascian (询问)' },
  { word: 'asleep', phonetic: '/əˈsliːp/', pos: 'adj.', meaning: '睡着的', eg: 'The baby is asleep.', trans: '婴儿睡着了。', coll: 'fall asleep; fast asleep', root: 'a- (处于) + sleep (睡觉)' },
  { word: 'aspect', phonetic: '/ˈæspekt/', pos: 'n.', meaning: '方面；外观', eg: 'Consider all aspects.', trans: '考虑所有方面。', coll: 'different aspects; important aspect', root: '来自拉丁语 aspectus (看)' },
  { word: 'assemble', phonetic: '/əˈsembəl/', pos: 'v.', meaning: '组装；集合', eg: 'Assemble the parts.', trans: '组装零件。', coll: 'assemble a team; assemble quickly', root: '来自拉丁语 assembrare (聚集)' },
  { word: 'assembly', phonetic: '/əˈsembli/', pos: 'n.', meaning: '组装；集会', eg: 'The assembly line.', trans: '生产线。', coll: 'assembly line; general assembly', root: 'assemble (组装) + -y (名词后缀)' },
  { word: 'assert', phonetic: '/əˈsɜːrt/', pos: 'v.', meaning: '断言；宣称', eg: 'He asserted his innocence.', trans: '他宣称自己无罪。', coll: 'assert oneself; assert that', root: '来自拉丁语 asserere (主张)' },
  { word: 'assessment', phonetic: '/əˈsesmənt/', pos: 'n.', meaning: '评估；评价', eg: 'Make an assessment.', trans: '进行评估。', coll: 'performance assessment; risk assessment', root: 'assess (评估) + -ment (名词后缀)' },
  { word: 'assess', phonetic: '/əˈses/', pos: 'v.', meaning: '评估；评价', eg: 'Assess the situation.', trans: '评估情况。', coll: 'assess the damage; assess needs', root: '来自拉丁语 assessare (评估)' },
  { word: 'asset', phonetic: '/ˈæset/', pos: 'n.', meaning: '资产；优点', eg: 'She is an asset to the team.', trans: '她是团队的宝贵财富。', coll: 'fixed asset; asset management', root: '来自拉丁语 adesse (存在)' },
  { word: 'assign', phonetic: '/əˈsaɪn/', pos: 'v.', meaning: '分配；指派', eg: 'Assign tasks to workers.', trans: '给工人分配任务。', coll: 'assign to; assign a task', root: '来自拉丁语 assignare (分配)' },
  { word: 'assignment', phonetic: '/əˈsaɪnmənt/', pos: 'n.', meaning: '作业；任务', eg: 'Complete the assignment.', trans: '完成作业。', coll: 'homework assignment; group assignment', root: 'assign (分配) + -ment (名词后缀)' },
  { word: 'assist', phonetic: '/əˈsɪst/', pos: 'v.', meaning: '协助；帮助', eg: 'Assist the customer.', trans: '协助顾客。', coll: 'assist sb. with; assist in', root: '来自拉丁语 assistere (站立)' },
  { word: 'assistance', phonetic: '/əˈsɪstəns/', pos: 'n.', meaning: '援助；帮助', eg: 'Provide assistance.', trans: '提供帮助。', coll: 'financial assistance; technical assistance', root: 'assist (协助) + -ance (名词后缀)' },
  { word: 'assistant', phonetic: '/əˈsɪstənt/', pos: 'n./adj.', meaning: '助手；助理的', eg: 'He is my assistant.', trans: '他是我的助手。', coll: 'teaching assistant; personal assistant', root: 'assist (协助) + -ant (名词后缀)' },
  { word: 'associate', phonetic: '/əˈsoʊʃieɪt/', pos: 'v./n.', meaning: '关联；同事', eg: 'Associate with friends.', trans: '与朋友交往。', coll: 'associate with; associate professor', root: '来自拉丁语 associatus (联合)' },
  { word: 'association', phonetic: '/əˌsoʊʃiˈeɪʃn/', pos: 'n.', meaning: '协会；关联', eg: 'Join an association.', trans: '加入一个协会。', coll: 'trade association; professional association', root: 'associate (关联) + -ation (名词后缀)' },
  { word: 'assume', phonetic: '/əˈsuːm/', pos: 'v.', meaning: '假设；承担', eg: 'Assume the worst.', trans: '做最坏的假设。', coll: 'assume responsibility; assume that', root: '来自拉丁语 assumere (拿取)' },
  { word: 'assumption', phonetic: '/əˈsʌmpʃn/', pos: 'n.', meaning: '假设；假定', eg: 'Based on this assumption.', trans: '基于这个假设。', coll: 'make an assumption; wrong assumption', root: 'assume (假设) + -ption (名词后缀)' },
  { word: 'assure', phonetic: '/əˈʃʊr/', pos: 'v.', meaning: '保证；确保', eg: 'I assure you.', trans: '我向你保证。', coll: 'assure sb. of; assure oneself', root: '来自法语 assurer (确保)' },
  { word: 'astonish', phonetic: '/əˈstɑːnɪʃ/', pos: 'v.', meaning: '使惊讶；使吃惊', eg: 'The news astonished everyone.', trans: '这个消息让每个人都很惊讶。', coll: 'be astonished at; astonish sb.', root: '来自古法语 astonir (使惊讶)' },
  { word: 'at', phonetic: '/æt/', pos: 'prep.', meaning: '在；向', eg: 'At home.', trans: '在家。', coll: 'at school; at work', root: '来自古英语 æt (在)' },
  { word: 'atmosphere', phonetic: '/ˈætməsfɪr/', pos: 'n.', meaning: '大气；气氛', eg: 'The atmosphere is tense.', trans: '气氛很紧张。', coll: 'atmosphere pressure; family atmosphere', root: '来自希腊语 atmos (蒸汽) + sphaira (球)' },
  { word: 'atom', phonetic: '/ˈætəm/', pos: 'n.', meaning: '原子', eg: 'An atom is very small.', trans: '原子非常小。', coll: 'atomic bomb; atomic energy', root: '来自希腊语 atomos (不可分割的)' },
  { word: 'attach', phonetic: '/əˈtætʃ/', pos: 'v.', meaning: '附加；连接', eg: 'Attach the document.', trans: '附上文件。', coll: 'attach to; attach importance to', root: '来自拉丁语 attacare (固定)' },
  { word: 'attack', phonetic: '/əˈtæk/', pos: 'n./v.', meaning: '攻击；袭击', eg: 'Launch an attack.', trans: '发动攻击。', coll: 'attack on; under attack', root: '来自古法语 atacquer (攻击)' },
  { word: 'attempt', phonetic: '/əˈtempt/', pos: 'n./v.', meaning: '尝试；企图', eg: 'Make an attempt.', trans: '尝试一下。', coll: 'attempt to do; make an attempt', root: '来自拉丁语 attemptare (尝试)' },
  { word: 'attend', phonetic: '/əˈtend/', pos: 'v.', meaning: '参加；照料', eg: 'Attend the meeting.', trans: '参加会议。', coll: 'attend school; attend to', root: '来自拉丁语 attendere (注意)' },
  { word: 'attention', phonetic: '/əˈtenʃn/', pos: 'n.', meaning: '注意；注意力', eg: 'Pay attention.', trans: '注意。', coll: 'pay attention to; draw attention', root: 'attend (注意) + -tion (名词后缀)' },
  { word: 'attractive', phonetic: '/əˈtræktɪv/', pos: 'adj.', meaning: '有吸引力的；迷人的', eg: 'She is very attractive.', trans: '她非常迷人。', coll: 'attractive price; attractive offer', root: 'attract (吸引) + -ive (形容词后缀)' },
  { word: 'attribute', phonetic: '/əˈtrɪbjuːt/', pos: 'n./v.', meaning: '属性；归因', eg: 'Attribute the success to teamwork.', trans: '把成功归因于团队合作。', coll: 'attribute to; personal attribute', root: '来自拉丁语 attribuere (分配)' },
  { word: 'audience', phonetic: '/ˈɔːdiəns/', pos: 'n.', meaning: '观众；听众', eg: 'The audience applauded.', trans: '观众鼓掌。', coll: 'large audience; target audience', root: '来自拉丁语 audientia (听力)' },
  { word: 'audio', phonetic: '/ˈɔːdiˌoʊ/', pos: 'adj./n.', meaning: '音频的；音频', eg: 'Audio quality is good.', trans: '音频质量很好。', coll: 'audio book; audio system', root: '来自拉丁语 audire (听)' },
  { word: 'audit', phonetic: '/ˈɔːdɪt/', pos: 'n./v.', meaning: '审计；检查', eg: 'Conduct an audit.', trans: '进行审计。', coll: 'financial audit; audit report', root: '来自拉丁语 audire (听)' },
  { word: 'august', phonetic: '/ˈɔːɡəst/', pos: 'adj./n.', meaning: '威严的；八月', eg: 'August weather is hot.', trans: '八月天气很热。', coll: 'August holiday; august person', root: '来自拉丁语 augustus (神圣的)' },
  { word: 'aunt', phonetic: '/ɑːnt/', pos: 'n.', meaning: '阿姨；姑姑', eg: 'My aunt lives here.', trans: '我姑姑住在这里。', coll: 'aunt and uncle; great aunt', root: '来自拉丁语 amita (姑母)' },
  { word: 'author', phonetic: '/ˈɔːθər/', pos: 'n.', meaning: '作者；作家', eg: 'The author of the book.', trans: '这本书的作者。', coll: 'famous author; co-author', root: '来自拉丁语 auctor (创造者)' },
  { word: 'authority', phonetic: '/əˈθɔːrəti/', pos: 'n.', meaning: '权威；权力', eg: 'He has the authority to decide.', trans: '他有决定权。', coll: 'in authority; authority on', root: 'author (作者) + -ity (名词后缀)' },
  { word: 'automatic', phonetic: '/ˌɔːtəˈmætɪk/', pos: 'adj.', meaning: '自动的', eg: 'Automatic door.', trans: '自动门。', coll: 'automatic transmission; automatic system', root: '来自希腊语 automatos (自己行动)' },
  { word: 'automobile', phonetic: '/ˈɔːtəməbiːl/', pos: 'n.', meaning: '汽车', eg: 'Buy a new automobile.', trans: '买一辆新车。', coll: 'automobile industry; automobile insurance', root: 'auto- (自己) + mobile (移动的)' },
  { word: 'autumn', phonetic: '/ˈɔːtəm/', pos: 'n.', meaning: '秋天', eg: 'Autumn is beautiful.', trans: '秋天很美。', coll: 'autumn leaves; autumn harvest', root: '来自拉丁语 autumnus (秋天)' },
  { word: 'available', phonetic: '/əˈveɪləbl/', pos: 'adj.', meaning: '可用的；可获得的', eg: 'Is this room available?', trans: '这个房间可用吗？', coll: 'available for; make available', root: '来自拉丁语 availabilis (有用的)' },
  { word: 'average', phonetic: '/ˈævərɪdʒ/', pos: 'adj./n.', meaning: '平均的；平均数', eg: 'The average temperature.', trans: '平均温度。', coll: 'on average; average cost', root: '来自阿拉伯语 awar (损坏)' },
  { word: 'avoid', phonetic: '/əˈvɔɪd/', pos: 'v.', meaning: '避免；避开', eg: 'Try to avoid mistakes.', trans: '尽量避免错误。', coll: 'avoid doing; avoid contact', root: 'a- (离开) + void (空)' },
  { word: 'awake', phonetic: '/əˈweɪk/', pos: 'adj./v.', meaning: '醒着的；唤醒', eg: 'I am awake.', trans: '我醒着。', coll: 'stay awake; awake sb.', root: '来自古英语 awaecan (醒来)' },
  { word: 'award', phonetic: '/əˈwɔːrd/', pos: 'n./v.', meaning: '奖项；授予', eg: 'Win an award.', trans: '赢得奖项。', coll: 'award ceremony; award prize', root: '来自古英语 award (裁决)' },
  { word: 'aware', phonetic: '/əˈwer/', pos: 'adj.', meaning: '意识到的；知道的', eg: 'Be aware of the danger.', trans: '意识到危险。', coll: 'be aware of; make aware', root: '来自古英语 gewaer (谨慎的)' },
  { word: 'away', phonetic: '/əˈweɪ/', pos: 'adv.', meaning: '离开；远离', eg: 'Go away.', trans: '走开。', coll: 'far away; right away', root: '来自古英语 aweg (离开)' },
  { word: 'awful', phonetic: '/ˈɔːfl/', pos: 'adj.', meaning: '可怕的；糟糕的', eg: 'What an awful day!', trans: '多么糟糕的一天！', coll: 'awful weather; awful smell', root: 'awe (敬畏) + -ful (充满)' },
  { word: 'awkward', phonetic: '/ˈɔːkwərd/', pos: 'adj.', meaning: '尴尬的；笨拙的', eg: 'An awkward situation.', trans: '一个尴尬的局面。', coll: 'feel awkward; awkward moment', root: '来自古英语 awkeward (转向)' },
  { word: 'baby', phonetic: '/ˈbeɪbi/', pos: 'n.', meaning: '婴儿；宝贝', eg: 'The baby is crying.', trans: '婴儿在哭。', coll: 'baby boy; baby girl', root: '来自古英语 babe (婴儿)' },
  { word: 'back', phonetic: '/bæk/', pos: 'n./adj./adv.', meaning: '背部；后面的；向后', eg: 'Sit back.', trans: '坐回去。', coll: 'back to back; behind one\'s back', root: '来自古英语 bæc (背部)' },
  { word: 'background', phonetic: '/ˈbækɡraʊnd/', pos: 'n.', meaning: '背景；后台', eg: 'What is